-- 用法： Item('原文', '轉換規則')
local Item = require('cgroup/core').Item;

return {

name = 'IT',
description = '-{zh-cn:信息技术; zh-tw:資訊科技;}-',
content = {

{ type = 'text', text = [=[
{{NoteTA
|G1 = IT
|G2 = MediaWiki
}}
请在本页编辑[[Portal:資訊科技|資訊科技]]公共轉換組的全文轉換。

在编辑前，请阅读[[Help:手工字詞轉換]]及[[Wikipedia:字詞轉換處理/公共轉換組]]以了解基本的语法，特别注意语法中带有<code>=></code>的单向转换规则，若您没有充分理解该规则的涵义，请不要仓促修改。

為了方便尋找，請按英文字母表順序排列。

以下是與本頁面相關的公共轉換組：
{| class="wikitable"
! 公共轉換組 || 說明
|-
| [[Module:CGroup/Games]] || 電子遊戲相關
|-
| [[Module:CGroup/Windows]] || 微軟視窗作業系統及其相關組件
|-
| [[Module:CGroup/Electronics]] || 電子相關
|-
| [[Module:CGroup/Communication]] || 通訊相關
|-
| [[Module:CGroup/MediaWiki]] || MediaWiki相關
|-
|}

'''注意：'''部分开源技术相关条目需加上[[Module:CGroup/Copyright]]（版权／著作权术语公共转换组）。

{{HideH|參考資料}}
* 微軟
** [https://www.microsoft.com/Language/en-US/Search.aspx Language Portal]（多語言，品質仍需明察）
* 台灣正體
** [http://terms.naer.edu.tw/ 國家教育研究院雙語詞彙、學術名詞暨辭書資訊網]
** [http://www.terms.org.tw:8080/phrase/query.jsp 兩岸名詞對照查詢系統]
* 大陆简体
** [http://www.termonline.cn 术语在线]
** [http://dict.cnki.net/ CNKI翻译助手]
** [http://www.ptsn.net.cn/ 通标网]
{{HideF}}

备注：
* 此表格对于font的转换不适用于需要区分typeface（字体）和font（字型）的场合。在提及这两者区别的条目中，请用<code>-&#123;-|zh-cn:字体;zh-tw:字型&#125;-</nowiki></code>撤销转换。

== A ==
]=] },
Item('AI', 'zh-cn:人工智能; zh-sg:人工智慧; zh-tw:人工智慧; zh-hk:人工智能;'),
Item('access', 'zh-cn:访问; zh-tw:存取;'),
Item('access', '訪問=>zh-tw:存取; 訪問=>zh-hk:存取; 訪問=>zh-mo:存取;'),
Item('access control list', 'zh-cn:访问控制表; zh-tw:存取控制列表;'),
Item('access control list', '存取控制串列=>zh-cn:访问控制表; 存取控制串列=>zh-sg:访问控制表; 存取控制串列=>zh-my:访问控制表; zh-tw:存取控制列表;'),
Item('access Multiplexer', 'zh-cn:接入复用器; zh-tw:接取多工器;'),
Item('access Point', 'zh-cn:接入点; zh-tw:存取點;'),
Item('account', 'zh-cn:账号; zh-tw:帳號; zh-hk:賬號;'),
Item('account', 'zh-cn:账户; zh-tw:帳戶; zh-hk:賬戶;'),
Item('activation', 'zh-cn:激活; zh-tw:啟用;'),
Item('activation function', 'zh-cn:激活函数; zh-tw:啟用功能;'),
Item('adapter', 'zh-cn:适配器; zh-tw:配接器;'),
Item('add-on', 'zh-cn:附加组件; zh-tw:附加元件;'),
Item('address', 'zh-cn:地址; zh-tw:位址; zh-hk:地址;'),
Item('address bar', 'zh-cn:地址栏; zh-tw:網址列; zh-hk:地址列;'),
Item('addressing', 'zh-cn:寻址; zh-tw:定址; zh-hk:定址;'),
Item('addressing modes', 'zh-cn:寻址模式; zh-tw:定址模式; zh-hk:定址模式;'),
Item('advanced', 'zh-cn:高级; zh-tw:進階;'),
Item('advertising area', 'zh-cn:广告位; zh-tw:廣告區;'),
Item('agent-oriented programming', 'zh-cn:面向代理编程; zh-tw:代理人導向程式設計;'),
Item('album (online)', 'zh-cn:相册; zh-tw:相簿;'),
Item('algorithm', 'zh-cn:算法; zh-tw:演算法;'),
Item('allocation unit', 'zh-cn:分配单元; zh-tw:單位配置;'),
Item('analog', 'zh-cn:模拟; zh-tw:類比; zh-hk:模擬;'),
Item('analog broadcasting', 'zh-cn:模拟广播; zh-tw:類比廣播; zh-hk:模擬廣播;'),
Item('analog television', 'zh-cn:模拟电视; zh-tw:類比電視; zh-hk:模擬電視;'),
-- 港台的「殺毒」有時有「清除病毒」的意思
Item('antivirus', 'zh-cn:杀毒; zh-tw:防毒;'),
Item('AOL', 'zh-cn:美国在线; zh-tw:美國線上;'),
Item('application', 'zh-cn:应用程序; zh-tw:應用程式;'),
Item('application programming interface', 'zh-cn:应用程序接口; zh-tw:應用程式介面;'),
Item('archive', 'zh-cn:压缩包; zh-tw:壓縮檔;'),
Item('array (RAID)', 'zh-cn:服务器阵列; zh-sg:伺服器阵列; zh-tw:伺服器陣列;'),
Item('array (RAID)', 'zh-cn:硬盘阵列; zh-tw:硬碟陣列;'),
Item('array (RAID)', 'zh-cn:磁盘阵列; zh-tw:磁碟陣列;'),
Item('array (RAID)', 'zh-cn:阵列服务器; zh-sg:阵列伺服器; zh-tw:陣列伺服器;'),
Item('array (RAID)', 'zh-cn:阵列硬盘; zh-tw:陣列硬碟;'),
Item('array', 'zh-cn:数组; zh-tw:陣列;'),
Item('Artificial Neural', 'zh-cn:人工神經; zh-tw:類神經;'),
Item('assembler', 'zh-cn:汇编; zh-tw:組譯;'),
Item('Assembly language', 'zh-cn:汇编语言; zh-tw:組合語言; zh-hk:匯編語言;'),
Item('assembly mnemonic', 'zh-cn:助记符; zh-tw:輔助記憶碼;'),
Item('assignment operator', 'zh-cn:赋值运算符; zh-tw:設定運算子;'),
Item('assignment operator', '賦值運算符=>zh-tw:設定運算子; 賦值運算符=>zh-hk:設定運算子; 賦值運算符=>zh-mo:設定運算子;'),
Item('assignment operator', '赋值操作符=>zh-tw:設定運算子; 赋值操作符=>zh-hk:設定運算子; 赋值操作符=>zh-mo:設定運算子;'),
Item('assignment operator', '賦值操作符=>zh-tw:設定運算子; 賦值操作符=>zh-hk:設定運算子; 賦值操作符=>zh-mo:設定運算子;'),
Item('asynchrony', 'zh-cn:异步; zh-tw:非同步;'),
Item('asynchrony', '異步=>zh-hk:非同步; 異步=>zh-mo:非同步;'),
Item('average bitrate', 'zh-cn:平均码率; zh-tw:平均位元速率;'),
Item('audio', 'zh-cn:音频; zh-tw:音訊; zh-hk:音頻;'),
Item('audio track', 'zh-cn:音频轨; zh-tw:音訊軌; zh-hk:音頻軌;'),
Item('audio input', 'zh-cn:音频输入; zh-tw:音訊輸入; zh-hk:音頻輸入;'),
Item('audio output', 'zh-cn:音频输出; zh-tw:音訊輸出; zh-hk:音頻輸出;'),
Item('audio file', 'zh-cn:音频文件; zh-tw:音訊檔; zh-hk:音頻檔;'),
Item('audio file', 'zh-cn:音频文档; zh-tw:音訊檔; zh-hk:音頻檔;'),
Item('audio file', 'zh-cn:音频档; zh-tw:音訊檔; zh-hk:音頻檔;'),
Item('audio profiles', 'zh-cn:情景模式; zh-tw:音訊設定檔;'),
Item('audit', 'zh-cn:审核; zh-tw:稽核;'),
Item('augmented reality', 'zh-cn:增强现实; zh-tw:擴增實境; zh-hk:擴張實境;'),
{ type = 'text', text = [[

== B ==
]] },
Item('back chaining', 'zh-cn:反链接; zh-tw:反鏈結;'),
Item('background traffic', 'zh-cn:后台流量; zh-tw:背景流量;'),
Item('backward compatible', '向后兼容=>zh-tw:向下相容; 向后兼容=>zh-hk:向下相容; 向后兼容=>zh-mo:向下相容;'),
Item('backward compatible', '向後兼容=>zh-tw:向下相容; 向後兼容=>zh-hk:向下相容; 向後兼容=>zh-mo:向下相容;'),
Item('bad sector', 'zh-cn:坏道; zh-tw:壞軌;'),
Item('band width', 'zh-cn:带宽; zh-tw:頻寬;'),
Item('base class', 'zh-cn:基类; zh-tw:基礎類別;'),
Item('base name', 'zh-cn:文件主名; zh-tw:主檔名;'),
Item('base type', 'zh-cn:基类型; zh-tw:基本類型;'),
Item('baseband', 'zh-cn:基带; zh-hk:基帶; zh-tw:基頻;'),
Item('batch', 'zh-cn:批量; zh-tw:批次;'),
Item('batch', 'zh-cn:批处理; zh-tw:批次處理;'),
Item('batch file', 'zh-cn:批处理文件; zh-tw:批次檔;'),
Item('batch programs', 'zh-cn:批处理程序; zh-tw:批次程式;'),
Item('Berkeley Software Distribution', 'zh-cn:伯克利软件套件; zh-tw:柏克萊軟體套件; zh-hk:柏克萊軟件套件;'),
Item('big data', 'zh-cn:大数据; zh-tw:巨量資料; zh-hk:大數據;'),
Item('Bill Gates', 'zh-cn:盖茨; zh-tw:蓋茲; zh-hk:蓋茨;'),
Item('binary', '二叉=>zh-tw:二元; 二叉=>zh-hk:二元; 二叉=>zh-mo:二元;'),
Item('binary function', 'zh-cn:双参函数; zh-tw:二元函數;'),
Item('binary heap', 'zh-cn:二叉堆; zh-tw:二元堆積; zh-hk:二叉堆積;'),
Item('binary linked list', 'zh-cn:二叉链表; zh-tw:二元連結串列;'),
Item('binary linked list', '二叉鏈表=>zh-tw:二元連結串列; 二叉鏈表=>zh-hk:二元連結串列; 二叉鏈表=>zh-mo:二元連結串列;'),
Item('binary search tree', 'zh-cn:二叉搜索树; zh-tw:二元搜尋樹; zh-hk:二叉搜尋樹;'),
Item('binary search tree', '二叉查找树=>zh-tw:二元搜尋樹; 二叉查找树=>zh-hk:二叉搜尋樹; 二叉查找树=>zh-mo:二叉搜尋樹;'),
Item('binary tree', 'zh-cn:二叉树; zh-tw:二元樹; zh-hk:二叉樹;'),
Item('binding', 'zh-cn:绑定; zh-tw:繫結;'),
Item('bit', 'zh-cn:比特; zh-sg:位元; zh-tw:位元;'),
Item('bit', '二进制位=>zh-sg:位元; 二进制位=>zh-my:位元; 二进制位=>zh-tw:位元; 二进制位=>zh-hk:位元; 二进制位=>zh-mo:位元;'),
Item('bit (4-bit)', 'zh-cn:4位; zh-tw:4位元;'),
Item('bit (8-bit)', 'zh-cn:8位; zh-tw:8位元;'),
-- 有可能過度轉換，編輯時須注意
Item('bit (12-bit)', 'zh-cn:12位; zh-tw:12位元;'),
Item('bit (16-bit)', 'zh-cn:16位; zh-tw:16位元;'),
Item('bit (18-bit)', 'zh-cn:18位; zh-tw:18位元;'),
Item('bit (24-bit)', 'zh-cn:24位; zh-tw:24位元;'),
Item('bit (31-bit)', 'zh-cn:31位; zh-tw:31位元;'),
Item('bit (32-bit)', 'zh-cn:32位; zh-tw:32位元;'),
Item('bit (36-bit)', 'zh-cn:36位; zh-tw:36位元;'),
Item('bit (48-bit)', 'zh-cn:48位; zh-tw:48位元;'),
Item('bit (60-bit)', 'zh-cn:60位; zh-tw:60位元;'),
Item('bit (64-bit)', 'zh-cn:64位; zh-tw:64位元;'),
Item('bit (80-bit)', 'zh-cn:80位; zh-tw:80位元;'),
Item('bit (128-bit)', 'zh-cn:128位; zh-tw:128位元;'),
Item('bit error rate', 'zh-cn:比特误码率; zh-tw:位元錯誤率;'),
Item('bit error rate', '误比特率=>zh-tw:位元錯誤率; 误比特率=>zh-hk:位元錯誤率; 误比特率=>zh-mo:位元錯誤率;'),
Item('bit field', 'zh-cn:位段; zh-tw:位元欄;'),
Item('bit pattern', 'zh-cn:位模式; zh-tw:位元型樣;'),
Item('bit pattern', '位元模式=>zh-cn:位模式; 位元模式=>zh-sg:位模式; 位元模式=>zh-my:位模式;'),
Item('bit string', 'zh-cn:位串; zh-tw:位元串;'),
Item('Bitmap', '栅格图=>zh-tw:點陣圖;'),
Item('Bitmap', 'zh-cn:位图; zh-tw:點陣圖;'),
Item('bitrate', 'zh-cn:比特率; zh-tw:位元速率;'),
Item('bitrate', '码率=>zh-tw:位元速率; 码率=>zh-hk:位元速率; 码率=>zh-mo:位元速率;'),
Item('bitrate', '碼率=>zh-tw:位元速率; 碼率=>zh-hk:位元速率; 碼率=>zh-mo:位元速率;'),
Item('bitrate', '荷码率=>zh-tw:位元速率; 荷码率=>zh-hk:位元速率; 荷码率=>zh-mo:位元速率;'),
Item('bitrate', '荷碼率=>zh-tw:位元速率; 荷碼率=>zh-hk:位元速率; 荷碼率=>zh-mo:位元速率;'),
Item('bitwise', 'zh-cn:按位; zh-tw:按位元;'),
Item('bitwise operation', 'zh-cn:位操作; zh-tw:位元運算;'),
Item('bitwise operation', '位元运算=>zh-cn:位操作; 位元运算=>zh-sg:位操作; 位元运算=>zh-my:位操作;'),
Item('bitwise operation', '位元操作=>zh-cn:位操作; 位元操作=>zh-sg:位操作; 位元操作=>zh-my:位操作;'),
Item('bitwise operation', '位运算=>zh-tw:位元運算; 位运算=>zh-hk:位元運算; 位运算=>zh-mo:位元運算;'),
Item('bitwise operation', '位運算=>zh-tw:位元運算; 位運算=>zh-hk:位元運算; 位運算=>zh-mo:位元運算;'),
Item('black box testing', 'zh-cn:黑盒测试; zh-tw:黑箱測試;'),
Item('Blade Server', 'zh-cn:刀片服务器; zh-tw:刀鋒伺服器;'),
Item('blank screen', 'zh-cn:黑屏; zh-tw:黑畫面;'),
Item('block', 'zh-cn:屏蔽; zh-tw:封鎖;'),
Item('block (Unicode)', '区段=>zh-cn:区块; 区段=>zh-sg:区块; 区段=>zh-my:区块;'),
Item('block chaining', 'zh-cn:组链接; zh-tw:塊鏈結;'),
Item('block chaining', 'zh-cn:区块链接; zh-tw:區塊鏈結;'),
Item('block cipher', 'zh-cn:分组密码; zh-tw:區塊加密法;'),
Item('block diagram', 'zh-cn:框图; zh-tw:方塊圖;'),
Item('blog', 'zh-cn:博客; zh-tw:部落格; zh-hk:網誌; zh-sg:部落格;'),
Item('Blue Screen of Death', 'zh-cn:蓝屏死机; zh-tw:藍白當機; zh-hk:藍畫面死機;'),
Item('boot', 'zh-cn:引导; zh-tw:啟動; zh-hk:開機;'),
Item('boot disk', 'zh-cn:启动盘; zh-tw:啟動磁碟;'),
Item('boot loader', 'zh-cn:启动引导程序; zh-tw:啟動載入程式;'),
Item('bottom-up', 'zh-cn:自底向上; zh-tw:由下而上;'),
Item('Boyce-Codd normal form', 'zh-cn:BC范式; zh-tw:BC正規形式;'),
Item('brain-machine interface', 'zh-cn:脑机接口; zh-tw:人機介面;'),
Item('Broadband', 'zh-cn:宽带; zh-tw:寬頻;'),
Item('Bubble sort', 'zh-cn:冒泡排序; zh-tw:泡沫排序;'),
Item('buffer', 'zh-cn:缓冲器; zh-tw:緩衝區;'),
Item('buffer overflow', 'zh-cn:缓存溢出; zh-tw:緩衝區溢位;'),
Item('bug', '隐错=>zh-tw:錯誤; 隐错=>zh-hk:錯誤; 隐错=>zh-mo:錯誤;'),
Item('build-in', 'zh-cn:内置; zh-tw:內建;'),
Item('Built-in', '自带=>zh-tw:內建; 自带=>zh-hk:內建; 自带=>zh-mo:內建;'),
Item('Built-in', '自帶=>zh-tw:內建; 自帶=>zh-hk:內建; 自帶=>zh-mo:內建;'),
Item('Built-in', '內置=>zh-tw:內建'),
Item('burn', 'zh-cn:刻录; zh-tw:燒錄;'),
Item('Business Model', 'zh-cn:商业模型; zh-tw:商業模式;'),
Item('Bus', 'zh-cn:总线; zh-tw:匯流排; zh-hk:匯流排;'),
Item('byte', 'zh-cn:字节; zh-tw:位元組;'),
Item('byte', '字節=>zh-tw:位元組; 字節=>zh-hk:位元組; 字節=>zh-mo:位元組;'),
Item('boolean', 'zh-cn:布尔; zh-tw:布林;'),
Item('boolean algebra', 'zh-cn:布尔逻辑; zh-tw:布林運算;'),
Item('Boot Camp', 'zh-cn:启动转换; zh-tw:啟動切換; zh-hk:開機切換;'),
{ type = 'text', text = [[

== C ==
]] },
Item('cache', 'zh-cn:缓存; zh-tw:快取; zh-hk:快取;'),
Item('cache', '緩存=>zh-tw:快取;'),
Item('cache memory', 'zh-cn:缓冲存储器; zh-tw:快取記憶體;'),
Item('cache memory', '缓冲存储器=>zh-hk:緩衝記憶體; 缓冲存储器=>zh-mo:緩衝記憶體;'),
Item('cache memory', '缓存器=>zh-tw:快取記憶體; 缓存器=>zh-hk:緩衝記憶體; 缓存器=>zh-mo:緩衝記憶體;'),
Item('cache memory', '快取記憶體=>zh-hk:緩衝記憶體; 快取記憶體=>zh-mo:緩衝記憶體;'),
Item('cache memory', 'zh-cn:高速缓冲存储器; zh-tw:高速緩衝記憶體;'),
Item('cache memory', '高速缓存=>zh-tw:高速緩衝記憶體; 高速缓存=>zh-hk:高速緩衝記憶體; 高速缓存=>zh-mo:高速緩衝記憶體;'),
Item('cached webpage', 'zh-cn:网页快照; zh-tw:頁庫存檔;'),
Item('calculator', 'zh-cn:计算器; zh-hk:計數機;'),
Item('calculator', '计算器=>zh-tw:計算機;'),
Item('calculator', '計數機=>zh-tw:計算機;'),
Item('calculator', '計算器=>zh-hk:計數機; 計算器=>zh-mo:計數機;'),
Item('calendar', '行事曆=>zh-cn:日历; 行事曆=>zh-sg:日历; 行事曆=>zh-my:日历;'),
Item('calendar program', 'zh-cn:日历程序; zh-tw:行事曆程式;'),
Item('call', 'zh-cn:调用; zh-tw:呼叫;'),
Item('Call Level Interface (CLI)', 'zh-cn:调用层接口; zh-tw:呼叫層級介面;'),
-- 回撥似乎用在電話比較多，計算機上回呼比較多。
Item('callback', 'zh-cn:回调; zh-tw:回呼;'),
Item('camcorder', 'zh-cn:摄像机; zh-tw:攝錄影機; zh-hk:攝像放像機;'),
Item('camera phone', 'zh-cn:照相手机; zh-tw:照相手機; zh-hk:相機手機;'),
Item('campus network', 'zh-cn:校园网; zh-tw:校園網路; zh-hk:校園網絡;'),
Item('campus network', '园区网络=>zh-tw:校園網路; 园区网络=>zh-hk:校園網絡; 园区网络=>zh-mo:校園網絡;'),
Item('capture', '捕获=>zh-tw:擷取; 捕获=>zh-hk:擷取; 捕获=>zh-mo:擷取;'),
Item('card reader', 'zh-cn:读卡器; zh-tw:讀卡機; zh-hk:讀卡器;'),
Item('carriage return character', 'zh-cn:回车符; zh-tw:回車字元;'),
Item('CDN', 'zh-cn:内容分发网络; zh-tw:內容傳遞網路;'),
Item('Cell', 'zh-cn:单元格; zh-tw:儲存格;'),
Item('Cellular data', 'zh-cn:蜂窝数据; zh-tw:蜂巢式資料; zh-hk:蜂巢式數據;'),
Item('Cellular network', 'zh-cn:蜂窝网络; zh-tw:蜂巢式網路; zh-hk:蜂巢式網絡;'),
Item('certificate', 'zh-cn:证书; zh-tw:憑證; zh-hk:證書;'),
Item('chain', '串鏈=>zh-cn:链; 串鏈=>zh-sg:链; 串鏈=>zh-my:链;'),
Item('chaining', '鍊接=>zh-cn:链接; 鍊接=>zh-sg:链接; 鍊接=>zh-my:链接;'),
Item('chaining backward', 'zh-cn:链接反向; zh-tw:鏈結反向;'),
Item('chaining forward', 'zh-cn:链接正向; zh-tw:鏈結正向;'),
Item('chaining of commands', 'zh-cn:命令链接; zh-tw:命令鏈結;'),
Item('chaining search', 'zh-cn:链接搜索; zh-tw:鏈結搜尋;'),
Item('channel', '渠道=>zh-tw:管道;'),
Item('character', 'zh-cn:字符; zh-tw:字元;'),
Item('character generator', 'zh-cn:字符生成器; zh-tw:字元產生器;'),
Item('character printer', 'zh-cn:字符打印机; zh-tw:字元列印機;'),
Item('check bit', 'zh-cn:检验位; zh-tw:核對位元;'),
Item('check button', 'zh-cn:复选按钮; zh-tw:核取按鈕;'),
Item('checkbox', 'zh-cn:复选框; zh-tw:核取方塊;'),
Item('checksum', 'zh-cn:检验和; zh-tw:核對和;'),
Item('Chief Executive Officer (CEO)', 'zh-cn:首席执行官; zh-tw:執行長; zh-hk:行政總裁;'),
Item('Chief Information Officer (CIO)', 'zh-cn:首席信息官; zh-tw:資訊長; zh-hk:資訊總監;'),
Item('Chief Operating Officer (COO)', 'zh-cn:首席运营官; zh-tw:營運長; zh-hk:營運總監;'),
Item('Chief Technology Officer (CTO)', 'zh-cn:首席技术官; zh-tw:技術長;'),
Item('child class', '子類別=>zh-cn:子类; 子類別=>zh-sg:子类; 子類別=>zh-my:子类;'),
Item('chip', 'zh-cn:芯片; zh-tw:晶片;'),
Item('class constructor', 'zh-cn:类的构造函数; zh-tw:類別的建構函數;'),
Item('class constructor', '類別建構子=>zh-cn:类的构造函数; 類別建構子=>zh-sg:类的构造函数; 類別建構子=>zh-my:类的构造函数;'),
Item('class declaration', 'zh-cn:类声明; zh-tw:類別宣告;'),
Item('class definition', 'zh-cn:类定义; zh-tw:類別定義;'),
Item('class destructor', 'zh-cn:类的析构函数; zh-tw:類別的破壞函數;'),
Item('class destructor', '類別破壞子=>zh-cn:类的析构函数; 類別破壞子=>zh-sg:类的析构函数; 類別破壞子=>zh-my:类的析构函数;'),
Item('class instance', 'zh-cn:类的实例; zh-tw:類別的實例;'),
Item('class instance', 'zh-cn:类实例; zh-tw:類別實例;'),
Item('class library', 'zh-cn:类库; zh-tw:類別館;'),
Item('class member', 'zh-cn:类成员; zh-tw:類別成員;'),
Item('class method', 'zh-cn:类方法; zh-tw:類別方法;'),
Item('class of C++', 'zh-cn:C++类; zh-tw:C++類別;'),
Item('class of C++', 'zh-cn:C++的类; zh-tw:C++的類別;'),
Item('class of Java', 'zh-cn:Java类; zh-tw:Java類別;'),
Item('class of Java', 'zh-cn:Java的类; zh-tw:Java的類別;'),
Item('class template', 'zh-cn:类模板; zh-tw:類別模板;'),
Item('class variable', 'zh-cn:类变量; zh-tw:類別變數;'),
Item('class-based', 'zh-cn:基于类; zh-tw:類別為基;'),
Item('class-based programming', 'zh-cn:基于类的编程; zh-tw:類別為基的程式設計;'),
Item('class-orientation', 'zh-cn:面向类; zh-tw:類別導向;'),
Item('classloader', 'zh-cn:类加载器; zh-tw:類別載入器;'),
Item('client', '用戶端=>zh-cn:客户端; 用戶端=>zh-sg:客户端; 用戶端=>zh-my:客户端;'),
Item('clipboard', 'zh-cn:剪贴板; zh-tw:剪貼簿;'),
Item('clock rate', '時鐘頻率=>zh-tw:時脈速率;'),
Item('clock rate', '時脈速率=>zh-cn:时钟频率; 時脈速率=>zh-sg:时钟频率; 時脈速率=>zh-my:时钟频率;'),
-- 国立编译馆的翻译
Item('clock rate', '時鐘率=>zh-cn:时钟频率; 時鐘率=>zh-sg:时钟频率; 時鐘率=>zh-my:时钟频率;'),
-- 容易過度轉換
Item('cloud computing', 'zh-cn:云计算; zh-tw:雲端運算;'),
Item('cloud computing storage', 'zh-cn:云存储; zh-tw:雲端儲存;'),
Item('cluster', 'zh-cn:集群; zh-tw:叢集;'),
Item('cluster', '群集=>zh-cn:聚类; 群集=>zh-sg:聚类; 群集=>zh-my:聚类;'),
Item('code', '程式碼=>zh-cn:代码; 程式碼=>zh-sg:代码; 程式碼=>zh-my:代码;'),
Item('code generator', 'zh-cn:代码生成器; zh-tw:碼產生器;'),
Item('code page', '代码页=>zh-tw:頁碼; 代码页=>zh-hk:頁碼; 代码页=>zh-mo:頁碼;'),
Item('collaboration', 'zh-cn:协作; zh-tw:協同運作;'),
Item('color monitor', '彩屏=>zh-tw:彩色螢幕; 彩屏=>zh-hk:彩色熒幕; 彩屏=>zh-mo:彩色熒幕;'),
Item('combobox', 'zh-cn:组合框; zh-tw:組合方塊;'),
Item('command line', 'zh-hant:命令列;zh-hans:命令行;'),
-- 有可能過度轉換，編輯時須注意
Item('communication', '通訊=>zh-cn:通信; 通訊=>zh-sg:通信; 通訊=>zh-my:通信;'),
Item('Communicating sequential processes', 'zh-cn:通信顺序进程; zh-tw:交談循序程式;'),
Item('community', '社区=>zh-tw:社群;'),
-- 有可能過度轉換，編輯時須注意
Item('compact disc', 'zh-cn:光盘; zh-tw:光碟;'),
Item('compact disc', '光碟片=>zh-cn:光盘; 光碟片=>zh-sg:光盘; 光碟片=>zh-my:光盘;'),
Item('Compact Disc Driver', 'zh-cn:光盘驱动器; zh-tw:光碟機;'),
Item('compatible', 'zh-cn:兼容; zh-tw:相容;'),
Item('compatible', '相兼容=>zh-tw:相容; 相兼容=>zh-hk:相容; 相兼容=>zh-mo:相容;'),
Item('complement', '補數=>zh-cn:补码; 補數=>zh-sg:补码; 補數=>zh-my:补码; 補數=>zh-hk:補碼; 補數=>zh-mo:補碼;'),
Item('complexity class', 'zh-cn:复杂性类; zh-tw:複雜性類別;'),
Item('complexity class', 'zh-cn:复杂度类; zh-tw:複雜度類別;'),
Item('component', '元件=>zh-cn:组件; 元件=>zh-sg:组件; 元件=>zh-my:组件;'),
Item('computer', '计算机=>zh-sg:电脑; 计算机=>zh-my:电脑; 计算机=>zh-tw:電腦; 计算机=>zh-hk:電腦; 计算机=>zh-mo:電腦;'),
Item('computer', '計算機=>zh-sg:电脑; 計算機=>zh-my:电脑;'),
Item('computer', '电子计算机=>zh-sg:电脑; 电子计算机=>zh-my:电脑; 电子计算机=>zh-tw:電腦; 电子计算机=>zh-hk:電腦; 电子计算机=>zh-mo:電腦;'),
Item('computer', '電子計算機=>zh-cn:电子计算机; 電子計算機=>zh-sg:电脑; 電子計算機=>zh-my:电脑;'),
Item('computer architecture', 'zh-cn:计算机体系结构; zh-tw:電腦架構;'),
Item('computer programming', 'zh-cn:程序设计; zh-tw:程式設計;'),
Item('computer science', 'zh-cn:计算机科学; zh-sg:电脑科学; zh-tw:電腦科學;'),
Item('computer terminal', '終端機=>zh-cn:终端; 終端機=>zh-sg:终端; 終端機=>zh-my:终端;'),
Item('concurrency', 'zh-cn:并发; zh-tw:並行;'),
Item('concurrent computing', 'zh-cn:并发计算; zh-tw:並行計算;'),
Item('concurrency-oriented', 'zh-cn:面向并发; zh-tw:平行導向;'),
Item('configure/configuration', 'zh-cn:配置; zh-tw:組態;'),
Item('configuration files', 'zh-cn:配置文件; zh-tw:組態檔;'),
-- Item('connection', 'zh-cn:连接; zh-tw:連線;'), 容易過度轉換
Item('constant', 'zh-cn:常量; zh-tw:常數;'),
Item('constant bitrate', 'zh-cn:固定码率; zh-tw:固定位元速率;'),
Item('constructor', 'zh-cn:构造函数; zh-tw:建構函式;'),
Item('constructor', '建構子=>zh-cn:构造函数; 建構子=>zh-sg:构造函数; 建構子=>zh-my:构造函数;'),
Item('contact', 'zh-cn:联系; zh-tw:聯絡;'),
Item('contact', '連絡=>zh-cn:联系; 連絡=>zh-sg:联系; 連絡=>zh-my:联络;'),
Item('contact', 'zh-cn:联系人; zh-tw:聯絡人;'),
Item('content-addressable memory', 'zh-cn:内容可寻址存储器; zh-tw:可定址內容記憶體;'),
Item('content-addressable memory', 'zh-cn:结合存储; zh-tw:可定址內容記憶體;'),
Item('context switch', 'zh-cn:上下文切换; zh-tw:上下文交換;'),
Item('Continuity', 'zh-cn:连续互通; zh-tw:接續互通;'),
Item('control', 'zh-cn:控件; zh-tw:控制項;'),
Item('convert', '轉檔=>zh-cn:转换; 轉檔=>zh-sg:转换; 轉檔=>zh-my:转换;'),
Item('copper clad laminate', 'zh-cn:覆铜板; zh-tw:銅箔基板;'),
Item('copyright', 'zh-cn:著作权; zh-tw:著作權; zh-hk:版權; zh-mo:著作權;'),
Item('copyright', '版权=>zh-cn:著作权; 版权=>zh-sg:著作权; 版权=>zh-my:著作权; 版权=>zh-tw:著作權; 版权=>zh-mo:著作權;'),
Item('copyright information', '版权信息=>zh-cn:著作权信息; 版权信息=>zh-sg:著作权信息; 版权信息=>zh-my:著作权信息; 版权信息=>zh-tw:著作權資訊; 版权信息=>zh-mo:著作權資訊;'),
Item('cost-effective', 'zh-cn:性价比; zh-tw:CP值; zh-hk:性價比;'),
Item('cracker', 'zh-cn:溃客; zh-tw:劊客; zh-hk:潰客;'),
Item('crash', 'zh-cn:死机; zh-tw:當機;'),
Item('create', 'zh-cn:创建; zh-tw:建立;'),
Item('create', '創建=>zh-tw:建立; 創建=>zh-hk:建立; 創建=>zh-mo:建立;'),
Item('CRT', 'zh-cn:显像管; zh-tw:映像管; zh-hk:顯像管;'),
Item('current version', 'zh-cn:当前版本; zh-tw:目前版本;'),
Item('cursor', 'zh-cn:光标; zh-tw:游標;'),
Item('custom', 'zh-cn:自定义; zh-tw:自訂;'),
Item('custom', '自定義=>zh-tw:自訂; 自定義=>zh-hk:自訂; 自定義=>zh-mo:自訂;'),
Item('custom', '自定=>zh-tw:自訂; 自定=>zh-hk:自訂; 自定=>zh-mo:自訂;'),
Item('customization', 'zh-cn:定制; zh-tw:客製化;'),
Item('cut', 'zh-cn:剪切; zh-tw:剪下;'),
Item('cyberbullying', 'zh-cn:网络欺凌; zh-tw:網路霸凌; zh-hk:網上欺凌;'),
{ type = 'text', text = [[

== D ==
]] },
Item('daemon', 'zh-cn:守护进程; zh-tw:守護行程;'),
Item('daisy chaining', 'zh-cn:菊花链接; zh-tw:菊式鏈結;'),
Item('data', '数据=>zh-tw:資料; 数据=>zh-hk:數據;'),
Item('database', 'zh-cn:数据库; zh-tw:資料庫; zh-hk:數據庫;'),
Item('data center', 'zh-cn:数据中心; zh-hk:數據中心; zh-tw:資料中心;'),
Item('data chaining', 'zh-cn:数据链接; zh-tw:資料鏈結;'),
Item('data cleansing', 'zh-cn:数据清洗; zh-tw:資料淨化;'),
Item('data dredging', 'zh-cn:数据捕捞; zh-tw:資料挖掘; zh-hk:數據捕撈;'),
Item('data execution protection', 'zh-cn:数据执行保护; zh-tw:系統記憶體保護; zh-hk:數據執行保護;'),
Item('data frame', 'zh-cn:数据帧; zh-tw:資料框; zh-hk:數據幀;'),
Item('data mart', 'zh-cn:数据集市; zh-tw:資料市集; zh-hk:數據市集;'),
Item('data mining', 'zh-cn:数据挖掘; zh-tw:資料探勘; zh-hk:數據探勘;'),
Item('data packet', 'zh-cn:数据包; zh-tw:封包;'),
Item('data packet', '数据封包=>zh-cn:数据包; 数据封包=>zh-sg:数据包; 数据封包=>zh-my:数据包;'),
Item('data packet', '數據封包=>zh-cn:数据包; 數據封包=>zh-sg:数据包; 數據封包=>zh-my:数据包;'),
Item('data packet', '資料封包=>zh-cn:数据包; 資料封包=>zh-sg:数据包; 資料封包=>zh-my:数据包;'),
Item('data source', 'zh-cn:数据源; zh-tw:資料來源; zh-hk:數據源;'),
Item('data warehouse', 'zh-cn:数据仓库; zh-tw:資料倉儲; zh-hk:數據倉庫;'),
Item('datagram', 'zh-cn:数据报文;zh-tw:資料報;'),
Item('deadlock', 'zh-cn:死锁; zh-tw:死結;'),
Item('debug', 'zh-cn:调试; zh-tw:除錯;'),
Item('debug', '除错=>zh-cn:调试; 除错=>zh-sg:调试; 除错=>zh-my:调试;'),
Item('debug', '偵錯=>zh-cn:调试; 偵錯=>zh-sg:调试; 偵錯=>zh-my:调试;'),
Item('debug', '侦错=>zh-cn:调试; 侦错=>zh-sg:调试; 侦错=>zh-my:调试;'),
Item('debug', '調試=>zh-tw:除錯; 調試=>zh-hk:除錯; 調試=>zh-mo:除錯;'),
Item('declaration', '声明语句=>zh-tw:宣告; 声明语句=>zh-hk:宣告; 声明语句=>zh-mo:宣告;'),
Item('decode', '译码=>zh-tw:解碼;'),
Item('default', 'zh-cn:默认; zh-tw:預設;'),
Item('default', '缺省=>zh-tw:預設; 缺省=>zh-hk:預設; 缺省=>zh-mo:預設;'),
Item('definition', '清晰度=>zh-tw:解析度;'),
Item('defragmentation program', 'zh-cn:磁盘碎片整理程序; zh-tw:磁碟重組工具;'),
Item('defragmentation', 'zh-cn:磁盘碎片整理; zh-tw:磁碟重組;'),
Item('denial-of-service (DoS)', 'zh-cn:拒绝服务; zh-tw:阻斷服務;'),
Item('denormalization', 'zh-cn:反规范化; zh-tw:解除規格化;'),
Item('dependent type', 'zh-cn:依赖类型; zh-tw:依值型別;'),
Item('dependent type', 'zh-cn:依存类型; zh-tw:依存型別;'),
Item('derivation list', 'zh-cn:继承列表; zh-tw:衍化列;'),
Item('derive', 'zh-cn:派生; zh-tw:衍生;'),
Item('derived class', 'zh-cn:派生类; zh-tw:衍生類別;'),
Item('derived type', 'zh-cn:派生类型; zh-tw:衍生類型;'),
Item('desktop', 'zh-cn:桌面型; zh-tw:桌上型;'),
Item('desktop computer', 'zh-cn:台式机; zh-tw:桌上型電腦; zh-hk:桌上電腦;'),
Item('desktop computer', '桌上型电脑=>zh-cn:台式机; 桌上型电脑=>zh-sg:台式机; 桌上型电脑=>zh-my:台式机; 桌上型电脑=>zh-hk:桌上電腦; 桌上型电脑=>zh-mo:桌上電腦;'),
Item('desktop computer', '桌上电脑=>zh-cn:台式机; 桌上电脑=>zh-sg:台式机; 桌上电脑=>zh-my:台式机; 桌上电脑=>zh-tw:桌上型電腦;'),
Item('desktop computer', '台式機=>zh-tw:桌上型電腦; 台式機=>zh-hk:桌上電腦; 台式機=>zh-mo:桌上電腦;'),
Item('desktop computer', '臺式機=>zh-tw:桌上型電腦; 臺式機=>zh-hk:桌上電腦; 臺式機=>zh-mo:桌上電腦;'),
Item('desktop computer', '台式计算机=>zh-tw:桌上型電腦; 台式计算机=>zh-hk:桌上電腦; 台式计算机=>zh-mo:桌上電腦;'),
Item('desktop computer', '台式电脑=>zh-tw:桌上型電腦; 台式电脑=>zh-hk:桌上電腦; 台式电脑=>zh-mo:桌上電腦;'),
Item('desktop computer', '台式電腦=>zh-tw:桌上型電腦; 台式電腦=>zh-hk:桌上電腦; 台式電腦=>zh-mo:桌上電腦;'),
Item('desktop computer', '桌上型计算机=>zh-hk:桌上電腦; 桌上型计算机=>zh-mo:桌上電腦;'),
Item('desktop computer', '桌上型計算機=>zh-hk:桌上電腦; 桌上型計算機=>zh-mo:桌上電腦;'),
Item('desktop computer', '桌上計算機=>zh-tw:桌上型電腦;'),
Item('desktop version', '桌面版=>zh-tw:電腦版; 桌面版=>zh-hk:電腦版; 桌面版=>zh-mo:電腦版;'),
Item('destruct', 'zh-cn:析构; zh-tw:解構;'),
Item('destructor', 'zh-cn:析构函数; zh-tw:解構函式;'),
Item('destructor', '解構子=>zh-cn:析构函数; 解構子=>zh-sg:析构函数; 解構子=>zh-my:析构函数;'),
Item('device', 'zh-cn:设备; zh-tw:裝置;'),
Item('device', '装置=>zh-cn:设备; 装置=>zh-sg:设备; 装置=>zh-my:设备;'),
Item('device', '設備=>zh-tw:裝置; 設備=>zh-hk:裝置; 設備=>zh-mo:裝置;'),
Item('dialog box', 'zh-cn:对话框; zh-tw:對話方塊;'),
Item('digital', '数码=>zh-tw:數位;'),
Item('digital', '數碼=>zh-cn:数字; 數碼=>zh-sg:数字; 數碼=>zh-my:数字; 數碼=>zh-tw:數位;'),
Item('digital', '数位=>zh-hk:數碼; 数位=>zh-mo:數碼;'),
Item('digital', '數位=>zh-cn:数字; 數位=>zh-sg:数字; 數位=>zh-my:数字; 數位=>zh-hk:數碼; 數位=>zh-mo:數碼;'),
Item('digitalisation', 'zh-cn:数字化; zh-tw:數位化; zh-hk:數碼化;'),
Item('digital', 'zh-cn:数字图像; zh-tw:數位影像; zh-hk:數碼圖像;'),
Item('digital', 'zh-cn:数字化; zh-my:数码化; zh-tw:數位化; zh-hk:數碼化;'),
Item('digital asset', 'zh-cn:数字资产; zh-tw:數位資產; zh-hk:數碼資產;'),
Item('digital broadcasting', 'zh-cn:数字广播; zh-tw:數位廣播; zh-hk:數碼廣播;'),
Item('digital camera', 'zh-cn:数字相机; zh-my:数码相机; zh-tw:數位相機; zh-hk:數碼相機;'),
Item('digital certificates', 'zh-cn:数字证书; zh-tw:數位憑證; zh-hk:數碼證書;'),
Item('digital distribution', 'zh-cn:数字发行; zh-tw:數位發行; zh-hk:數碼發行;'),
Item('digital identity', 'zh-cn:数字身份; zh-tw:數位身分; zh-hk:數碼身份;'),
Item('digital mapping', 'zh-cn:数字测图; zh-tw:數位製圖; zh-hk:數碼製圖;'),
Item('digital mobile', 'zh-cn:数字移动; zh-tw:數位行動; zh-hk:數碼流動;'),
Item('digital mode', 'zh-cn:数字模式; zh-tw:數位模式; zh-hk:數碼模式;'),
Item('digital photo', 'zh-cn:数字照片; zh-tw:數位相片; zh-hk:數碼相片;'),
Item('digital right', 'zh-cn:数字版权; zh-tw:數位版權; zh-hk:數碼版權;'),
Item('digital signature', 'zh-cn:数字签名; zh-tw:數位簽章; zh-hk:數碼簽章;'),
Item('digital television', 'zh-cn:数字电视; zh-tw:數位電視; zh-hk:數碼電視;'),
Item('digital terrestrial television', 'zh-cn:数字地面电视; zh-tw:數位無線電視; zh-hk:數碼地面電視;'),
Item('digital video', 'zh-cn:数字视频; zh-tw:數位影片; zh-hk:數碼影片;'),
Item('digital video', 'zh-hans:视频;zh-hant:影片;'),
Item('digital video', '視像=>zh-tw:視訊; 視像=>zh-cn:视频; 視像=>zh-my:视频; 視像=>zh-sg:视频;'),
Item('digital video', '视像=>zh-tw:視訊; 视像=>zh-hk:視像; 视像=>zh-cn:视频; 视像=>zh-my:视频; 视像=>zh-sg:视频;'),
Item('digital video', '視頻=>zh-tw:影片; 視頻=>zh-hk:影片; 視頻=>zh-mo:影片;'),
Item('digital video', '視訊=>zh-hk:視像; 視訊=>zh-mo:視像; 視訊=>zh-cn:视频; 視訊=>zh-my:视频; 視訊=>zh-sg:视频;'),
Item('digital video', '视讯=>zh-mo:視像; 视讯=>zh-hk:視像; 视讯=>zh-cn:视频; 视讯=>zh-my:视频; 视讯=>zh-sg:视频;'),
Item('digital video', 'zh-cn:监控; zh-tw:監視; zh-hk:監視;'),
Item('digital watermarking', ' zh-cn:数字水印; zh-tw:數位浮水印; zh-hk:數碼水印;'),
Item('disk', 'zh-cn:磁盘; zh-tw:磁碟;'),
Item('display device', '显示屏=>zh-tw:顯示器; 显示屏=>zh-hk:顯示器; 显示屏=>zh-mo:顯示器;'),
Item('distributed', 'zh-cn:分布式; zh-tw:分散式;'),
Item('document', '文档=>zh-tw:文件; 文档=>zh-hk:文件; 文档=>zh-mo:文件;'),
Item('document', '文檔=>zh-tw:文件; 文檔=>zh-hk:文件; 文檔=>zh-mo:文件;'),
Item('document file', 'zh-cn:文档文件; zh-tw:文件檔案;'),
Item('document file', '文件檔=>zh-cn:文档文件; 文件檔=>zh-sg:文档文件; 文件檔=>zh-my:文档文件;'),
Item('document-oriented', 'zh-cn:面向文档; zh-tw:文件導向;'),
Item('document object model (DOM)', 'zh-cn:文档对象模型; zh-tw:文件物件模型;'),
Item('do Not Track', 'zh-cn:请勿追踪; zh-tw:停止追蹤;'),
Item('domain-key normal form', 'zh-cn:DK范式; zh-tw:DK規格化;'),
Item('drive', 'zh-cn:磁盘驱动器; zh-tw:磁碟機;'),
Item('drive - A drive', 'zh-cn:A盘; zh-tw:本機磁碟(A); zh-hk:A磁碟機;'),
Item('drive - B drive', 'zh-cn:B盘; zh-tw:本機磁碟(B); zh-hk:B磁碟機;'),
Item('drive - C drive', 'zh-cn:C盘; zh-tw:本機磁碟(C); zh-hk:C磁碟機;'),
Item('drive - D drive', 'zh-cn:D盘; zh-tw:本機磁碟(D); zh-hk:D磁碟機;'),
Item('drive - E drive', 'zh-cn:E盘; zh-tw:本機磁碟(E); zh-hk:E磁碟機;'),
Item('drive - F drive', 'zh-cn:F盘; zh-tw:本機磁碟(F); zh-hk:F磁碟機;'),
Item('drive - G drive', 'zh-cn:G盘; zh-tw:本機磁碟(G); zh-hk:G磁碟機;'),
Item('drive - H drive', 'zh-cn:H盘; zh-tw:本機磁碟(H); zh-hk:H磁碟機;'),
Item('drive - I drive', 'zh-cn:I盘; zh-tw:本機磁碟(I); zh-hk:I磁碟機;'),
Item('drive - J drive', 'zh-cn:J盘; zh-tw:本機磁碟(J); zh-hk:J磁碟機;'),
Item('drive - K drive', 'zh-cn:K盘; zh-tw:本機磁碟(K); zh-hk:K磁碟機;'),
Item('drive - L drive', 'zh-cn:L盘; zh-tw:本機磁碟(L); zh-hk:L磁碟機;'),
Item('drive - M drive', 'zh-cn:M盘; zh-tw:本機磁碟(M); zh-hk:M磁碟機;'),
Item('drive - N drive', 'zh-cn:N盘; zh-tw:本機磁碟(N); zh-hk:N磁碟機;'),
Item('drive - O drive', 'zh-cn:O盘; zh-tw:本機磁碟(O); zh-hk:O磁碟機;'),
Item('drive - P drive', 'zh-cn:P盘; zh-tw:本機磁碟(P); zh-hk:P磁碟機;'),
Item('drive - Q drive', 'zh-cn:Q盘; zh-tw:本機磁碟(Q); zh-hk:Q磁碟機;'),
Item('drive - R drive', 'zh-cn:R盘; zh-tw:本機磁碟(R); zh-hk:R磁碟機;'),
Item('drive - S drive', 'zh-cn:S盘; zh-tw:本機磁碟(S); zh-hk:S磁碟機;'),
Item('drive - T drive', 'zh-cn:T盘; zh-tw:本機磁碟(T); zh-hk:T磁碟機;'),
Item('drive - U drive', 'U磁碟機=>zh-cn:U盘; U磁碟機=>zh-sg:U盘; U磁碟機=>zh-my:U盘; U磁碟機=>zh-tw:USB磁碟機;'),
-- U盘與USB flash drive有衝突
Item('drive - U drive', 'U槽=>zh-cn:U盘; U槽=>zh-sg:U盘; U槽=>zh-my:U盘; U槽=>zh-tw:USB磁碟機; U槽=>zh-hk:U磁碟機; U槽=>zh-mo:U磁碟機;'),
Item('drive - V drive', 'zh-cn:V盘; zh-tw:本機磁碟(V); zh-hk:V磁碟機;'),
Item('drive - W drive', 'zh-cn:W盘; zh-tw:本機磁碟(W); zh-hk:W磁碟機;'),
Item('drive - X drive', 'zh-cn:X盘; zh-tw:本機磁碟(X); zh-hk:X磁碟機;'),
Item('drive - Y drive', 'zh-cn:Y盘; zh-tw:本機磁碟(Y); zh-hk:Y磁碟機;'),
Item('drive - Z drive', 'zh-cn:Z盘; zh-tw:本機磁碟(Z); zh-hk:Z磁碟機;'),
Item('drive - system drive', 'zh-cn:系统盘; zh-tw:系統磁碟; zh-hk:系統磁碟機;'),
Item('drive letter', 'zh-cn:盘符; zh-tw:磁碟機代號;'),
Item('driver', 'zh-cn:驱动程序; zh-tw:驅動程式;'),
Item('drop-down menu', 'zh-cn:下拉菜单; zh-tw:下拉式選單;'),
Item('Dual-link', 'zh-cn:双通道; zh-tw:雙連結;'),
Item('duck typing', 'zh-cn:鸭子类型; zh-tw:鴨子型別;'),
Item('dynamic binding', 'zh-cn:动态绑定; zh-tw:動態繫結;'),
Item('dynamic typing', 'zh-cn:动态类型; zh-tw:動態型別;'),
Item('digital media', 'zh-cn:数字媒体; zh-tw:數位媒體; zh-hk:數碼媒體;'),
{ type = 'text', text = [[

== E ==
]] },
Item('edit bar', 'zh-cn:编辑栏; zh-tw:編輯列;'),
Item('email', '电子邮件=>zh-sg:电邮; 电子邮件=>zh-my:电邮;'),
Item('email', '電子郵件=>zh-sg:电邮; 電子郵件=>zh-my:电邮;'),
Item('email', '电邮=>zh-tw:電子郵件;'),
Item('email', '電郵=>zh-tw:電子郵件;'),
Item('email', '电子信件=>zh-cn:电子邮件; 电子信件=>zh-sg:电邮; 电子信件=>zh-my:电邮; 电子信件=>zh-tw:電子郵件;'),
Item('email', '電子信件=>zh-cn:电子邮件; 電子信件=>zh-sg:电邮; 電子信件=>zh-my:电邮; 電子信件=>zh-tw:電子郵件;'),
Item('email (mailbox)', 'zh-cn:邮箱; zh-tw:電子信箱; zh-hk:郵箱;'),
Item('email (mailbox)', '电子邮箱=>zh-tw:電子信箱;'),
Item('email (mailbox)', '電子郵箱=>zh-tw:電子信箱;'),
Item('enclosed', '带圈=>zh-tw:圍繞; 带圈=>zh-hk:圍繞; 带圈=>zh-mo:圍繞;'),
Item('enclosed', '帶圈=>zh-tw:圍繞; 帶圈=>zh-hk:圍繞; 帶圈=>zh-mo:圍繞;'),
Item('enclosed character', 'zh-cn:带圈字符; zh-tw:圍繞字元;'),
Item('end user', 'zh-cn:最终用户; zh-tw:終端使用者;'),
Item('end-user license agreements', 'zh-cn:最终用户许可协议; zh-tw:終端使用者授權協定;'),
Item('enter', '回车=>zh-tw:Enter; 回车=>zh-hk:Enter; 回车=>zh-mo:Enter;'),
Item('enter key', 'zh-cn:回车键; zh-tw:確認鍵;'),
Item('enter key', '确认键=>zh-cn:回车键; 确认键=>zh-sg:回车键; 确认键=>zh-my:回车键;'),
Item('enter key', '回車鍵=>zh-tw:確認鍵; 回車鍵=>zh-hk:確認鍵; 回車鍵=>zh-mo:確認鍵;'),
Item('enumeration', 'zh-cn:枚举; zh-tw:列舉;'),
Item('enumerators', 'zh-cn:枚举器; zh-tw:列舉元;'),
Item('enumerators', 'zh-cn:枚举成员; zh-tw:列舉元;'),
Item('escape', 'zh-cn:转义; zh-tw:跳脫;'),
Item('Ethernet', 'zh-cn:以太网; zh-tw:乙太網路;'),
Item('Ethernet', '以太网络 => zh-tw:乙太網路;'),
Item('EULA', 'zh-cn:最终用户许可协议; zh-tw:終端使用者授權合約;'),
Item('Exabyte', 'zh-hans:艾字节; zh-hant:艾位元組;'),
Item('exception handling', 'zh-cn:异常处理; zh-tw:例外處理;'),
Item('exclusive or', 'zh-cn:异或; zh-tw:互斥或; zh-hk:異或;'),
Item('executable file', '可执行文件=>zh-tw:可執行檔;'),
Item('executable file', '執行檔=>zh-cn:可执行文件; 執行檔=>zh-sg:可执行文件; 執行檔=>zh-my:可执行文件;'),
-- Item('exit/quit', 'zh-cn:退出; zh-tw:結束;'), 容易過度轉換
Item('exit/quit application', 'zh-cn:退出程序; zh-tw:結束程式;'),
Item('exit/quit application', 'zh-cn:退出应用程序; zh-tw:結束應用程式; zh-hk:結束應用程序;'),
Item('expand', 'zh-cn:扩展; zh-tw:擴充;'),
Item('export', 'zh-cn:导出; zh-tw:匯出;'),
Item('expression', '運算式=>zh-cn:表达式; 運算式=>zh-sg:表达式; 運算式=>zh-my:表达式;'),
Item('extended block', '扩充区=>zh-cn:扩展区; 扩充区=>zh-sg:扩展区; 扩充区=>zh-my:扩展区;'),
Item('extended block', '擴展區=>zh-tw:擴充區; 擴展區=>zh-hk:擴充區; 擴展區=>zh-mo:擴充區;'),
Item('extended Chinese character', '扩充汉字=>zh-cn:扩展汉字; 扩充汉字=>zh-sg:扩展汉字; 扩充汉字=>zh-my:扩展汉字;'),
Item('extended Chinese character', '擴展漢字=>zh-tw:擴充漢字; 擴展漢字=>zh-hk:擴充漢字; 擴展漢字=>zh-mo:擴充漢字;'),
Item('extended reality', 'zh-cn:扩展现实; zh-tw:延展實境;'),
Item('extensible', 'zh-cn:可扩展; zh-tw:可延伸;'),
Item('extensible business reporting language', 'zh-cn:可扩展商业报告语言; zh-tw:可延伸商用報告語言;'),
Item('extensible firmware interface', 'zh-cn:可扩展固件接口; zh-tw:可延伸韌體介面;'),
Item('extensible markup language', 'zh-cn:可扩展置标语言; zh-tw:可延伸標示語言;'),
Item('extension name', 'zh-cn:扩展名; zh-tw:副檔名;'),
Item('extension', '擴充套件=>zh-cn:扩展; 擴充套件=>zh-sg:扩展; 擴充套件=>zh-my:扩展;'),
Item('extension', '擴充功能=>zh-cn:扩展; 擴充功能=>zh-sg:扩展; 擴充功能=>zh-my:扩展;'),
Item('extension A', '扩充A区=>zh-cn:扩展A区; 扩充A区=>zh-sg:扩展A区; 扩充A区=>zh-my:扩展A区;'),
Item('extension A', '擴展A區=>zh-tw:擴充A區; 擴展A區=>zh-hk:擴充A區; 擴展A區=>zh-mo:擴充A區;'),
Item('extension B', '扩充B区=>zh-cn:扩展B区; 扩充B区=>zh-sg:扩展B区; 扩充B区=>zh-my:扩展B区;'),
Item('extension B', '擴展B區=>zh-tw:擴充B區; 擴展B區=>zh-hk:擴充B區; 擴展B區=>zh-mo:擴充B區;'),
Item('extension C', '扩充C区=>zh-cn:扩展C区; 扩充C区=>zh-sg:扩展C区; 扩充C区=>zh-my:扩展C区;'),
Item('extension C', '擴展C區=>zh-tw:擴充C區; 擴展C區=>zh-hk:擴充C區; 擴展C區=>zh-mo:擴充C區;'),
Item('extension D', '扩充D区=>zh-cn:扩展D区; 扩充D区=>zh-sg:扩展D区; 扩充D区=>zh-my:扩展D区;'),
Item('extension D', '擴展D區=>zh-tw:擴充D區; 擴展D區=>zh-hk:擴充D區; 擴展D區=>zh-mo:擴充D區;'),
Item('extension E', '扩充E区=>zh-cn:扩展E区; 扩充E区=>zh-sg:扩展E区; 扩充E区=>zh-my:扩展E区;'),
Item('extension E', '擴展E區=>zh-tw:擴充E區; 擴展E區=>zh-hk:擴充E區; 擴展E區=>zh-mo:擴充E區;'),
Item('extension F', '扩充F区=>zh-cn:扩展F区; 扩充F区=>zh-sg:扩展F区; 扩充F区=>zh-my:扩展F区;'),
Item('extension F', '擴展F區=>zh-tw:擴充F區; 擴展F區=>zh-hk:擴充F區; 擴展F區=>zh-mo:擴充F區;'),
Item('extension G', '扩充G区=>zh-cn:扩展G区; 扩充G区=>zh-sg:扩展G区; 扩充G区=>zh-my:扩展G区;'),
Item('extension G', '擴展G區=>zh-tw:擴充G區; 擴展G區=>zh-hk:擴充G區; 擴展G區=>zh-mo:擴充G區;'),
Item('external hard drive', 'zh-cn:外置硬盘; zh-tw:外接硬碟;'),
Item('external link', '外链=>zh-tw:外部連結; 外链=>zh-hk:外部連結; 外链=>zh-mo:外部連結;'),
Item('external link', '外鏈=>zh-tw:外部連結; 外鏈=>zh-hk:外部連結; 外鏈=>zh-mo:外部連結;'),
Item('enterprise mobility management', 'zh-cn:企业移动管理; zh-tw:企業行動管理;'),
{ type = 'text', text = [[

== F ==
]] },
Item('Facebook', 'zh-cn:脸谱; zh-sg:面簿; zh-my:脸书; zh-tw:臉書;'),
Item('Facebook', '脸谱=>zh-hk:Facebook; 臉譜=>zh-hk:Facebook; 面簿=>zh-hk:Facebook; 脸书=>zh-hk:Facebook; 臉書=>zh-hk:Facebook; 面书=>zh-hk:Facebook; 面書=>zh-hk:Facebook; 脸谱=>zh-mo:Facebook; 臉譜=>zh-mo:Facebook; 面簿=>zh-mo:Facebook; 脸书=>zh-mo:Facebook; 臉書=>zh-mo:Facebook; 面书=>zh-mo:Facebook; 面書=>zh-mo:Facebook;'),
Item('facial recognition', 'zh-cn:人脸识别; zh-tw:臉部辨識; zh-hk:人面辨識;'),
Item('facial recognition', '人臉辨識=>zh-tw:臉部辨識;人臉辨識=>zh-hk:人面辨識;人臉辨識=>zh-mo:人面辨識;'),
Item('fairchild semiconductor', 'zh-cn:飞兆半导体; zh-tw:快捷半導體;'),
Item('feature phone', 'zh-cn:功能手机; zh-tw:功能型手機; zh-hk:功能電話;'),
Item('feedback', 'zh-cn:反馈; zh-tw:回饋; zh-hk:反饋;'),
Item('fiber distributed data interface', 'zh-cn:光纤分布式数据接口; zh-tw:光纖分散式資料介面; zh-hk:光纖分散式數據介面;'),
Item('field', 'zh-cn:字段; zh-tw:欄位;'),
Item('fifth normal form', 'zh-cn:第五范式; zh-tw:第五規格化;'),
Item('file', 'zh-cn:文件; zh-tw:檔案;'),
Item('file', '档案=>zh-cn:文件; 档案=>zh-sg:文件; 档案=>zh-my:文件;'),
Item('dile descriptor', 'zh-cn:文件描述符; zh-hant:檔案描述子;'),
Item('File namespace', 'zh-cn:文件名字空间; zh-tw:檔案命名空間;'),
Item('filename', 'zh-cn:文件名; zh-tw:檔名;'),
Item('filename', 'zh-cn:文件名称; zh-tw:檔案名稱;'),
Item('filename', '文件名稱=>zh-tw:檔案名稱; 文件名稱=>zh-hk:檔案名稱; 文件名稱=>zh-mo:檔案名稱;'),
Item('filename', 'zh-cn:文件名字; zh-tw:檔案名字;'),
Item('filename extension', 'zh-cn:文件扩展名; zh-tw:副檔名;'),
Item('filename extension', 'zh-cn:扩展名; zh-tw:副檔名;'),
Item('film streaming', 'zh-cn:影片流; zh-tw:影片串流;'),
Item('find', 'zh-cn:查找; zh-tw:尋找;'),
Item('firmware', 'zh-cn:固件; zh-tw:韌體;'),
Item('first normal form', 'zh-cn:第一范式; zh-tw:第一規格化;'),
Item('flash memory', 'zh-cn:闪存; zh-tw:快閃記憶體;'),
Item('flight mode', 'zh-cn:飞行模式; zh-tw:飛航模式;'),
Item('floppy disk', 'zh-cn:软盘; zh-tw:軟碟;'),
Item('floppy disk drive', 'zh-cn:软盘驱动器; zh-tw:軟碟機;'),
Item('folder', 'zh-cn:文件夹; zh-tw:資料夾;'),
Item('font', 'zh-cn:字体; zh-tw:字型;'),
Item('footer', 'zh-cn:页脚; zh-tw:頁尾;'),
Item('footnote', 'zh-cn:脚注; zh-tw:註腳;'),
Item('footnote', 'zh-cn:尾注; zh-tw:章節附註;'),
Item('foreign key', 'zh-cn:外键; zh-tw:外來鍵;'),
Item('form', 'zh-cn:窗体; zh-tw:表單;'),
Item('forward chaining', 'zh-cn:前向链接; zh-tw:正向鏈結;'),
Item('forward error correction', 'zh-cn:前向纠错; zh-tw:正向錯誤校正;'),
Item('fourth normal form', 'zh-cn:第四范式; zh-tw:第四規格化;'),
Item('frame', 'zh-cn:帧; zh-tw:影格; zh-hk:幀;'),
Item('frame', '片格=>zh-cn:帧; 片格=>zh-sg:帧; 片格=>zh-my:帧; 片格=>zh-hk:幀; 片格=>zh-mo:幀;'),
Item('frame', '讯框=>zh-cn:帧; 讯框=>zh-sg:帧; 讯框=>zh-my:帧; 讯框=>zh-hk:幀; 讯框=>zh-mo:幀;'),
Item('frame', '訊框=>zh-cn:帧; 訊框=>zh-sg:帧; 訊框=>zh-my:帧; 訊框=>zh-hk:幀; 訊框=>zh-mo:幀;'),
Item('frame rate', 'zh-cn:帧率; zh-tw:影格率; zh-hk:幀率;'),
Item('frame rate', '影格速率=>zh-cn:帧率; 影格速率=>zh-sg:帧率; 影格速率=>zh-my:帧率; 影格速率=>zh-hk:幀率; 影格速率=>zh-mo:幀率;'),
Item('frame pointer', 'zh-cn:帧指针; zh-tw:影格指標; zh-hk:框指標;'),
Item('frame synchronization', 'zh-cn:帧同步; zh-tw:影格同步化; zh-hk:框同步化;'),
Item('forum', 'zh-cn:论坛; zh-tw:論壇; zh-hk:討論區;'),
Item('full screen', 'zh-cn:全屏; zh-tw:全螢幕; zh-hk:全屏幕;'),
Item('full screen', '全面屏=>zh-tw:全螢幕;全面屏=>zh-hk:全屏幕;全面屏=>zh-mo:全屏幕;'),
Item('full-size smartphone', 'zh-cn:全面屏手机;zh-tw:全螢幕手機;zh-hk:全屏幕手機;'),
Item('fullwidth', 'zh-cn:全角; zh-tw:全形;'),
Item('function', 'zh-cn:函数; zh-tw:函式; zh-hk:函數;'),
Item('functional programming', 'zh-cn:函数式编程; zh-tw:函式語言程式設計;'),
Item('functional programming language', 'zh-cn:函数编程语言; zh-tw:函式程式語言;'),
Item('functional programming language', '函數程式語言=>zh-cn:函数编程语言; 函數程式語言=>zh-sg:函数编程语言; 函數程式語言=>zh-my:函数编程语言;'),
Item('full high definition (full HD)', '全高清=>zh-tw:超高畫質;'),
{ type = 'text', text = [[

== G ==
]] },
-- 参考文献：刘青，温昌斌，海峡两岸科技名词差异问题分析与试解，中国科技术语，(3), 2008, 65-69
Item('garbage', '无用信息=>zh-tw:多餘的資料; 无用信息=>zh-hk:多餘的資料; 无用信息=>zh-mo:多餘的資料;'),
Item('gateway', 'zh-cn:网关; zh-tw:閘道器;'),
Item('gateway', '閘道=>zh-cn:网关; 閘道=>zh-sg:网关; 閘道=>zh-my:网关;'),
Item('Gateway, Inc.', 'zh-cn:捷威; zh-tw:桀威;'),
Item('get', 'zh-cn:获取; zh-tw:取得;'),
Item('gigabit ethernet', 'zh-cn:吉比特以太网; zh-tw:十億位元乙太網路;'),
Item('Gigabyte', '吉咖字节=>zh-hant:吉位元組; 京字节=>zh-hant:吉位元組; 吉字节=>zh-hant:吉位元組; '),
Item('Gigabyte', '吉位元組=>zh-hans:吉字节; 十億位元組=>zh-hans:吉字节;  '),
Item('global', 'zh-cn:全局; zh-tw:全域;'),
Item('Global System for Mobile Communications Association', 'zh-cn:全球移动通信系统协会; zh-tw:全球行動通訊系統協會; zh-hk:全球流動通訊系統協會;'),
Item('Google', '谷歌=>zh-sg:Google; 谷歌=>zh-my:Google; 谷歌=>zh-tw:Google; 谷歌=>zh-hk:Google; 谷歌=>zh-mo:Google;'),
Item('Google Cloud Messaging', 'zh-cn:Google云消息传递; zh-tw:Google雲端通訊;'),
Item('Google Cloud Messaging', 'Google云端推送=>zh-tw:Google雲端通訊; Google云端推送=>zh-hk:Google雲端通訊; Google云端推送=>zh-mo:Google雲端通訊;'),
Item('Google Chrome Frame', 'zh-cn:谷歌浏览器内嵌框架; zh-tw:Google Chrome內嵌瀏覽框;'),
Item('Google Docs', 'zh-cn:Google文档; zh-tw:Google文件;'),
Item('Google Docs', 'zh-cn:Google 文档; zh-tw:Google 文件;'),
Item('Google Toolbar', 'zh-cn:Google工具条; zh-tw:Google工具列;'),
Item('Google Toolbar', 'zh-cn:Google 工具条; zh-tw:Google 工具列;'),
Item('Google Video', 'zh-cn:Google视频; zh-tw:Google影片;'),
Item('Google Video', 'zh-cn:Google 视频; zh-tw:Google 影片;'),
Item('graphics', 'zh-cn:图形学; zh-tw:圖學;'),
Item('graphics', '图学=>zh-cn:图形学; 图学=>zh-sg:图形学; 图学=>zh-my:图形学;'),
Item('graphics', '圖形學=>zh-tw:圖學; 圖形學=>zh-hk:圖學; 圖形學=>zh-mo:圖學;'),
Item('graphics processing unit', 'zh-cn:图形处理器; zh-tw:圖形處理器'),
Item('graphing calculator', 'zh-cn:图形计算器; zh-tw:繪圖計算機;'),
Item('greedy algorithm', 'zh-cn:贪心算法; zh-tw:貪婪演算法;'),
Item('greedy algorithm', '贪婪算法=>zh-cn:贪心算法; 贪婪算法=>zh-sg:贪心算法; 贪婪算法=>zh-my:贪心算法;'),
Item('greedy algorithm', '貪心算法=>zh-tw:貪婪演算法; 貪心算法=>zh-hk:貪婪演算法; 貪心算法=>zh-mo:貪婪演算法;'),
Item('greedy algorithm', '貪心演算法=>zh-tw:貪婪演算法; 貪心演算法=>zh-hk:貪婪演算法; 貪心演算法=>zh-mo:貪婪演算法;'),
Item('greedy algorithm', 'zh-cn:贪心法; zh-tw:貪婪法;'),
Item('greedy algorithm', '貪心法=>zh-tw:貪婪法; 貪心法=>zh-hk:貪婪法; 貪心法=>zh-mo:貪婪法;'),
Item('gridlines', 'zh-cn:网格线; zh-tw:格線;'),
Item('group', 'zh-cn:组群; zh-tw:群組;'),
Item('group notice', 'zh-cn:组提示; zh-tw:群組提示;'),
Item('GSM mobile', 'zh-cn:GSM移动; zh-tw:GSM行動; zh-hk:GSM流動;'),
Item('GUI', 'zh-cn:图形用户界面; zh-tw:圖形化使用者介面;'),
Item('GUID Partition Table', 'zh-cn:全局唯一标识分区表; zh-tw:GUID磁碟分割表;'),
{ type = 'text', text = [[

== H ==
]] },
Item('hacker', 'zh-cn:黑客; zh-tw:駭客; zh-hk:黑客;'),
Item('halfwidth', 'zh-cn:半角; zh-tw:半形;'),
Item('handler', 'zh-cn:处理函数; zh-tw:處理常式;'),
Item('handle', 'zh-cn:句柄; zh-tw:控制代碼;'),
Item('hard disk', 'zh-cn:硬盘; zh-tw:硬碟;'),
Item('hard disk', '硬盤 => zh-tw:硬碟;'),
Item('hard disk drive (HDD)', 'zh-cn:硬盘驱动器; zh-tw:硬碟機;'),
Item('hard-coded', 'zh-cn:硬编码; zh-tw:寫死;'),
Item('hardware', 'zh-cn:硬件; zh-tw:硬體; zh-hk:硬件;'),
Item('hash', '哈希=>zh-tw:雜湊; 哈希=>zh-hk:雜湊; 哈希=>zh-mo:雜湊;'),
Item('hash', 'zh-cn:散列; zh-tw:雜湊;'),
Item('HDMI', 'zh-cn:高清多媒体界面; zh-tw:高畫質多媒體介面; zh-hk:高清多媒體介面;'),
Item('head crash', 'zh-cn:磁头划碰; zh-tw:磁頭損壞;'),
Item('header', 'zh-cn:标头; zh-tw:檔頭;'),
Item('header', 'zh-cn:页眉; zh-tw:頁首;'),
Item('header file', 'zh-cn:头文件; zh-tw:標頭檔;'),
Item('header file', '標頭檔案=>zh-cn:头文件; 標頭檔案=>zh-sg:头文件; 標頭檔案=>zh-my:头文件;'),
Item('header file', '表頭檔=>zh-cn:头文件; 表頭檔=>zh-sg:头文件; 表頭檔=>zh-my:头文件;'),
Item('header file', '表頭檔案=>zh-cn:头文件; 表頭檔案=>zh-sg:头文件; 表頭檔案=>zh-my:头文件;'),
Item('heapsort', 'zh-cn:堆排序; zh-tw:堆積排序;'),
Item('hearts', 'zh-cn:红心大战; zh-tw:傷心小棧;'),
Item('Help and Support', 'zh-cn:帮助与支持; zh-tw:說明與支援;'),
Item('help document', 'zh-cn:帮助文档; zh-tw:說明文件;'),
Item('Hierarchical View', 'zh-cn:分层视图; zh-tw:多層次樹狀介面;'),
Item('Hierarchical View', 'zh-cn:分层树形视图; zh-tw:多層次樹狀介面;'),
Item('hierarchy', 'zh-cn:层次结构; zh-tw:階層;'),
Item('high definition (HD)', 'zh-cn:高清; zh-tw:高畫質; zh-hk:高清;'),
Item('high definition (HD)', 'zh-cn:高清晰; zh-tw:高解析; zh-hk:高清晰;'),
Item('high fidelity (Hi-Fi)', '高保真=>zh-hk:高傳真; 高保真=>zh-mo:高傳真;'),
Item('high fidelity (Hi-Fi)', '高傳真=>zh-cn:高保真; 高傳真=>zh-sg:高保真; 高傳真=>zh-my:高保真;'),
Item('high-resolution audio', 'zh-cn:高清音频; zh-tw:高音質音訊; zh-hk:高清音頻;'),
Item('high-resolution sound quality', 'zh-cn:高清音质; zh-tw:高音質; zh-hk:高清音質;'),
Item('high-level language', 'zh-cn:高级语言; zh-tw:高階語言;'),
Item('high-level language', '高阶语言=>zh-cn:高级语言; 高阶语言=>zh-sg:高级语言; 高阶语言=>zh-my:高级语言;'),
Item('high-level language', '高级語言=>zh-tw:高階語言; 高级語言=>zh-hk:高階語言; 高级語言=>zh-mo:高階語言;'),
Item('high-level language', '高級語言=>zh-tw:高階語言; 高級語言=>zh-hk:高階語言; 高級語言=>zh-mo:高階語言;'),
Item('high-level programming language', 'zh-cn:高级编程语言; zh-tw:高階程式語言;'),
Item('high-level programming language', '高级编程語言=>zh-tw:高階程式語言; 高级编程語言=>zh-hk:高階程式語言; 高级编程語言=>zh-mo:高階程式語言;'),
Item('high-level programming language', '高级编程語言=>zh-tw:高階程式語言; 高级编程語言=>zh-hk:高階程式語言; 高级编程語言=>zh-mo:高階程式語言;'),
Item('high-level/high-end/highend', 'zh-cn:高端; zh-tw:高階;'),
Item('high-level/high-end/highend', '高檔=>zh-cn:高端; 高檔=>zh-sg:高端; 高檔=>zh-my:高端; 高檔=>zh-hk:高階; 高檔=>zh-mo:高階;'),
Item('highlight', '高亮=>zh-tw:突顯; 高亮=>zh-hk:突顯; 高亮=>zh-mo:突顯;'),
Item('highlight', '高亮显示=>zh-tw:突出顯示; 高亮显示=>zh-hk:突出顯示; 高亮显示=>zh-mo:突出顯示;'),
Item('highlight', '高亮顯示=>zh-tw:突出顯示; 高亮顯示=>zh-hk:突出顯示; 高亮顯示=>zh-mo:突出顯示;'),
Item('holographic', 'zh-cn:全息; zh-tw:全像;'),
Item('home', '住家=>zh-cn:家庭; 住家=>zh-sg:家庭; 住家=>zh-my:家庭;'),
Item('home address', '住家地址=>zh-cn:家庭地址; 住家地址=>zh-sg:家庭地址; 住家地址=>zh-my:家庭地址;'),
Item(nil, 'zh-cn:主页; zh-tw:首頁;'),
Item('hosting', 'zh-cn:托管; zh-tw:代管; zh-hk:寄存;'),
Item('hosting', '託管=>zh-tw:代管; 託管=>zh-hk:寄存; 託管=>zh-mo:寄存;'),
Item('hook', 'zh-cn:钩子; zh-tw:勾點;'),
Item('HyperText Markup Language', 'zh-cn:超文本标记语言; zh-tw:超文件標示語言;'),
Item('HyperText Markup Language', 'zh-cn:超文本置标语言; zh-tw:超文件標示語言;'),
{ type = 'text', text = [[

== I ==
]] },
Item('icon', 'zh-cn:图标; zh-tw:圖示;'),
Item('Integrated Development Environment (IDE)', 'zh-cn:集成开发环境; zh-tw:整合式開發環境;'),
Item('Integrated Device Electronics (IDE)', 'zh-cn:集成设备电路; zh-tw:整合裝置電路;'),
Item('ID', 'zh-cn:身份; zh-tw:身分; zh-hk:身份;'),
Item('identifier', 'zh-cn:标识符; zh-tw:識別碼;'),
Item('if and only if', 'zh-cn:当且仅当; zh-tw:若且唯若;'),
-- 有可能過度轉換，編輯時須注意
Item('image', '映象=>zh-cn:镜像; 映象=>zh-sg:镜像; 映象=>zh-my:镜像;'),
Item('image file', 'zh-cn:图像文件; zh-tw:圖檔;'),
Item('image macro', 'zh-cn:表情包; zh-tw:哏圖;'),
Item('image macro', '表情图=>zh-cn:表情包; 表情圖=>zh-cn:表情包; 表情图=>zh-tw:哏圖; 表情圖=>zh-tw:哏圖;'),
Item('imperative programming', 'zh-cn:命令式编程; zh-tw:指令式程式設計;'),
Item('implement', '實作=>zh-cn:实现; 實作=>zh-sg:实现; 實作=>zh-my:实现;'),
Item('import', 'zh-cn:导入; zh-tw:匯入;'),
Item('import', '汇入=>zh-cn:导入; 汇入=>zh-sg:导入; 汇入=>zh-my:导入;'),
Item('import', '導入=>zh-tw:匯入; 導入=>zh-hk:匯入; 導入=>zh-mo:匯入;'),
Item('Incognito mode', 'zh-cn:隐身模式; zh-tw:無痕模式;'),
Item('indent', 'zh-cn:缩进; zh-tw:縮排;'),
Item('info (information)', 'zh-cn:信息; zh-tw:資訊;'),
Item('information age', 'zh-cn:信息时代; zh-tw:資訊時代; zh-hk:資訊年代;'),
Item('Information and Communication Technology', 'zh-cn:信息及通信技术; zh-tw:資訊及通訊科技;'),
Item('Information Engagement', 'zh-cn:信息接触; zh-tw:資訊參與;'),
Item('Information industry', 'zh-cn:信息产业; zh-tw:資訊工業;'),
Item('Information Management', 'zh-cn:信息管理; zh-tw:資訊管理;'),
Item('Information overload', 'zh-cn:信息过载; zh-tw:資訊超載;'),
Item('Information Science', 'zh-cn:信息学; zh-tw:資訊學; zh-hk:資訊科學;'),
Item('information security', 'zh-cn:信息安全; zh-tw:資訊安全;'),
Item('information security', '資安=>zh-cn:信息安全; 資安=>zh-sg:信息安全; 資安=>zh-my:信息安全;'),
Item('Information Technology', 'zh-cn:信息技术; zh-tw:資訊科技;'),
Item('injection', '隱碼=>zh-cn:注入; 隱碼=>zh-sg:注入; 隱碼=>zh-my:注入;'),
Item('injection', '資料隱碼=>zh-cn:注入; 資料隱碼=>zh-sg:注入; 資料隱碼=>zh-my:注入;'),
Item('inline', 'zh-cn:内联; zh-tw:行內;'),
Item('Intranet', 'zh-cn:内联网; zh-tw:內部網路;'),
Item('installation package', 'zh-cn:安装包; zh-tw:安裝套件;'),
Item('instance method', '實體方法=>zh-cn:实例方法; 實體方法=>zh-sg:实例方法; 實體方法=>zh-my:实例方法;'),
Item('integrate', 'zh-cn:集成; zh-tw:整合;'),
Item('integrated circuit', 'zh-cn:集成电路; zh-tw:積體電路; zh-hk:集成電路;'),
Item('intellectual property', 'zh-cn:知识产权; zh-tw:智慧財產權; zh-hk:知識產權;'),
Item('intellectualize', 'zh-cn:智能化; zh-tw:智慧化; zh-hk:智能化;'),
Item('intelligence', '智能型=>zh-sg:智慧型; 智能型=>zh-my:智慧型; 智能型=>zh-tw:智慧型;'),
Item('interacts', 'zh-cn:交互; zh-tw:互動;'),
Item('interactive entertainment', '互動娛樂=>zh-cn:互动娱乐; 互動娛樂=>zh-sg:互动娱乐; 互動娛樂=>zh-my:互动娱乐;'),
Item('interface', 'zh-cn:接口; zh-tw:介面;'),
Item('interface (frontstage)', '界面=>zh-tw:介面; 界面=>zh-hk:介面; 界面=>zh-mo:介面;'),
Item('internal link', '内链=>zh-tw:內部連結; 内链=>zh-hk:內部連結; 内链=>zh-mo:內部連結;'),
Item('internal link', '內鏈=>zh-tw:內部連結; 內鏈=>zh-hk:內部連結; 內鏈=>zh-mo:內部連結;'),
Item('Internet', 'zh-cn:互联网; zh-tw:網際網路; zh-hk:互聯網;'),
Item('Internet', '英特网=>zh-tw:網際網路; 英特网=>zh-hk:互聯網; 英特网=>zh-mo:互聯網;'),
Item('Internet', '因特网=>zh-tw:網際網路; 因特网=>zh-hk:互聯網; 因特网=>zh-mo:互聯網;'),
Item('Internet', '互联网=>zh-tw:網際網路; 互联网=>zh-hk:互聯網; 互联网=>zh-mo:互聯網;'),
Item('Internet', '国际互联网=>zh-tw:網際網路; 国际互联网=>zh-hk:互聯網; 国际互联网=>zh-mo:互聯網;'),
Item('Internet bar', 'zh-cn:网吧; zh-tw:網咖; zh-hk:網吧;'),
Item('Internet culture', '网络文化=>zh-tw:網路文化;'),
Item('Internet forum', '網上論壇 => zh-tw:網路論壇;'),
Item('Internet forum', '網上討論區 => zh-tw:網路論壇;'),
Item('Internet Content Provider (ICP)', 'zh-cn:互联网内容提供商; zh-tw:線上內容提供者; zh-hk:互聯網內容供應商;'),
Item('Internet Service Provider (ISP)', 'zh-cn:互联网服务提供商; zh-tw:網際網路服務提供者; zh-hk:互聯網服務供應商;'),
Item('interpreter', 'zh-cn:解释器; zh-tw:直譯器;'),
Item('Interpreted language', 'zh-cn:解释型语言; zh-tw:直譯語言;'),
Item('Intranet', 'zh-cn:内部网络; zh-tw:內部網路; zh-hk:內聯網;'),
Item('Intranet', 'zh-cn:内部网; zh-tw:內部網路; zh-hk:內聯網;'),
Item('Internet Key Exchange', 'zh-cn:因特网密钥交换; zh-tw:網際網路金鑰交換; zh-hk:互聯網金鑰交換;'),
Item('Inter-Process Communication', 'zh-cn:进程间通信; zh-tw:行程間通訊; zh-hk:行程間通訊;'),
Item('Inter-Process', 'zh-cn:进程间; zh-tw:行程間; zh-hk:行程間;'),
-- 與call的轉換有衝突
Item('invoke', '叫用=>zh-cn:调用; 叫用=>zh-sg:调用; 叫用=>zh-my:调用;'),
{ type = 'text', text = [[

== J ==
]] },
Item('Jelly Bean', 'zh-cn:果冻豆; zh-tw:雷根糖; zh-hk:啫喱豆;'), -- 常用于指代Android 4.1
Item('judge', 'zh-cn:评测系统; zh-tw:解題系統;'),
{ type = 'text', text = [[

== K ==
]] },
Item('kernel', '内核=>zh-tw:核心;'),
Item('kernel', '內核=>zh-tw:核心;'),
Item('key', 'zh-cn:密钥; zh-tw:金鑰;'),
Item('keyboard layout', 'zh-cn:键盘布局; zh-tw:鍵盤配置;'),
Item('keygen', 'zh-cn:注册机; zh-tw:序號產生器;'),
{ type = 'text', text = [[

== L ==
]] },
Item('landscape', 'zh-cn:横屏幕; zh-tw:橫螢幕; zh-hk:橫熒幕;'),
Item('landscape', '橫屏=>zh-tw:橫螢幕; 橫屏=>zh-hk:橫熒幕; 橫屏=>zh-mo:橫熒幕;'),
Item('Language-Oriented Programming', 'zh-cn:面向语言的程序设计; zh-tw:語言導向程式設計;'),
Item('language package', 'zh-cn:语言包; zh-tw:語言套件;'),
Item('laptop/notebook computer', 'zh-cn:笔记本电脑; zh-tw:筆記型電腦; zh-hk:手提電腦;'),
Item('laptop/notebook computer', '笔记型电脑=>zh-cn:笔记本电脑; 笔记型电脑=>zh-sg:笔记本电脑; 笔记型电脑=>zh-my:笔记本电脑; 笔记型电脑=>zh-hk:手提電腦; 笔记型电脑=>zh-mo:手提電腦;'),
Item('laptop/notebook computer', '手提电脑=>zh-cn:笔记本电脑; 手提电脑=>zh-sg:笔记本电脑; 手提电脑=>zh-my:笔记本电脑; 手提电脑=>zh-tw:筆記型電腦;'),
Item('laptop/notebook computer', '筆記本電腦=>zh-tw:筆記型電腦; 筆記本電腦=>zh-hk:手提電腦; 筆記本電腦=>zh-mo:手提電腦;'),
Item('laptop/notebook computer', '笔电=>zh-cn:笔记本电脑; 笔电=>zh-sg:笔记本电脑; 笔电=>zh-my:笔记本电脑; 笔电=>zh-hk:手提電腦; 笔电=>zh-mo:手提電腦;'),
Item('laptop/notebook computer', '筆電=>zh-cn:笔记本电脑; 筆電=>zh-sg:笔记本电脑; 筆電=>zh-my:笔记本电脑; 筆電=>zh-hk:手提電腦; 筆電=>zh-mo:手提電腦;'),
Item('laptop/notebook computer', '膝上型电脑=>zh-cn:笔记本电脑; 膝上型电脑=>zh-sg:笔记本电脑; 膝上型电脑=>zh-my:笔记本电脑; 膝上型电脑=>zh-tw:筆記型電腦;'),
Item('laptop/notebook computer', '膝上型電腦=>zh-cn:笔记本电脑; 膝上型電腦=>zh-sg:笔记本电脑; 膝上型電腦=>zh-my:笔记本电脑; 膝上型電腦=>zh-tw:筆記型電腦;'),
Item('laser', 'zh-cn:激光; zh-sg:镭射; zh-tw:雷射; zh-hk:激光;'),
Item('LaserDisc', 'zh-cn:激光视盘; zh-tw:雷射影碟; zh-hk:鐳射影碟;'),
Item('launch bar', 'zh-cn:启动栏; zh-tw:啟動列;'),
Item('library', '函式庫=>zh-cn:库; 函式庫=>zh-sg:库; 函式庫=>zh-my:库;'),
-- 「链接」有chaining或link的意思，而chaining和link都可被譯為「鏈結」
Item('link', 'zh-cn:链接; zh-tw:連結;'),
Item('link', '鏈結=>zh-cn:链接; 鏈結=>zh-sg:链接; 鏈結=>zh-my:链接;'),
Item('link', '连结=>zh-cn:链接; 连结=>zh-sg:链接; 连结=>zh-my:链接;'),
Item('link', '鏈接=>zh-tw:鏈結; 鏈接=>zh-hk:連結; 鏈接=>zh-mo:連結;'),
Item('linked list', 'zh-cn:链表; zh-tw:連結串列;'),
Item('linked list', '鏈表=>zh-tw:連結串列; 鏈表=>zh-hk:連結串列; 鏈表=>zh-mo:連結串列;'),
Item('livelock', 'zh-cn:活锁; zh-tw:活結;'),
Item('load', 'zh-cn:加载; zh-tw:載入;'),
Item('load', '载入=>zh-cn:加载; 载入=>zh-sg:加载; 载入=>zh-my:加载;'),
Item('load', '加載=>zh-tw:載入; 加載=>zh-hk:載入; 加載=>zh-mo:載入;'),
Item('Local Area Network', 'zh-cn:局域网; zh-tw:區域網路; zh-hk:區域網絡;'),
Item('localization', 'zh-cn:本地化; zh-tw:在地化; zh-hk:本地化;'),
Item('log', 'zh-cn:日志; zh-tw:紀錄檔;'),
Item('log in', 'zh-hans:登录;zh-hant:登入;'),
Item('log out', 'zh-hant:登出;zh-hans:退出;'),
Item('logic device', 'zh-cn:逻辑器件; zh-tw:邏輯裝置;'),
Item('logic gate', 'zh-cn:逻辑门; zh-tw:邏輯閘; zh-hk:邏輯門;'),
Item('loop', 'zh-cn:循环; zh-tw:迴圈;'),
Item('lossless', 'zh-cn:无损; zh-tw:無失真;'),
Item('lossless compression', 'zh-cn:无损压缩; zh-tw:無失真壓縮; zh-hk:無損壓縮;'),
Item('lossy', '失真=>zh-cn:有损; 失真=>zh-sg:有损; 失真=>zh-my:有损;'), -- 做一个单向，看看问题是否严重
Item('lossy compression', 'zh-cn:有损压缩; zh-tw:失真壓縮;'),
Item('lost', 'zh-cn:丢失; zh-tw:遺失;'),
Item('low definition', 'zh-cn:低清; zh-tw:低畫質; zh-hk:低清;'),
Item('low level', 'zh-cn:低级; zh-tw:低階;'),
Item('low level', 'zh-cn:低端; zh-tw:低階;'),
Item('low-level language', 'zh-cn:低级语言; zh-tw:低階語言;'),
Item('low-level language', '低阶语言=>zh-cn:低级语言; 低阶语言=>zh-sg:低级语言; 低阶语言=>zh-my:低级语言;'),
Item('low-level language', '低级語言=>zh-tw:低階語言; 低级語言=>zh-hk:低階語言; 低级語言=>zh-mo:低階語言;'),
Item('low-level language', '低級語言=>zh-tw:低階語言; 低級語言=>zh-hk:低階語言; 低級語言=>zh-mo:低階語言;'),
Item('low-level programming language', 'zh-cn:低级编程语言; zh-tw:低階程式語言;'),
Item('low-level programming language', '低级编程語言=>zh-tw:低階程式語言; 低级编程語言=>zh-hk:低階程式語言; 低级编程語言=>zh-mo:低階程式語言;'),
{ type = 'text', text = [[

== M ==
]] },
Item('machine code', 'zh-cn:机器代码; zh-tw:機器碼; zh-hk:機械碼;'),
Item('machine code', '機器代碼=>zh-tw:機器碼; 機器代碼=>zh-hk:機械碼; 機器代碼=>zh-mo:機械碼;'),
Item('machine code', '机器码=>zh-tw:機器碼; 机器码=>zh-hk:機械碼; 机器码=>zh-mo:機械碼;'),
Item('mailing list', 'zh-cn:邮件列表; zh-tw:郵寄清單;'),
Item('managed code', 'zh-cn:托管代码; zh-tw:受控代碼;'),
Item('managed code', '受控代码=>zh-cn:托管代码; 受控代码=>zh-sg:托管代码; 受控代码=>zh-my:托管代码;'),
Item('managed code', '託管代碼=>zh-tw:受控代碼; 託管代碼=>zh-hk:受控代碼; 託管代碼=>zh-mo:受控代碼;'),
-- 單向轉換以避免過度轉換
Item('macro', '巨集=>zh-cn:宏; 巨集=>zh-sg:宏; 巨集=>zh-my:宏;'),
Item('macro virus', 'zh-cn:宏病毒; zh-tw:巨集病毒;'),
Item('macroblock', 'zh-cn:宏块; zh-tw:大區塊;'),
Item('macroblock', '大区块=>zh-cn:宏块; 大区块=>zh-sg:宏块; 大区块=>zh-my:宏块;'),
Item('macroblock', '宏塊=>zh-tw:大區塊; 宏塊=>zh-hk:大區塊; 宏塊=>zh-mo:大區塊;'),
Item('macroblock', '宏區塊=>zh-tw:大區塊; 宏區塊=>zh-hk:大區塊; 宏區塊=>zh-mo:大區塊;'),
Item('main memory', 'zh-cn:主存; zh-tw:主記憶體;'),
Item('mainframe', 'zh-cn:大型机; zh-tw:大型電腦;'),
Item('mapping', 'zh-cn:映射; zh-tw:對映;'),
Item('marketing', 'zh-cn:营销; zh-tw:行銷;'),
Item('Markup Language', 'zh-cn:置标语言; zh-tw:標示語言;'),
Item('Markup Language', 'zh-cn:标记语言; zh-tw:標示語言;'),
Item('Markup Language', 'zh-cn:标记语言; zh-tw:標記式語言;'),
Item('mask', '掩码=>zh-tw:遮罩; 掩码=>zh-hk:遮罩; 掩码=>zh-mo:遮罩;'),
Item('Master Boot Record', 'zh-cn:主引导记录; zh-tw:主開機紀錄;'),
-- Item('match', '匹配=>zh-tw:符合; 匹配=>zh-hk:符合; 匹配=>zh-mo:符合;'), 容易過度轉換
Item('media streamming', 'zh-cn:流媒体; zh-tw:串流媒體;'),
Item('medium', 'zh-cn:介质; zh-tw:媒介;'),
Item('medium', '媒质=>zh-tw:媒介; 媒质=>zh-hk:媒介; 媒质=>zh-mo:媒介;'),
Item('Medium Dependent Interface', 'zh-cn:介质相关接口; zh-tw:媒體相依介面;'),
Item('Megabyte', 'zh-hans:兆字节; zh-hant:百萬位元組;'),
Item('memory', 'zh-cn:存储器; zh-tw:記憶體;'),
Item('memory', '内部存储器=>zh-tw:記憶體; 内部存储器=>zh-hk:記憶體; 内部存储器=>zh-mo:記憶體;'),
Item('memory', '内存=>zh-tw:記憶體; 内存=>zh-hk:記憶體; 内存=>zh-mo:記憶體;'),
Item('memory', '內存=>zh-tw:記憶體; 內存=>zh-hk:記憶體; 內存=>zh-mo:記憶體;'),
Item('memory card', 'zh-cn:存储卡; zh-tw:記憶卡;'),
Item('memory leak', 'zh-cn:内存泄漏; zh-tw:記憶體漏失;'),
Item('memory leak', 'zh-cn:内存泄漏; zh-tw:記憶體流失;'),
Item('menu', 'zh-cn:菜单; zh-tw:選單;'),
Item('merge', '归并=>zh-tw:合併; 归并=>zh-hk:合併; 归并=>zh-mo:合併;'),
Item('message', 'zh-cn:消息; zh-tw:訊息;'),
Item('message authentication code', 'zh-cn:消息认证码; zh-tw:訊息鑑別碼;'),
Item('message box', 'zh-cn:消息框; zh-tw:訊息方塊;'),
Item('message-oriented', 'zh-cn:面向消息; zh-tw:訊息導向;'),
Item('message-oriented middleware', 'zh-cn:面向消息的中间件; zh-tw:訊息導向中介層;'),
Item('meta-programming', 'zh-cn:元编程; zh-tw:元程式設計;'),
Item('meta-programming', '元編程=>zh-tw:元程式設計; 元編程=>zh-hk:元程式設計; 元編程=>zh-mo:元程式設計;'),
Item('meta-programming', 'zh-cn:超编程; zh-tw:超程式設計;'),
Item('meta-programming', '超編程=>zh-tw:超程式設計; 超編程=>zh-hk:超程式設計; 超編程=>zh-mo:超程式設計; 超編程=>zh-cn:元编程;'),
-- 台灣專業以稱元資料為主
Item('metadata', 'zh-cn:元数据; zh-tw:元資料; zh-hk:元數據;'),
-- 參考文獻：劉青，溫昌斌，海峽兩岸科技名詞差異問題分析與試解，中國科技術語，(3), 2008, 65-69
Item('Metal Oxide Semiconductor', 'zh-cn:金属氧化物半导体; zh-tw:金氧半導體;'),
Item('Metropolitan Area Network', 'zh-cn:城域网; zh-tw:都會網路;'),
Item('Micro-blog', 'zh-cn:微博客; zh-tw:微部落格; zh-hk:微博客;'),
Item('Micro-blog', 'zh-cn:微型博客; zh-tw:微型部落格; zh-hk:微型博客;'),
Item('Micro-blog', '微網誌=>zh-cn:微博; 微網誌=>zh-sg:微博; 微網誌=>zh-my:微博;'),
Item('microcontroller', 'zh-cn:单片机; zh-tw:單晶片;'),
Item('middleware', 'zh-cn:中间件; zh-tw:中介軟體;'),
Item('midrange', 'zh-cn:中级; zh-tw:中階;'),
Item('midrange', 'zh-cn:中端; zh-tw:中階;'),
Item('MIDP', 'zh-cn:移动信息设备配置文件; zh-tw:行動資訊裝置設定檔; zh-hk:流動資訊器材定義檔;'),
Item('minesweeper', 'zh-cn:扫雷; zh-tw:踩地雷;'),
Item('mixed reality', 'zh-cn:混合现实; zh-tw:混合實境;'),
Item('mobile agent', 'zh-cn:移动代理; zh-tw:行動代理; zh-hk:流動代理;'),
Item('mobile app', 'zh-cn:移动应用; zh-tw:行動應用; zh-hk:流動應用;'),
Item('mobile broadcasting', 'zh-cn:移动广播; zh-tw:行動廣播; zh-hk:流動廣播;'),
Item('mobile browser', 'zh-cn:移动浏览器; zh-tw:行動瀏覽器; zh-hk:流動瀏覽器;'),
Item('mobile client', 'zh-cn:移动客户端; zh-tw:行動用戶端; zh-hk:流動用戶端;'),
Item('mobile code', 'zh-cn:移动代码; zh-tw:行動程式碼; zh-hk:流動程式碼;'),
Item('mobile company', 'zh-cn:移动公司; zh-tw:行動公司; zh-hk:流動公司;'),
Item('mobile computer', 'zh-cn:移动计算机; zh-tw:行動電腦; zh-hk:流動電腦;'),
Item('mobile communication', 'zh-cn:移动通信; zh-tw:行動通訊; zh-hk:流動通訊;'),
Item('mobile data', 'zh-cn:移动数据; zh-tw:行動資料; zh-hk:流動數據;'),
Item('mobile device', 'zh-cn:移动设备; zh-tw:行動裝置; zh-hk:流動裝置;'),
Item('mobile device', '移動設備=>zh-tw:行動裝置; 移動設備=>zh-hk:流動裝置; 移動設備=>zh-mo:流動裝置;'),
Item('mobile device', '移动装置=>zh-tw:行動裝置; 移动装置=>zh-hk:流動裝置; 移动装置=>zh-mo:流動裝置;'),
Item('mobile device', '移動裝置=>zh-tw:行動裝置; 移動裝置=>zh-hk:流動裝置; 移動裝置=>zh-mo:流動裝置;'),
Item('mobile device', '行動設備=>zh-tw:行動裝置; 行動設備=>zh-hk:流動裝置; 行動設備=>zh-mo:流動裝置;'),
Item('mobile device', '流動設備=>zh-tw:行動裝置; 流動設備=>zh-hk:流動裝置; 流動設備=>zh-mo:流動裝置;'),
Item('mobile Internet', 'zh-cn:移动互联网; zh-tw:行動網際網路; zh-hk:流動互聯網;'),
Item('Mobile Internet Device', 'zh-cn:移动联网设备; zh-tw:行動網路裝置; zh-hk:行動聯網裝置;'),
Item('mobile network', 'zh-cn:移动网络; zh-tw:行動網路; zh-hk:流動網絡;'),
Item('mobile network operator', 'zh-cn:移动网络运营商; zh-tw:行動網路業者; zh-hk:流動網絡營辦商;'),
Item('mobile operating system', 'zh-cn:移动操作系统; zh-tw:行動作業系統; zh-hk:流動作業系統;'),
Item('mobile operator', 'zh-cn:移动运营商; zh-tw:行動業者; zh-hk:流動營辦商;'),
Item('mobile pay', 'zh-cn:移动支付; zh-tw:行動支付; zh-hk:流動支付;'),
Item('mobile phone', 'zh-cn:移动电话; zh-tw:行動電話; zh-hk:流動電話;'),
Item('mobile platform', 'zh-cn:移动平台; zh-tw:行動平台; zh-hk:流動平台;'),
Item('mobile product', 'zh-cn:移动产品; zh-tw:行動產品; zh-hk:流動產品;'),
Item('Mobile software', 'zh-cn:移动软件; zh-tw:行動軟體; zh-hk:流動軟件;'),
Item('mobile telecom', 'zh-cn:移动电信; zh-tw:行動電信; zh-hk:流動電訊;'),
Item('Mobile telecom operator', 'zh-cn:移动电信运营商; zh-tw:行動電信業者; zh-hk:流動電訊營辦商;'),
Item('mobile television', 'zh-cn:移动电视; zh-tw:行動電視; zh-hk:流動電視;'),
Item('mobile terminal', 'zh-cn:移动终端; zh-tw:行動終端; zh-hk:流動終端;'),
Item('mobile terminal', 'zh-cn:移动端; zh-tw:行動端; zh-hk:流動端;'),
Item('mobile version', 'zh-cn:移动版; zh-tw:行動版; zh-hk:流動版;'),
Item('mobility', 'zh-cn:移动性; zh-tw:行動性; zh-hk:流動性;'),
Item('modem', 'zh-cn:调制解调器; zh-tw:數據機;'),
Item('modem', '調變解調器=>zh-cn:调制解调器; 調變解調器=>zh-sg:调制解调器; 調變解調器=>zh-my:调制解调器;'),
Item('modifier', 'zh-cn:修饰符; zh-tw:修飾詞;'),
Item('module', 'zh-cn:模块; zh-tw:模組;'),
Item('module', '模组=>zh-cn:模块; 模组=>zh-sg:模块; 模组=>zh-my:模块;'),
Item('module', '模塊=>zh-tw:模組; 模塊=>zh-hk:模組; 模塊=>zh-mo:模組;'),
Item('monolithic kernel', 'zh-cn:宏内核; zh-tw:單核心; zh-hk:整塊性核心;'),
Item('most derived class', 'zh-cn:最底层派生类; zh-tw:最末層衍生類別;'),
Item('motherboard', 'zh-cn:主板; zh-tw:主機板;'),
Item('mouse', 'zh-cn:鼠标; zh-tw:滑鼠;'),
Item('multi-channel network', 'zh-cn:多频道网络; zh-tw:多頻道聯播網;'),
Item('multi-part archive', 'zh-cn:分卷压缩; zh-tw:分割壓縮;'),
Item('multi-tasking', 'zh-cn:多任务; zh-tw:多工;'),
Item('multiagent system', 'zh-cn:多主体系统; zh-tw:多代理系統;'),
Item('multihoming', 'zh-cn:多宿主; zh-tw:內送流量備援容錯機制;'),
Item('Multimedia Messaging Service', 'zh-cn:彩信; zh-sg:多媒体简讯; zh-my:多媒体短讯; zh-tw:多媒體簡訊; zh-hk:多媒體短訊;'),
Item('multithreading', '多緒=>zh-cn:多线程; 多緒=>zh-sg:多线程; 多緒=>zh-my:多线程;'),
Item('mutual information', 'zh-cn:互信息; zh-tw:相互資訊;'),
Item('mutual information', '交互資訊=>zh-cn:互信息; 交互資訊=>zh-sg:互信息; 交互資訊=>zh-my:互信息;'),
Item('mutual information', '交互信息=>zh-tw:相互資訊; 交互信息=>zh-hk:相互資訊; 交互信息=>zh-mo:相互資訊;'),
Item('My Document', 'zh-cn:我的文档; zh-tw:我的文件;'),
Item('Mobile World Congress', 'zh-cn:世界移动通信大会; zh-tw:世界行動通訊大會; zh-hk:世界流動通訊大會;'),
Item('Mobile content management', 'zh-cn:移动内容管理; zh-tw:行動內容管理;'),
Item('Mobile application management', 'zh-cn:移动应用管理; zh-tw:行動應用管理;'),
Item('Mobile device management', 'zh-cn:移动设备管理; zh-tw:行動裝置管理;'),
{ type = 'text', text = [[

== N ==
]] },
Item('namespace', 'zh-cn:名字空间; zh-tw:命名空間;'),
Item('namespace', '名字空間=>zh-tw:命名空間; 名字空間=>zh-hk:命名空間; 名字空間=>zh-mo:命名空間;'),
Item('namespace', '命名空间=>zh-cn:名字空间; 命名空间=>zh-sg:名字空间; 命名空间=>zh-my:名字空间;'),
Item('native', '固有=>zh-tw:原生; 固有=>zh-hk:原生; 固有=>zh-mo:原生;'),
Item('narrowband', 'zh-cn:窄带; zh-tw:窄頻;'),
Item('native', 'zh-cn:本地的; zh-tw:原生的;'),
-- Item('native', 'zh-cn:本地; zh-tw:原生;'),
Item('navigation bar', 'zh-cn:导航条; zh-tw:導覽列;'),
Item('nest', 'zh-cn:嵌套; zh-tw:巢狀;'),
Item('Net disk', 'zh-cn:网盘; zh-tw:網路硬碟;'),
Item('Net disk', '網盤 => zh-tw:網路硬碟;網盤 => zh-hk:網路硬碟;網盤 => zh-mo:網路硬碟;'),
Item('Netbook', 'zh-cn:上网本; zh-tw:小筆電; zh-hk:NetBook;'),
Item('Netizen', '网民=>zh-cn:网民;网民=>zh-tw:網友;网民=>zh-hk:網民;'),
Item('Netizen', '網民=>zh-cn:网民;網民=>zh-tw:網友;網民=>zh-hk:網民;'),
Item('Netscape Navigator', 'zh-cn:网景导航者; zh-tw:網景領航員;'),
Item('Network', 'zh-cn:网络; zh-tw:網路; zh-hk:網絡;'),
Item('network card', '網路卡=>zh-cn:网卡; 網路卡=>zh-sg:网卡; 網路卡=>zh-my:网卡;'),
Item('network database', 'zh-cn:网状数据库; zh-tw:網狀式資料庫; zh-hk:網絡數據庫;'),
Item('Network Neighbourhood', 'zh-cn:网上邻居; zh-tw:網路上的芳鄰;'),
Item('Network operator', 'zh-cn:网络运营商; zh-tw:網路業者; zh-hk:網絡營辦商;'),
Item('NVIDIA', 'zh-cn:英伟达; zh-tw:輝達;'),
Item('normalization', 'zh-cn:规范化; zh-tw:規格化; zh-hk:規範化;'),
Item('Norton Ghost', 'zh-cn:诺顿克隆精灵; zh-tw:諾頓魅影系統;'),
Item('null list', 'zh-cn:空列表; zh-tw:空串列;'),
Item('null string', 'zh-cn:空串; zh-tw:空字串;'),
{ type = 'text', text = [[

== O ==
]] },
Item('object', 'zh-cn:对象; zh-tw:物件;'),
Item('object', '對象=>zh-tw:物件; 對象=>zh-hk:物件; 對象=>zh-mo:物件;'),
Item('object code', 'zh-cn:目标代码; zh-tw:目的碼; zh-hk:目標碼;'),
Item('object file', '目的檔案=>zh-cn:目标文件; 目的檔案=>zh-sg:目标文件; 目的檔案=>zh-my:目标文件;'),
Item('object file', 'zh-cn:目标文件; zh-tw:目的檔; zh-hk:目標文件;'),
Item('Object-oriented', 'zh-cn:面向对象; zh-tw:物件導向;'),
Item('Object-oriented programming', 'zh-cn:面向对象编程; zh-tw:物件導向程式設計;'),
Item('object', 'zh-cn:对象; zh-tw:物件;'),
Item('octree', 'zh-cn:八叉树; zh-tw:八元樹; zh-hk:八叉樹;'),
Item('Office Shortcut Bar', 'zh-cn:快捷工具栏; zh-tw:快捷列;'),
Item('offline', '脱机=>zh-tw:離線; 脱机=>zh-hk:離線; 脱机=>zh-mo:離線;'),
Item('ones\' complement', 'zh-cn:反码; zh-tw:一補數; zh-hk:一補碼;'),
Item('ones\' complement', '二进制反码=>zh-tw:一補數; 二进制反码=>zh-hk:一補碼; 二进制反码=>zh-mo:一補碼;'),
Item('online', 'zh-cn:在线; zh-tw:線上;'),
Item('online', '在線 => zh-tw:線上;'),
Item('online', '联机=>zh-tw:連線; 联机=>zh-hk:連線; 联机=>zh-mo:連線;'),
Item('online hard drive', 'zh-cn:网络硬盘; zh-tw:網路硬碟; zh-hk:網絡硬碟;'),
Item('online shopping', 'zh-cn:网络购物; zh-tw:網路購物; zh-hk:網絡購物;'),
Item('online shopping', '网上购物=>zh-tw:網路購物;'),
Item('online shopping', '網上購物=>zh-tw:網路購物;'),
Item('online video', 'zh-cn:在线视频; zh-tw:網路影片; zh-hk:線上影片;'),
-- Item('on the Internet', 'zh-cn:网络; zh-tw:網路; zh-hk:網上;'), 此处严重过度转换：可考虑设-{网上=>zh-tw:網路;}-的单向转换，但更建议延长词长。原理由：依台灣金融相關法律規定已連線為正式用語，非線上
Item('On-Line Transaction Processing', 'zh-cn:联机交易处理; zh-tw:線上異動處理;'),
Item('On-Line Analytical Processing', 'zh-cn:联机分析处理; zh-tw:連線分析處理;'),
Item('open', 'zh-cn:开启; zh-tw:開啟;'),
Item('Open Handset Alliance', 'zh-cn:开放手持设备联盟; zh-tw:開放手機聯盟;'),
Item('Open Mobile Alliance', 'zh-cn:开放移动联盟; zh-tw:開放行動聯盟; zh-hk:流動通訊開放制式聯盟;'),
Item('operand', 'zh-cn:操作数; zh-tw:運算元;'),
Item('operating system', 'zh-cn:操作系统; zh-tw:作業系統;'),
Item('operation object', 'zh-cn:操作对象; zh-tw:運算物件;'),
Item('operator', 'zh-cn:运算符; zh-tw:運算子;'),
Item('operator', '运算子=>zh-cn:运算符; 运算子=>zh-sg:运算符; 运算子=>zh-my:运算符;'),
Item('operator', '運算符=>zh-tw:運算子; 運算符=>zh-hk:運算子; 運算符=>zh-mo:運算子;'),
Item('operator', '操作符=>zh-tw:運算子; 操作符=>zh-hk:運算子; 操作符=>zh-mo:運算子;'),
Item('operator', '操作子=>zh-tw:運算子; 操作子=>zh-hk:運算子; 操作子=>zh-mo:運算子;'),
Item('optimal', '最优=>zh-tw:最佳; 最优=>zh-hk:最佳; 最优=>zh-mo:最佳;'),
Item('optimization', 'zh-hans:优化; zh-hant:最佳化; 最優化=>zh-hant:最佳化; 最优化=>zh-hant:最佳化;'),
Item('Optical Network Terminals', 'zh-cn:光网络终端; zh-tw:光纖網路終端;'),
Item('outport', 'zh-cn:导出; zh-tw:匯出;'),
Item('overflow', '上限溢位=>zh-cn:溢出; 上限溢位=>zh-sg:溢出; 上限溢位=>zh-my:溢出;'),
Item('overflow', 'zh-cn:溢出; zh-tw:溢位;'),
Item('overload', 'zh-cn:重载; zh-tw:多載;'),
Item('overload', '過載=>zh-cn:重载; 過載=>zh-sg:重载; 過載=>zh-my:重载;'),
Item('override', 'zh-cn:改写; zh-tw:覆寫;'),
{ type = 'text', text = [[

== P ==
]] },
Item('package', '套件=>zh-cn:包; 套件=>zh-sg:包; 套件=>zh-my:包;'),
Item('package management system', 'zh-cn:软件包管理系统; zh-tw:軟體套件管理系統; zh-hk:軟件套件管理系統;'),
Item('package of software', 'zh-cn:软件包; zh-tw:軟體套件; zh-hk:軟件套件;'),
Item('packet switch', 'zh-cn:分组交换; zh-tw:封包交換;'),
Item('page view', 'zh-cn:访问量; zh-tw:瀏覽量;'),
Item('paint', '小畫家=>zh-cn:画图; 小畫家=>zh-sg:画图; 小畫家=>zh-my:画图;'),
Item('palette', 'zh-cn:调色板; zh-tw:調色盤;'),
Item('paradigm', 'zh-cn:范型; zh-tw:範式;'),
Item('parallel', 'zh-cn:并行; zh-tw:並列;'),
Item('parallel computing', 'zh-cn:并行计算; zh-tw:平行計算;'),
Item('parallel port', 'zh-cn:并行端口; zh-tw:並列埠;'),
Item('parallel port', '并口=>zh-tw:並列埠; 并口=>zh-hk:並列埠; 并口=>zh-mo:並列埠;'),
Item('parallel port', '并行端口=>zh-tw:並列埠; 并行端口=>zh-hk:並列埠; 并行端口=>zh-mo:並列埠;'),
Item('parallel port', '并行接口=>zh-tw:並列埠; 并行接口=>zh-hk:並列埠; 并行接口=>zh-mo:並列埠;'),
Item('parameter list', 'zh-cn:参数列表; zh-tw:參數列;'),
Item('parameter list', 'zh-cn:参数表; zh-tw:參數列;'),
Item('parent class', 'zh-cn:父类; zh-tw:父類別;'),
Item('parser', 'zh-cn:分析器; zh-tw:剖析器;'),
Item('partition', 'zh-cn:分区; zh-tw:分割區; zh-hk:分區;'),
Item('paste', 'zh-cn:粘贴; zh-tw:貼上;'),
Item('Password Authentication Protocol', 'zh-cn:密码认证协议; zh-tw:通行碼鑑別協定;'),
Item('patch', 'zh-cn:补丁; zh-tw:修補程式;'),
-- Item('pattern', 'zh-cn:模式; zh-tw:範式;'), 容易過度轉換
Item('Peer-to-Peer', 'zh-cn:点对点; zh-tw:對等;'),
Item('performance', 'zh-cn:性能; zh-tw:效能;'),
Item('permission', '許可權=>zh-cn:权限; 許可權=>zh-sg:权限; 許可權=>zh-my:权限;'),
Item('persistence', 'zh-cn:持久性; zh-tw:永續性;'),
Item('Personal Area Network', 'zh-cn:个人网; zh-tw:個人區域網路;'),
Item('personal digital assistant', 'zh-cn:个人数码助理; zh-tw:個人數位助理; zh-hk:個人數碼助理;'),
Item('Petabyte', 'zh-hans:拍字节; zh-hant:拍位元組;'),
Item('photo', 'zh-cn:照片; zh-tw:相片;'),
Item('photocopy', 'zh-cn:复印; zh-tw:影印;'),
Item('physical layer', 'zh-cn:物理层; zh-tw:實體層;'),
Item('physical address', 'zh-cn:物理地址; zh-tw:實體位址;'),
Item('physical memory', 'zh-cn:物理内存; zh-tw:實體記憶體;'),
Item('picture viewer', 'zh-cn:图像检视器; zh-tw:圖片檢視器;'),
Item('picture viewer', '图像浏览器=>zh-tw:圖片檢視器; 图像浏览器=>zh-hk:圖片檢視器; 图像浏览器=>zh-mo:圖片檢視器;'),
Item('pipeline', 'zh-cn:流水线; zh-tw:管線; zh-hk:管線; zh-mo:管線;'),
Item('pipelining', 'zh-cn:流水线; zh-tw:管線; zh-hk:管線化; zh-mo:管線化;'),
Item('pixel', '畫素=>zh-cn:像素; 畫素=>zh-sg:像素; 畫素=>zh-my:像素; 畫素=>zh-hk:像素; 畫素=>zh-mo:像素;'),
Item('pixel', '画素=>zh-cn:像素; 画素=>zh-sg:像素; 画素=>zh-my:像素; 画素=>zh-hk:像素; 画素=>zh-mo:像素;'),
Item('placeholder', 'zh-cn:占位符; zh-tw:預留位置;'),
Item('Plug and Play', 'zh-cn:即插即用; zh-tw:隨插即用;'),
Item('plug-in', 'zh-cn:插件; zh-tw:外掛程式;'),
Item('plug-in', '外掛模組=>zh-cn:插件; 外掛模組=>zh-sg:插件; 外掛模組=>zh-my:插件;'),
Item('podcast', 'zh-cn:播客; zh-tw:Podcast;'),
Item('point and click', '点选=>zh-cn:点击; 点选=>zh-sg:点击; 点选=>zh-my:点击; 点选=>zh-hk:點擊; 点选=>zh-mo:點擊;'),
Item('point and click', '點選=>zh-cn:点击; 點選=>zh-sg:点击; 點選=>zh-my:点击; 點選=>zh-hk:點擊; 點選=>zh-mo:點擊;'),
Item('pointer', 'zh-cn:指针; zh-tw:指標;'),
Item('polymorphism', 'zh-cn:多态; zh-tw:多型;'),
Item('Popups', 'zh-cn:弹出窗口; zh-tw:彈出式視窗;'),
Item('port', 'zh-cn:端口; zh-tw:埠;'),
-- Item('port', '接口=>zh-tw:埠; 接口=>zh-hk:埠; 接口=>zh-mo:埠;'), 容易過度轉換
Item('port', '通訊埠=>zh-cn:端口;'),
Item('port forwarding', 'zh-cn:端口转发; zh-tw:通訊埠轉發;'),
Item('portable', 'zh-cn:便携式; zh-tw:可攜式;'),
Item('portable', '可携式=>zh-cn:便携式; 可携式=>zh-sg:便携式; 可携式=>zh-my:便携式;'),
Item('portable', '便攜式=>zh-tw:可攜式; 便攜式=>zh-hk:可攜式; 便攜式=>zh-mo:可攜式;'),
Item('portable', '便携=>zh-tw:可攜式; 便携=>zh-hk:可攜式; 便携=>zh-mo:可攜式;'),
Item('portable', '便攜=>zh-tw:可攜式; 便攜=>zh-hk:可攜式; 便攜=>zh-mo:可攜式;'),
Item('portable application', 'zh-cn:绿色软件; zh-tw:可攜式軟體; zh-hk:可攜式軟件;'),
Item('portable application', '綠色軟件=>zh-tw:可攜式軟體; 綠色軟件=>zh-hk:可攜式軟件; 綠色軟件=>zh-mo:可攜式軟件;'),
Item('portable application', '綠色軟體=>zh-tw:可攜式軟體; 綠色軟體=>zh-hk:可攜式軟件; 綠色軟體=>zh-mo:可攜式軟件;'),
Item('portable application', '便携软件=>zh-tw:可攜式軟體; 便携软件=>zh-hk:可攜式軟件; 便携软件=>zh-mo:可攜式軟件;'),
Item('portable edition', 'zh-cn:便携版; zh-tw:可攜式版本;'),
Item('portable hard drive', 'zh-cn:移动硬盘; zh-tw:行動硬碟; zh-hk:流動硬碟;'),
Item('Portable Document Format', 'zh-cn:可移植文档格式; zh-tw:可攜式文件格式;'),
Item('portal', 'zh-cn:门户系统; zh-tw:入口網站; zh-hk:入門系統;'),
Item('portal', 'zh-cn:门户网站; zh-tw:入口網站; zh-hk:入門網站;'),
Item('post', 'zh-cn:帖子; zh-tw:貼文;'),
Item('power bank', 'zh-cn:移动电源; zh-tw:行動電源; zh-hk:流動充電器'),
Item('preference', '预置=>zh-tw:偏好設定; 预置=>zh-hk:參數設置; 预置=>zh-mo:參數設置;'),
Item('preference settings', 'zh-cn:首选项; zh-tw:偏好設定; zh-hk:參數設置;'),
Item('prefix', 'zh-cn:前缀; zh-tw:字首;'),
Item('presentation', 'zh-cn:演示稿; zh-tw:簡報;'),
Item('print', 'zh-cn:打印; zh-tw:列印;'),
Item('print preview', 'zh-cn:打印预览; zh-tw:預覽列印;'),
Item('printer', 'zh-cn:打印机; zh-tw:印表機;'),
Item('procedural generation', '程序化生成=>zh-cn:过程生成; 程序化生成=>zh-sg:过程生成; 程序化生成=>zh-my:过程生成;'),
Item('procedural programming', 'zh-cn:过程式; zh-tw:程序式;'),
Item('procedural programming', 'zh-cn:过程化; zh-tw:程序化;'),
Item('procedural programming', 'zh-cn:面向过程; zh-tw:程序導向;'),
Item('process', '連作=>zh-cn:进程; 連作=>zh-sg:进程; 連作=>zh-my:进程;'),
Item('process', '處理程序=>zh-cn:进程; 處理程序=>zh-sg:进程; 處理程序=>zh-my:进程;'),
Item('process', '进程=>zh-tw:行程; 进程=>zh-hk:行程; 进程=>zh-mo:行程;'),
-- Item('process', '行程=>zh-cn:进程; 行程=>zh-sg:进程; 行程=>zh-my:进程;'), 容易過度轉換
-- Item('process', '過程=>zh-cn:进程; 過程=>zh-sg:进程; 過程=>zh-my:进程;'), 容易過度轉換
Item('process control block', 'zh-cn:进程控制块; zh-tw:過程控制段; zh-hk:行程控制表;'),
Item('process group', 'zh-cn:进程组; zh-tw:行程群組;'),
Item('product key', 'zh-cn:产品密钥; zh-tw:產品金鑰;'),
Item('profile', 'zh-cn:配置文件; zh-tw:設定檔;'),
Item('program', 'zh-cn:程序; zh-tw:程式;'),
Item('programmer', 'zh-cn:程序编写员; zh-tw:程式設計師;'),
Item('programmer', 'zh-cn:程序员; zh-tw:程式設計師;'),
Item('programmable', 'zh-cn:可编程; zh-tw:可程式化;'),
Item('programmable', '可規化=>zh-cn:可编程; 可規化=>zh-sg:可编程; 可規化=>zh-my:可编程;'),
Item('programming language', 'zh-cn:编程语言; zh-tw:程式語言;'),
Item('programming language', '程式语言=>zh-cn:编程语言; 程式语言=>zh-sg:编程语言; 程式语言=>zh-my:编程语言;'),
Item('programming language', '编程語言=>zh-tw:程式語言; 编程語言=>zh-hk:程式語言; 编程語言=>zh-mo:程式語言;'),
Item('programming language', '編程语言=>zh-tw:程式語言; 編程语言=>zh-hk:程式語言; 編程语言=>zh-mo:程式語言;'),
Item('programming language', '編程語言=>zh-tw:程式語言; 編程語言=>zh-hk:程式語言; 編程語言=>zh-mo:程式語言;'),
Item('Programming paradigm', 'zh-cn:编程范型; zh-tw:程式設計範式;'),
-- Item('project', 'zh-cn:工程; zh-tw:專案;'), 容易過度轉換
Item('project', 'zh-cn:项目; zh-tw:專案;'),
Item('project', '計畫=>zh-cn:项目; 計畫=>zh-sg:项目; 計畫=>zh-my:计划; 計畫=>zh-hk:計劃; 計畫=>zh-mo:計劃;'),
Item('project page', 'zh-cn:项目页; zh-tw:計畫頁;'),
Item('protocol', 'zh-cn:协议; zh-tw:協定;'),
Item('protocol', '協議=>zh-tw:協定; 協議=>zh-hk:協定; 協議=>zh-mo:協定;'),
Item('prototype-based programming', 'zh-cn:基于原型的编程; zh-tw:原型程式設計;'),
Item('proximity sensor', 'zh-cn:接近传感器; zh-tw:鄰近感測器;'),
Item('Pseudocode', 'zh-cn:伪代码; zh-tw:虛擬碼; zh-hk:偽代碼;'),
Item('pattern recognition', 'zh-cn:模式识别; zh-tw:圖型識別;'),
Item('Public land mobile network', 'zh-cn:公共陆基移动网; zh-tw:公用陸上行動網路; zh-hk:公地流動網路;'),
Item('pull-down lists', 'zh-cn:下拉列表; zh-tw:下拉式清單;'),
-- 維基百科內建功能
Item('purge', '刷新缓存=>zh-tw:清除快取; 刷新缓存=>zh-hk:清除快取; 刷新缓存=>zh-mo:清除快取;'),
Item('purge', 'zh-cn:清理缓存; zh-tw:清除快取;'),
Item('push', 'zh-cn:推送; zh-tw:推播;'),
{ type = 'text', text = [[

== Q ==
]] },
Item('QR code', '行動條碼=>zh-cn:QR码; 行動條碼=>zh-sg:QR码; 行動條碼=>zh-my:QR码; 行動條碼=>zh-hk:QR碼; 行動條碼=>zh-mo:QR碼;'),
Item('queue', 'zh-cn:队列; zh-tw:佇列;'),
Item('quadtree', 'zh-cn:四叉树; zh-tw:四元樹; zh-hk:四叉樹;'),
Item('quality', 'zh-cn:质量; zh-tw:品質; zh-hk:質素;'),
Item('quality', '品质=>zh-cn:质量; 品质=>zh-sg:质量; 品质=>zh-my:质量; 品质=>zh-hk:質素; 品质=>zh-mo:質素;'),
Item('quality', '质素=>zh-cn:质量; 质素=>zh-sg:质量; 质素=>zh-my:质量; 质素=>zh-tw:品質;'),
Item('quality', '質量=>zh-tw:品質; 質量=>zh-hk:質素; 質量=>zh-mo:質素;'),
{ type = 'text', text = [[

== R ==
]] },
Item('radio button', 'zh-cn:单选按钮; zh-tw:無線電鈕;'),
Item('random-access memory', '随机存储器=>zh-tw:隨機存取記憶體; 随机存储器=>zh-hk:隨機存取記憶體; 随机存储器=>zh-mo:隨機存取記憶體;'),
Item('random number', 'zh-cn:随机数; zh-tw:亂數;'),
Item('readme', 'zh-cn:自述文件; zh-tw:讀我檔案;'),
Item('read-only', 'zh-cn:只读; zh-tw:唯讀;'),
Item('read-only memory', 'zh-cn:只读存储器; zh-tw:唯讀記憶體;'),
Item('real mode', 'zh-cn:实模式; zh-tw:真實模式;'),
Item('real mode', '真实模式=>zh-cn:实模式; 真实模式=>zh-sg:实模式; 真实模式=>zh-my:实模式;'),
Item('real mode', '實模式=>zh-tw:真實模式; 實模式=>zh-hk:真實模式; 實模式=>zh-mo:真實模式;'),
Item('real-time', '实时=>zh-tw:即時; 实时=>zh-hk:即時; 实时=>zh-mo:即時;'),
Item('reboot', 'zh-cn:重启; zh-tw:重新啟動;'),
Item('reboot', '重新開機=>zh-cn:重启; 重新開機=>zh-sg:重启; 重新開機=>zh-my:重启;'),
Item('recognition', 'zh-cn:识别; zh-tw:辨識;'),
Item('recover', '回復=>zh-cn:恢复; 回復=>zh-sg:恢复; 回復=>zh-my:恢复;'),
Item('recovery disc', 'zh-cn:恢复光盘; zh-tw:還原光碟;'),
Item('recovery record', 'zh-cn:恢复记录; zh-tw:恢復記錄; zh-hk:修復記錄;'),
Item('recursion', 'zh-cn:递归; zh-tw:遞迴; zh-hk:遞歸;'),
Item('Recycle Bin', 'zh-cn:回收站; zh-tw:資源回收筒;'),
Item('redirect', 'zh-cn:重定向; zh-tw:重新導向;'),
Item('redirect page', 'zh-cn:重定向页; zh-tw:重新導向頁面;'),
Item('redirect page', '重定向頁=>zh-tw:重新導向頁面; 重定向頁=>zh-hk:重新導向頁面; 重定向頁=>zh-mo:重新導向頁面;'),
Item('redirect page', '重定向页面=>zh-tw:重新導向頁面; 重定向页面=>zh-hk:重新導向頁面; 重定向页面=>zh-mo:重新導向頁面;'),
Item('redirect page', '重定向頁面=>zh-tw:重新導向頁面; 重定向頁面=>zh-hk:重新導向頁面; 重定向頁面=>zh-mo:重新導向頁面;'),
Item('reference', 'zh-cn:引用; zh-tw:參照;'),
-- Item('reference', '參考=>zh-cn:引用; 參考=>zh-sg:引用; 參考=>zh-my:引用;'), 容易過度轉換
Item('dereference', 'zh-cn:解引用; zh-tw:解除參照;'),
Item('refresh', 'zh-cn:刷新; zh-tw:重新整理;'),
Item('register', 'zh-cn:寄存器; zh-tw:暫存器;'),
Item('registry', 'zh-cn:注册表; zh-tw:登錄檔;'),
Item('regular expression', 'zh-cn:正则表达式; zh-tw:正規表示式; zh-hk:正則表達式;'),
Item('regular language', 'zh-cn:正则语言; zh-tw:正規語言; zh-hk:正則語言;'),
Item('regular language', '正规语言=>zh-cn:正则语言; 正规语言=>zh-sg:正则语言; 正规语言=>zh-my:正则语言;'),
Item('reinstallation', 'zh-cn:重装; zh-tw:重新安裝;'),
Item('relational', '關聯=>zh-cn:关系; 關聯=>zh-sg:关系; 關聯=>zh-my:关系;'),
Item('relational database', 'zh-cn:关系数据库; zh-tw:關聯式資料庫; zh-hk:關聯式數據庫;'),
Item('release', '釋出=>zh-cn:发布; 釋出=>zh-sg:发布; 釋出=>zh-my:发布;'),
-- Item('release', 'zh-cn:发行; zh-tw:釋出;'),
Item('remote', 'zh-cn:远程; zh-tw:遠端;'),
Item('remote desktop protocol', 'zh-cn:远程桌面协议; zh-tw:遠端桌面協定;'),
Item('remote procedure call', 'zh-cn:远程过程调用; zh-tw:遠端程序呼叫;'),
-- 「可移动磁盘」對應「抽取式磁碟」（來自微軟官網）
Item('removable', 'zh-cn:可移动; zh-tw:抽取式;'),
Item('rename', 'zh-cn:重命名; zh-tw:重新命名;'),
Item('render', 'zh-cn:渲染; zh-tw:彩現;'),
Item('repeating group', 'zh-cn:重复组; zh-tw:重複群;'),
Item('reply', 'zh-hans:回复; zh-hant:回覆;'),
Item('reply', 'zh-hans:答复; zh-hant:答覆;'),
Item('Republic of Gamers', 'zh-cn:玩家国度; zh-tw:玩家共和國;'),
Item('reset', 'zh-cn:重置; zh-tw:重設;'),
Item('resolution', 'zh-cn:分辨率; zh-tw:解析度; zh-hk:解像度;'),
Item('response', '响应=>zh-tw:回應;'),
Item('Rich Internet application', 'zh-cn:丰富互联网应用程序; zh-tw:多樣化網際網路應用程式; zh-hk:多樣化互聯網應用程式;'),
Item('routine', 'zh-cn:例程; zh-tw:常式;'),
Item('run', 'zh-cn:运行; zh-tw:執行;'),
Item('running in the background', 'zh-cn:后台运行; zh-tw:背景執行;'),
{ type = 'text', text = [[

== S ==
]] },
Item('sample', 'zh-cn:示例; zh-tw:範例;'),
Item('sampling rate', 'zh-cn:采样率; zh-tw:取樣率;'),
Item('sampling rate', '取樣頻率=>zh-cn:采样率; 取樣頻率=>zh-sg:采样率; 取樣頻率=>zh-my:采样率; 取樣頻率=>zh-hk:取樣率; 取樣頻率=>zh-mo:取樣率;'),
Item('SanDisk', 'zh-cn:闪迪; zh-tw:新帝; zh-hk:SanDisk;'),
Item('save', '保存=>zh-tw:儲存; 保存=>zh-hk:儲存; 保存=>zh-mo:儲存;'),
Item('scanner', 'zh-cn:扫描仪; zh-tw:掃描器;'),
Item('schedule', 'zh-cn:调度; zh-tw:排程;'),
Item('scheduler', 'zh-cn:调度器; zh-tw:排程器;'),
Item('screen', 'zh-cn:屏幕; zh-tw:螢幕; zh-hk:熒幕;'),
Item('screensaver', 'zh-cn:屏幕保护程序; zh-tw:螢幕保護裝置; zh-hk:熒幕保護裝置;'),
Item('screenshot', 'zh-cn:截屏; zh-tw:螢幕擷取; zh-hk:熒幕擷取;'),
Item('script', 'zh-cn:脚本; zh-tw:指令碼;'),
Item('script', '腳本=>zh-tw:指令碼; 腳本=>zh-hk:指令碼; 腳本=>zh-mo:指令碼;'),
Item('scripting language', 'zh-cn:脚本语言; zh-tw:手稿語言;'),
Item('scripting language', '腳本語言=>zh-tw:手稿語言; 腳本語言=>zh-hk:手稿語言; 腳本語言=>zh-mo:手稿語言;'),
Item('scroll', 'zh-cn:滚动; zh-tw:捲動;'),
Item('scroll bar', 'zh-cn:滚动条; zh-tw:捲軸;'),
Item('scroll bar', 'zh-cn:滚动栏; zh-tw:捲軸;'),
Item('scroll box', 'zh-cn:滚动框; zh-tw:捲動方塊;'),
Item('SDK', 'zh-cn:软件开发工具包; zh-tw:軟體開發套件; zh-hk:軟件開發套件;'),
Item('search', 'zh-cn:搜索; zh-tw:搜尋;'),
Item('search box', 'zh-cn:搜索框; zh-tw:搜尋方塊;'),
Item('search key', 'zh-cn:搜索关键字; zh-tw:搜尋鍵碼;'),
Item('second normal form', 'zh-cn:第二范式; zh-tw:第二正規化;'),
Item('sector', 'zh-cn:扇区; zh-tw:磁區;'),
Item('Secure Sockets Layer', 'zh-cn:安全套接层; zh-tw:安全通訊協定;'),
Item('security software', 'zh-cn:安全软件; zh-tw:安全軟體; zh-hk:保安軟件;'),
Item('security software', '保安軟體=>zh-cn:安全软件; 保安軟體=>zh-sg:安全软件; 保安軟體=>zh-my:安全软件; 保安軟體=>zh-hk:保安軟件; 保安軟體=>zh-mo:保安軟件;'),
Item('Semantic Web', 'zh-cn:语义网; zh-tw:語意網;'),
Item('semantics', 'zh-cn:语义; zh-tw:語意;'),
Item('semaphore', 'zh-cn:信号量; zh-tw:號誌; zh-hk:訊號量;'),
Item('semaphore', '信號量=>zh-tw:號誌; 信號量=>zh-hk:號誌; 信號量=>zh-mo:號誌;'),
Item('send', 'zh-cn:发送; zh-tw:傳送;'),
Item('send SMS', 'zh-cn:发短信; zh-sg:发简讯; zh-my:发短讯; zh-tw:傳簡訊; zh-hk:傳短訊;'),
Item('sensor', 'zh-cn:传感器; zh-tw:感測器;'),
Item('Sequencing', 'zh-cn:测序; zh-tw:定序;'),
Item('Serial computing', 'zh-cn:串行计算; zh-tw:序列計算;'),
Item('Serial port', 'zh-hans:串行端口; zh-hant:序列埠;'),
Item('Serial port', 'zh-hans:串口;zh-hant:序列埠;'),
Item('server', 'zh-cn:服务器; zh-tw:伺服器;'),
Item('server', '服務器=>zh-tw:伺服器; 服務器=>zh-hk:伺服器; 服務器=>zh-mo:伺服器;'),
Item('server message block', 'zh-cn:服务器消息块; zh-tw:伺服器訊息區塊;'),
Item('server-side', 'zh-cn:服务端; zh-tw:伺服器端;'),
Item('server-side', '伺服端=>zh-cn:服务端; 伺服端=>zh-sg:服务端; 伺服端=>zh-my:服务端;'),
Item('server-side', '服務端=>zh-tw:伺服器端; 服務端=>zh-hk:伺服器端; 服務端=>zh-mo:伺服器端;'),
Item('service framework', 'zh-cn:服务框架; zh-tw:服務架構;'),
Item('session', 'zh-cn:会话; zh-tw:對談;'),
Item('Session Identity', 'zh-cn:会话标识; zh-tw:交談識別碼;'),
Item('session ID', 'zh-cn:会话标识; zh-tw:交談識別碼;'),
Item('session hijacking', 'zh-cn:会话劫持; zh-tw:連線劫持;'),
Item('setting', 'zh-cn:设置; zh-tw:設定; zh-hk:設置;'),
Item('set-top box', 'zh-cn:机顶盒; zh-tw:機上盒; zh-hk:機頂盒;'),
Item('share', 'zh-cn:共享; zh-tw:共享; zh-hk:共用;'),
Item('shared folder', '分享資料夾=>zh-cn:共享文件夹; 分享資料夾=>zh-sg:共享文件夹; 分享資料夾=>zh-my:共享文件夹; 分享資料夾=>zh-tw:共用資料夾;'),
Item('short video', 'zh-cn:短视频; zh-tw:短影音; zh-hk:短影音;'),
Item('shortcut', 'zh-cn:快捷方式; zh-tw:捷徑;'),
Item('shortcut key', 'zh-cn:快捷键; zh-tw:快速鍵;'),
Item('Single Link', 'zh-cn:单通道; zh-tw:單連結;'),
Item('signal', 'zh-cn:信号; zh-tw:訊號;'),
Item('signal', '信號=>zh-tw:訊號; 信號=>zh-hk:訊號; 信號=>zh-mo:訊號;'),
Item('signal', '讯号=>zh-cn:信号; 讯号=>zh-sg:信号; 讯号=>zh-my:信号; 讯号=>zh-tw:訊號;'),
Item('signature', 'zh-cn:签名; zh-tw:簽章;'),
Item('simulated reality', 'zh-cn:模拟现实; zh-tw:模擬實境;'),
Item('single sign-on', 'zh-cn:单点登录; zh-tw:單一登入;'),
Item('Site Identity Button', 'zh-cn:站点标识按钮; zh-tw:網站識別鈕;'),
Item('sixth normal form', 'zh-cn:第六范式; zh-tw:第六規格化;'),
Item('skin', '皮肤=>zh-tw:外觀; 皮肤=>zh-hk:佈景主題; 皮肤=>zh-mo:佈景主題;'),
Item('slider', 'zh-cn:滑块; zh-tw:滾軸;'),
Item('smart', 'zh-cn:智能; zh-sg:智慧; zh-tw:智慧型; zh-hk:智能;'),
Item('smart card', 'zh-cn:智能卡; zh-sg:智慧卡; zh-tw:智慧卡; zh-hk:智能卡;'),
Item('Smart speaker', 'zh-cn:智能音箱; zh-tw:智慧型喇叭; zh-hk:智能音箱;'),
Item('smart television', 'zh-cn:智能电视; zh-tw:智慧型電視; zh-hk:智能電視;'),
Item('smartphone', 'zh-cn:智能手机; zh-tw:智慧型手機; zh-hk:智能手機;'),
Item('smartwatch', 'zh-cn:智能手表; zh-tw:智慧型手錶; zh-hk:智能手錶;'),
Item('SMS', 'zh-cn:短信; zh-sg:简讯; zh-my:短讯; zh-tw:簡訊; zh-hk:短訊;'),
Item('SMS', '短消息=>zh-sg:简讯; 短消息=>zh-my:短讯; 短消息=>zh-tw:簡訊; 短消息=>zh-hk:短訊; 短消息=>zh-mo:短訊;'),
Item('SMS', '短信息=>zh-sg:简讯; 短信息=>zh-my:短讯; 短信息=>zh-tw:簡訊; 短信息=>zh-hk:短訊; 短信息=>zh-mo:短訊;'),
Item('Snowden', 'zh-cn:斯诺登; zh-tw:史諾登; zh-hk:斯諾登;'),
Item('social media', 'zh-hans:社会媒体; zh-cn:社交媒体; zh-tw:社群媒體; zh-hk:社交媒體;'),
Item('social network', 'zh-cn:社交网络; zh-tw:社群網路; zh-hk:社交網絡;'),
Item('social networking site', 'zh-cn:社交网站; zh-tw:社群網站; zh-hk:社交網站;'),
Item('socket', 'zh-cn:套接字; zh-tw:通訊端;'),
Item('socket', '通訊端點=>zh-cn:套接字; 通訊端點=>zh-my:套接字; 通訊端點=>zh-sg:套接字;'),
Item('sockets layer', 'zh-cn:套接层; zh-tw:通訊層;'),
Item('software', 'zh-cn:软件; zh-tw:軟體; zh-hk:軟件;'),
Item('software process', 'zh-cn:软件过程; zh-tw:軟體流程; zh-hk:軟件流程;'),
Item('solid archive', 'zh-cn:固实压缩; zh-tw:結實壓縮;'),
Item('Sony Mobile', 'zh-cn:索尼移动; zh-tw:索尼行動; zh-hk:索尼流動;'),
Item('Sony Mobile Communications', 'zh-cn:索尼移动通信; zh-tw:索尼行動通訊; zh-hk:索尼流動通訊;'),
Item('Sound card', 'zh-cn:声卡; zh-tw:音效卡;'),
Item('source code', 'zh-cn:源代码; zh-sg:原始码; zh-tw:原始碼;'),
Item('source code', '源代碼=>zh-sg:原始码; 源代碼=>zh-my:原始码; 源代碼=>zh-tw:原始碼; 源代碼=>zh-hk:原始碼; 源代碼=>zh-mo:原始碼;'),
Item('source code', '源码=>zh-sg:原始码; 源码=>zh-my:原始码; 源码=>zh-tw:原始碼; 源码=>zh-hk:原始碼; 源码=>zh-mo:原始碼;'),
Item('source code', '源碼=>zh-sg:原始码; 源碼=>zh-my:原始码; 源碼=>zh-tw:原始碼; 源碼=>zh-hk:原始碼; 源碼=>zh-mo:原始碼;'),
Item('source file', 'zh-cn:源文件; zh-tw:原始檔;'),
Item('spreadsheet', 'zh-cn:电子表格; zh-tw:電子試算表;'),
Item('spreadsheet', '试算表=>zh-cn:表格; 试算表=>zh-sg:表格; 试算表=>zh-my:表格;'),
Item('spreadsheet', '試算表=>zh-cn:表格; 試算表=>zh-sg:表格; 試算表=>zh-my:表格;'),
Item('spider solitaire', 'zh-cn:蜘蛛纸牌; zh-tw:連環新接龍;'),
Item('statement', 'zh-cn:语句; zh-tw:語句; zh-hk:陳述式;'),
Item('stack', 'zh-cn:堆栈; zh-tw:堆疊;'),
Item('stack frame', 'zh-cn:堆栈帧; zh-tw:堆疊框; zh-hk:堆疊幀;'),
Item('stack frame', '栈帧=>zh-tw:堆疊框; 栈帧=>zh-hk:堆疊幀; 栈帧=>zh-mo:堆疊幀;'),
Item('stack-oriented', 'zh-cn:面向堆栈; zh-tw:堆疊導向;'),
Item('standard definition', 'zh-cn:标清; zh-tw:標準畫質; zh-hk:標清;'),
Item('static typing', 'zh-cn:静态类型; zh-tw:靜態型別;'),
Item('status bar', 'zh-cn:状态栏; zh-tw:狀態列;'),
Item('storage', 'zh-cn:存储; zh-tw:儲存;'),
Item('storage', '存儲=>zh-tw:儲存; 存儲=>zh-hk:儲存; 存儲=>zh-mo:儲存;'),
Item('stored procedure', 'zh-cn:存储程序; zh-tw:儲存程序;'),
Item('stored procedure', '預存程序=>zh-cn:存储程序; 預存程序=>zh-sg:存储程序; 預存程序=>zh-my:存储程序;'),
Item('stored procedure', '存儲程序=>zh-tw:儲存程序; 存儲程序=>zh-hk:儲存程序; 存儲程序=>zh-mo:儲存程序;'),
Item('stored procedure', '存储过程=>zh-tw:儲存程序; 存储过程=>zh-hk:儲存程序; 存储过程=>zh-mo:儲存程序;'),
Item('stored procedure', '存儲過程=>zh-tw:儲存程序; 存儲過程=>zh-hk:儲存程序; 存儲過程=>zh-mo:儲存程序;'),
Item('stream', '串流=>zh-cn:流; 串流=>zh-sg:流; 串流=>zh-my:流;'),
Item('stream', '流式=>zh-tw:串流; 流式=>zh-hk:串流; 流式=>zh-mo:串流;'),
Item('stream cipher', 'zh-cn:流密码; zh-tw:串流加密法;'),
Item('string', 'zh-cn:字符串; zh-tw:字串;'),
Item('strong typing', 'zh-cn:强类型; zh-tw:強型別;'),
Item('submit', '送出=>zh-cn:提交; 送出=>zh-sg:提交; 送出=>zh-my:提交;'),
Item('subnet', 'zh-cn:子网; zh-tw:子網路; zh-hk:子網絡;'),
Item('subnet mask', 'zh-cn:子网掩码; zh-tw:子網路遮罩; zh-hk:子網絡遮罩;'),
Item('subroutine', 'zh-cn:子例程; zh-tw:次常式;'),
Item('suffix', 'zh-cn:后缀; zh-tw:字尾;'),
-- 有可能過度轉換，編輯時須注意
Item('support', 'zh-cn:支持; zh-tw:支援;'),
Item('Sun Microsystems', 'zh-cn:Sun微系统; zh-tw:昇陽電腦; zh-hk:太陽電腦;'),
Item('syntax highlighting', 'zh-cn:语法高亮; zh-tw:語法突顯;'),
Item('syntax highlighting', '語法凸顯=>zh-cn:语法高亮; 語法凸顯=>zh-sg:语法高亮; 語法凸顯=>zh-my:语法高亮;'),
Item('syntax highlighting', '语法高亮度=>zh-tw:語法突顯; 语法高亮度=>zh-hk:語法突顯; 语法高亮度=>zh-mo:語法突顯;'),
Item('syntax highlighting', '語法高亮度=>zh-tw:語法突顯; 語法高亮度=>zh-hk:語法突顯; 語法高亮度=>zh-mo:語法突顯;'),
Item('system (format)', '制式=>zh-tw:格式; 制式=>zh-hk:格式; 制式=>zh-mo:格式;'),
{ type = 'text', text = [[

== T ==
]] },
Item('tab', 'zh-cn:标签页; zh-tw:分頁;'),
Item('tab', 'zh-cn:选项卡; zh-tw:索引標籤;'),
Item('tail recursion', 'zh-cn:尾部递归; zh-tw:尾端遞迴;'),
Item('target', 'zh-cn:目标软件; zh-tw:目標軟體; zh-hk:目標軟件;'),
Item('target user', 'zh-cn:目标用户; zh-tw:目標使用者;'),
Item('task bar', 'zh-cn:任务栏; zh-tw:工作列;'),
Item('task manager', 'zh-cn:任务管理器; zh-tw:工作管理員;'),
Item('task switch', 'zh-cn:任务切换; zh-tw:工作切換;'),
Item('template', '樣板=>zh-cn:模板; 樣板=>zh-sg:模板; 樣板=>zh-my:模板; 樣板=>zh-tw:模板; 樣板=>zh-hk:模板; 樣板=>zh-mo:模板;'),
Item('Terabyte', 'zh-hans:太字节; zh-hant:兆位元組;'),
Item('terminator', 'zh-cn:终结器; zh-tw:終端子;'),
Item('ternary linked list', 'zh-cn:三叉链表; zh-tw:三元連結串列;'),
Item('ternary linked list', '三叉鏈表=>zh-tw:三元連結串列; 三叉鏈表=>zh-hk:三元連結串列; 三叉鏈表=>zh-mo:三元連結串列;'),
Item('ternary search tree', 'zh-cn:三叉搜索树; zh-tw:三元搜尋樹; zh-hk:三叉搜尋樹;'),
Item('ternary search tree', '三叉查找树=>zh-tw:三元搜尋樹; 三叉查找树=>zh-hk:三叉搜尋樹; 三叉查找树=>zh-mo:三叉搜尋樹;'),
Item('ternary tree', 'zh-cn:三叉树; zh-tw:三元樹; zh-hk:三叉樹;'),
-- Item('terrestrial', '地面=>zh-tw:無線; 地面=>zh-hk:無線; 地面=>zh-mo:無線;'), 易过度转换
Item('terrestrial television', 'zh-cn:地面电视; zh-tw:無線電視; zh-hk:地面電視;'),
Item('terrestrial broadcasting', 'zh-cn:地面广播; zh-tw:無線廣播; zh-hk:地面廣播;'),
Item('text', '文本=>zh-tw:文字; 文本=>zh-hk:文字; 文本=>zh-mo:文字;'),
Item('textbox', 'zh-cn:文本框; zh-tw:文字方塊; zh-hk:文本框;'),
Item('text editor', 'zh-cn:文本编辑器; zh-tw:文字編輯器;'),
Item('text file', 'zh-cn:文本文件; zh-tw:文字檔案;'),
Item('third normal form', 'zh-cn:第三范式; zh-tw:第三正規化;'),
Item('threads', 'zh-cn:线程; zh-tw:執行緒; zh-hk:線程;'),
Item('throw', 'zh-cn:抛出; zh-tw:丟擲; zh-hk:投擲;'),
Item('thumbnail', 'zh-cn:缩略图; zh-tw:縮圖;'),
Item('timeout', 'zh-hans:超时; zh-hant:逾時;'),
Item('title bar', 'zh-cn:标题栏; zh-tw:標題列;'),
Item('token', 'zh-cn:权标; zh-tw:符記;'),
Item('token', 'zh-cn:令牌; zh-tw:權杖;'),
Item('toolbar', 'zh-cn:工具栏; zh-tw:工具列;'),
Item('touch', 'zh-cn:触摸; zh-tw:輕觸;'),
Item('touchscreen', 'zh-cn:触摸屏; zh-tw:觸控式螢幕; zh-hk:輕觸式熒幕;'),
Item('touchscreen', 'zh-cn:触屏; zh-tw:觸控螢幕; zh-hk:輕觸熒幕;'),
Item('TouchPad', 'zh-cn:触摸板; zh-tw:觸控板;'),
Item('track', 'zh-cn:磁道; zh-tw:磁軌;'),
Item('traditional (Chinese)', '正體=>zh-cn:繁体; 正體=>zh-sg:繁体; 正體=>zh-my:繁体; 正體=>zh-hk:繁體; 正體=>zh-mo:繁體;'),
Item('Trinitron', 'zh-cn:特丽珑; zh-tw:特麗霓虹;'),
Item('troubleshooting', 'zh-cn:疑难解答; zh-tw:疑難排解;'),
Item('Turing completeness', 'zh-cn:图灵完备; zh-tw:圖靈完備;'),
Item('Turing completeness', '图灵完备=>zh-cn:图灵完备; 图灵完备=>zh-sg:图灵完备; 图灵完备=>zh-my:图灵完全;'),
Item('Turing completeness', '圖靈完全=>zh-tw:圖靈完備; 圖靈完全=>zh-hk:圖靈完備; 圖靈完全=>zh-mo:圖靈完備;'),
Item('two-dimensional code', 'zh-cn:二维码; zh-tw:二維條碼;'),
Item('two-dimensional code', '二维条码=>zh-cn:二维码; 二维条码=>zh-sg:二维码; 二维条码=>zh-my:二维码;'),
Item('two-dimensional code', '二維碼=>zh-tw:二維條碼; 二維碼=>zh-hk:二維條碼; 二維碼=>zh-mo:二維條碼;'),
Item('two\'s complement', 'zh-cn:补码; zh-tw:二補數; zh-hk:二補碼;'),
Item('two\'s complement', '二进制补码=>zh-tw:二補數; 二进制补码=>zh-hk:二補碼; 二进制补码=>zh-mo:二補碼;'),
Item('two\'s-complement integer', '补码整数=>zh-tw:二補數;'),
Item('type', '型別=>zh-cn:类型; 型別=>zh-sg:类型; 型別=>zh-my:类型;'),
Item('type', '型態=>zh-cn:类型; 型態=>zh-sg:类型; 型態=>zh-my:类型;'),
Item('type checking', 'zh-cn:类型检查; zh-tw:型別檢查;'),
Item('type system', 'zh-cn:类型系统; zh-tw:型別系統;'),
{ type = 'text', text = [[

== U ==
]] },
Item('Ultrabook', 'zh-cn:超极本; zh-tw:超極致筆電; zh-hk:Ultrabook;'),
Item('Ultrabook', '超级本=>zh-tw:超極致筆電; 超级本=>zh-hk:Ultrabook; 超级本=>zh-mo:Ultrabook;'),
Item('unary function', 'zh-cn:单参函数; zh-tw:一元函式;'),
Item('underflow', '欠位=>zh-cn:下溢; 欠位=>zh-my:下溢; 欠位=>zh-sg:下溢;'),
Item('underline', 'zh-cn:下划线; zh-tw:底線;'),
Item('undo', 'zh-cn:撤销; zh-tw:復原;'),
Item('undo', '撤銷=>zh-tw:復原; 撤銷=>zh-hk:復原; 撤銷=>zh-mo:復原;'),
Item('undo', '撤消=>zh-tw:復原; 撤消=>zh-hk:復原; 撤消=>zh-mo:復原;'),
-- Item('update', '升级=>zh-tw:更新; 升级=>zh-hk:更新; 升级=>zh-mo:更新;'), 容易過度轉換
-- Item('update', '升級=>zh-tw:更新; 升級=>zh-hk:更新; 升級=>zh-mo:更新;'), 容易過度轉換
Item('unified shader model', 'zh-cn:统一渲染架构; zh-tw:統一著色器架構;'),
Item('uninstall', 'zh-cn:卸载; zh-tw:解除安裝;'),
Item('uninstall', '卸載=>zh-tw:解除安裝; 卸載=>zh-hk:解除安裝; 卸載=>zh-mo:解除安裝;'),
Item('Universal Serial Bus', 'zh-cn:通用串行总线; zh-tw:通用序列匯流排;'),
Item('Universal Serial Bus', '通用串列匯流排=>zh-cn:通用序列总线; 通用串列匯流排=>zh-sg:通用串行总线; 通用串列匯流排=>zh-my:通用串行总线;'),
Item('Universal Serial Bus', '通用串行總線=>zh-tw:通用序列匯流排; 通用串行總線=>zh-hk:通用序列匯流排; 通用串行總線=>zh-mo:通用序列匯流排;'),
Item('upload', '上传=>zh-hk:上載;上传=>zh-mo:上載;'),
Item('upload', '上傳=>zh-hk:上載;上傳=>zh-mo:上載;'),
Item('UPS', 'zh-cn:电源保护; zh-tw:不斷電系統;'),
Item('URL shortening', 'zh-cn:缩略网址; zh-tw:縮網址;'),
Item('URL shortening', '縮略網址 => zh-tw:縮網址;'),
Item('USB flash drive', 'zh-cn:U盘; zh-tw:USB隨身碟; zh-hk:USB手指;'),
Item('USB flash drive', '闪存盘=>zh-tw:隨身碟; 闪存盘=>zh-hk:USB手指; 闪存盘=>zh-mo:USB手指;'),
Item('USB flash drive', '优盘=>zh-tw:隨身碟; 优盘=>zh-hk:USB手指; 优盘=>zh-mo:USB手指;'),
Item('USB flash drive', '隨身碟=>zh-cn:U盘; 隨身碟=>zh-sg:U盘; 隨身碟=>zh-my:U盘; 隨身碟=>zh-hk:USB手指; 隨身碟=>zh-mo:USB手指;'),
Item('user', 'zh-cn:用户;zh-sg:用户;zh-my:用户;zh-hk:用戶;zh-mo:用戶;zh-tw:使用者;'),
Item('user group', '使用者群=>zh-cn:用户组;使用者群=>zh-sg:用户组;使用者群=>zh-my:用户组;使用者群=>zh-hk:用戶組;使用者群=>zh-mo:用戶組;'),
Item('user group', 'zh-tw:使用者群組;zh-cn:用户组;zh-sg:用户组;zh-my:用户组;zh-hk:用戶組;zh-mo:用戶組;'),
Item('user interface', 'zh-cn:用户界面; zh-tw:使用者介面; zh-hk:用戶介面;'),
Item('user interface', '用户介面=>zh-cn:用户界面; 用户介面=>zh-sg:用户界面; 用户介面=>zh-my:用户界面;'),
Item('user interface', 'zh-cn:人机界面; zh-tw:人機介面;'),
Item('user page', 'zh-cn:用户页; zh-tw:使用者頁面; zh-hk:用戶頁;'),
Item('user page', '用戶頁面=>zh-cn:用户页; 用戶頁面=>zh-sg:用户页; 用戶頁面=>zh-my:用户页;'),
Item('userbox', 'zh-cn:用户框; zh-tw:使用者方塊; zh-hk:用戶框;'),
Item('username', 'zh-cn:用户名; zh-tw:使用者名稱; zh-hk:用戶名;'),
Item('username', '用戶名稱=>zh-cn:用户名; 用戶名稱=>zh-sg:用户名; 用戶名稱=>zh-my:用户名;'),
{ type = 'text', text = [[

== V ==
]] },
Item('variable', 'zh-cn:变量; zh-tw:變數;'),
Item('variable', '变数=>zh-cn:变量; 变数=>zh-sg:变量; 变数=>zh-my:变量;'),
Item('variable', '變量=>zh-tw:變數; 變量=>zh-hk:變數; 變量=>zh-mo:變數;'),
Item('variable bitrate', 'zh-cn:可变码率; zh-tw:變動位元速率; zh-hk:動態編碼率;'),
Item('vector', '矢量=>zh-tw:向量; 矢量=>zh-hk:向量; 矢量=>zh-mo:向量;'),
Item('vector graphics', 'zh-cn:矢量图形; zh-tw:向量圖形;'),
Item('VGA connector', 'zh-cn:视频接口; zh-tw:視訊連接頭; zh-hk:影像端子;'),
Item('video card', 'zh-cn:显卡; zh-tw:顯示卡;'),
Item('video card', '显示卡=>zh-cn:显卡; 显示卡=>zh-sg:显卡; 显示卡=>zh-my:显卡;'),
Item('video card', '顯卡=>zh-tw:顯示卡; 顯卡=>zh-hk:顯示卡; 顯卡=>zh-mo:顯示卡;'),
Item('video document', 'zh-cn:视频文档; zh-tw:視訊檔案;'),
Item('video file', 'zh-cn:视频文件; zh-tw:視訊檔; zh-hk:影片檔;'),
Item('video file', 'zh-cn:视频档; zh-tw:視訊檔; zh-hk:影片檔;'),
Item('video game', 'zh-hans:视频游戏; zh-hant:電動遊戲;'),
Item('video input', 'zh-cn:视频输入; zh-tw:視訊輸入; zh-hk:視頻輸入;'),
Item('video memory', 'zh-cn:显存; zh-tw:視訊記憶體; zh-hk:影像記憶體;'),
Item('video output', 'zh-cn:视频输出; zh-tw:視訊輸出; zh-hk:視頻輸出;'),
Item('video processor', 'zh-cn:视频处理器; zh-tw:影像處理器;'),
Item('video streaming', 'zh-cn:影音流; zh-tw:影音串流;'),
Item('video track', 'zh-cn:视频轨; zh-tw:視訊軌; zh-hk:視頻軌;'),
Item('videotape', 'zh-cn:录像带; zh-tw:錄影帶;'),
Item('videotape', '录相带=>zh-tw:錄影帶; 录相带=>zh-hk:錄影帶; 录相带=>zh-mo:錄影帶;'),
Item('view', 'zh-cn:查看; zh-tw:檢視;'),
Item('virtual function', 'zh-cn:虚函数; zh-tw:虛擬函式;'),
Item('virtual machine', 'zh-cn:虚拟机; zh-tw:虛擬機器;'),
Item('virtual memory', 'zh-cn:虚拟内存; zh-tw:虛擬記憶體;'),
Item('visit', '造訪=>zh-cn:访问; 造訪=>zh-sg:访问; 造訪=>zh-my:访问;'),
Item('visual', 'zh-cn:可视化; zh-tw:視覺化;'),
Item('volatile (memory)', 'zh-cn:易失性; zh-tw:揮發性;'),
Item('volume', '磁碟區=>zh-cn:卷; 磁碟區=>zh-sg:卷; 磁碟區=>zh-my:卷;'),
Item('Logical volume management', 'zh-cn:逻辑卷管理; zh-tw:邏輯捲軸管理;'),
Item('Virtual Private Network', 'zh-cn:虚拟专用网; zh-tw:虛擬私人網路;'),
Item('von Neumann', 'zh-cn:冯·诺伊曼; zh-tw:馮·紐曼;'),
{ type = 'text', text = [[

== W ==
]] },
Item('wallpaper', 'zh-cn:壁纸; zh-tw:桌布;'),
Item('watermark', 'zh-cn:水印; zh-tw:浮水印;'),
Item('Watson', 'zh-cn:沃森; zh-tw:華生;'),
Item('weak typing', 'zh-cn:弱类型; zh-tw:弱型別;'),
Item('web animation', 'zh-cn:网络动画; zh-tw:網路動畫; zh-hk:網絡動畫;'),
Item('webcache', 'zh-cn:网页快照; zh-tw:頁面快取檔;'),
Item('webcam', 'zh-cn:摄像头; zh-tw:網路攝影機; zh-hk:網絡攝影機;'),
Item('webcomics', 'zh-cn:网络漫画; zh-tw:網路漫畫; zh-hk:網絡漫畫;'),
Item('Wide Area Network', 'zh-cn:广域网; zh-tw:廣域網路;'),
Item('wildcard character', 'zh-cn:通配符; zh-sg:万用字元; zh-tw:萬用字元;'),
-- Item('window', 'zh-cn:窗口; zh-tw:視窗;'), Microsoft Windows操作系统稱作視窗
Item('window manager', 'zh-cn:窗口管理器; zh-tw:視窗管理員;'),
Item('Western Digital', 'zh-cn:西部数据; zh-tw:威騰電子;'),
Item('wide screen', 'zh-cn:宽屏;zh-tw:寬螢幕;zh-hk:寬屏幕;'),
Item('wide screen', '宽面屏=>zh-tw:寬螢幕;宽面屏=>zh-hk:寬屏幕;宽面屏=>zh-mo:寬屏幕;'),
Item('wide screen', '寬面屏=>zh-tw:寬螢幕;寬面屏=>zh-hk:寬屏幕;寬面屏=>zh-mo:寬屏幕;'),
Item('Windows Explorer', 'zh-cn:资源管理器; zh-tw:檔案總管;'),
Item('wizard', 'zh-cn:向导; zh-tw:精靈;'),
Item('word process', 'zh-cn:文字处理; zh-tw:文書處理;'),
Item('word processor', 'zh-cn:文字处理器; zh-tw:文書處理器;'),
Item('workgroup', 'zh-cn:工作组; zh-tw:工作群組;'),
Item('World Wide Web', 'zh-cn:万维网; zh-tw:全球資訊網; zh-hk:萬維網;'),
Item('World Wide Web Consortium', 'zh-cn:万维网联盟; zh-tw:全球資訊網協會; zh-hk:萬維網聯盟;'),
Item('write-only', 'zh-cn:只写; zh-tw:唯寫;'),
Item('write-only memory', 'zh-cn:只写存储器; zh-tw:唯寫記憶體;'),
Item('write protection', 'zh-cn:写保护; zh-tw:防寫;'),
Item('Wind River', 'zh-cn:风河; zh-tw:溫瑞爾;'),
{ type = 'text', text = [[

== X ==
]] },
Item('Xerox', 'zh-cn:施乐; zh-tw:全錄; zh-hk:施樂;'),
Item('X window system', 'zh-cn:X窗口系统; zh-tw:X視窗系統; zh-hk:X Window系統;'),
Item('X window system', 'X视窗系统=>zh-cn:X窗口系统; X视窗系统=>zh-sg:X窗口系统; X视窗系统=>zh-my:X窗口系统;'),
Item('X window system', 'X Window系统=>zh-cn:X窗口系统; X Window系统=>zh-sg:X窗口系统; X Window系统=>zh-my:X窗口系统;'),
{ type = 'text', text = [[

== Y ==
]] },
Item('Yottabyte', 'zh-hans:尧字节; zh-hant:佑位元組;'),
{ type = 'text', text = [[

== Z ==
]] },
Item('Zettabyte', 'zh-hans:泽字节; zh-hant:皆位元組;'),
Item('Zuckerberg', 'zh-cn:扎克伯格; zh-tw:祖克柏; zh-hk:朱克伯格;'),
{ type = 'text', text = [[

== 其他 ==
]] },
Item('3-D film', 'zh-hans:三维电影; zh-hant:3D電影;'),
Item('3D computer', 'zh-hans:三维计算机; zh-hant:3D電腦;'),
Item('3D computer graphics', 'zh-hans:三维计算机图形; zh-hant:3D電腦圖形;'),
Item(nil, 'zh-cn:浏览框; zh-tw:瀏覽域;'),
Item(nil, 'zh-cn:定位框; zh-tw:定位域;'),
-- Item(nil, 'zh-cn:电信; zh-tw:電信; zh-hk:電訊;'), 容易過度轉換。該詞有可能是某些電信公司官方名稱中的一部分，例如「電訊盈科」變成「電信盈科」，「中華電信」變成「中華電訊」。
Item(nil, 'zh-cn:电信商; zh-tw:電信商; zh-hk:電訊商;'),
Item(nil, 'zh-cn:电信公司; zh-tw:電信公司; zh-hk:電訊公司;'),
Item(nil, 'zh-cn:电信业; zh-tw:電信業; zh-hk:電訊業;'),
Item(nil, 'zh-cn:电信运营商; zh-tw:電信業者; zh-hk:電訊供應商;'),
Item(nil, 'zh-cn:电信服务; zh-tw:電信服務; zh-hk:電訊服務;'),
Item(nil, 'zh-cn:电信行业; zh-tw:電信行業; zh-hk:電訊行業;'),
-- 简中少用“撷”
Item(nil, '擷=>zh-cn:截; 擷=>zh-sg:截; 擷=>zh-my:截;'),
Item(nil, 'zh-cn:乔布斯; zh-tw:賈伯斯; zh-hk:喬布斯;'),
Item(nil, 'zh-cn:鲍尔默; zh-tw:巴爾默;'),
Item(nil, 'zh-cn:扒站; zh-tw:砍站;'),
{ type = 'text', text = [[

== 防止過度轉換 ==
]] },
-- 避免 字体->字型 的過度轉換
Item(nil, 'zh-hans:文字体系; zh-hant:文字體系;'),
Item(nil, 'zh-hans:汉字体系; zh-hant:漢字體系;'),
-- 避免 當機->死机 的過度轉換
Item('dead robot', 'zh-hans:当机器; zh-hant:當機器;'),
-- 避免 時脈->时钟频率 的过度转换
Item('clock rate', '時脈頻率=>zh-cn:时钟频率; 時脈頻率=>zh-sg:时钟频率; 時脈頻率=>zh-my:时钟频率;'),
Item('contacts', 'zh-hans:通讯录; zh-hant:通訊錄;'),
Item('emoji', 'zh-hans:绘文字; zh-hant:繪文字;'),
-- 避免 程式->程序 的过度转换
Item('equation', 'zh-hans:方程式; zh-hant:方程式;'),
-- 避免 資料->数据/數據 的過度轉換
Item('References', 'zh-hans:参考资料; zh-hant:參考資料;'),
Item(nil, 'zh-hans:电视频; zh-hant:電視頻;'),
Item(nil, 'zh-hans:电影片; zh-hant:電影片;'),
Item(nil, 'zh-hans:字符号; zh-hant:字符號;'),
-- 以下均为名從主人
Item('China Telecom', 'zh-hans:中国电信; zh-hant:中國電信;'),
Item('Chunghwa Telecom', 'zh-hans:中华电信; zh-hant:中華電信;'),
Item(nil, 'zh-hans:网民报告; zh-hant:網民報告;'), -- 泡泡網民報告
Item(nil, 'zh-hans:网络电视台; zh-hant:網絡電視台;'),
Item(nil, 'zh-hans:网路电视台; zh-hant:網路電視台;'),
Item(nil, 'zh-hans:网络广播电视台; zh-hant:網絡廣播電視台;'),
Item(nil, 'zh-hans:网络安全和信息化; zh-hant:網絡安全和信息化;'),
Item(nil, 'zh-hans:互联网信息办公室; zh-hant:互聯網信息辦公室;'),
Item('CAC', 'zh-hans:中共中央网络安全和信息化领导小组办公室; zh-hant:中共中央網絡安全和信息化領導小組辦公室;'),
Item('CNCERT', 'zh-hans:国家互联网应急中心; zh-hant:國家互聯網應急中心;'),
Item('CNCERT', 'zh-hans:互联网应急中心; zh-hant:互聯網應急中心;'),
Item('CNNIC', 'zh-hans:中国互联网络信息中心; zh-hant:中國互聯網絡信息中心;'),
Item('CNNIC', 'zh-hans:互联网络信息中心; zh-hant:互聯網絡信息中心;'),
Item('Industry and Information Technology', 'zh-hans:工业和信息化; zh-hant:工業和信息化;'), -- 中华人民共和国工业和信息化部
Item('National Administration of Surveying, Mapping and Geoinformation', 'zh-hans:国家测绘地理信息局; zh-hant:國家測繪地理信息局;'),
Item('Hudong Baike', 'zh-hans:互动百科; zh-hant:互動百科;'),
Item('World Internet Conference', 'zh-hans:世界互联网大会; zh-hant:世界互聯網大會;'),
Item('Alibaba Cloud', 'zh-hans:阿里云计算; zh-hant:阿里雲計算;'),
Item('Tencent Cloud', 'zh-hans:腾讯云计算; zh-hant:騰訊雲計算;'),
Item('Baidu Cloud', 'zh-hans:百度云计算; zh-hant:百度雲計算;'),
Item('LeCloud', 'zh-hans:乐视云计算; zh-hant:樂視雲計算;'),
Item('ByteDance', 'zh-hans:字节跳动; zh-hant:字節跳動;'),
Item(nil, 'zh-hans:人渣文本; zh-hant:人渣文本;'),
Item(nil, 'zh-hans:资讯台; zh-hant:資訊台;'),
Item(nil, 'zh-hans:资讯频道; zh-hant:資訊頻道;'), -- 避免电视频道名称过度转换
-- 防止「共享」過度轉換
Item('Wikimedia Commons', 'zh-hans:维基共享资源; zh-hant:維基共享資源;'),
Item('shareware', 'zh-cn:共享软件; zh-tw:共享軟體;'),
-- 防止「數據」過度轉換
Item('Wikidata', 'zh-hans:维基数据; zh-hant:維基數據;'),
-- 以下均为防止“视频”过度转换
Item('Baidu Video', 'zh-hans:百度视频; zh-hant:百度視頻;'),
Item('Netease Video', 'zh-hans:网易视频; zh-hant:網易視頻;'),
Item('Sina Video', 'zh-hans:新浪视频; zh-hant:新浪視頻;'),
Item('Sohu Video', 'zh-hans:搜狐视频; zh-hant:搜狐視頻;'),
Item('Tencent Video', 'zh-hans:腾讯视频; zh-hant:騰訊視頻;'),
Item('Tik Tok', 'zh-hans:抖音短视频; zh-hant:抖音短視頻;'),
Item('Tudou Video', 'zh-hans:土豆视频; zh-hant:土豆視頻;'),
Item('Vigo Video', 'zh-hans:火山小视频; zh-hant:火山小視頻;'),
Item('Xigua Video', 'zh-hans:西瓜视频; zh-hant:西瓜視頻;'),
Item('Youku Video', 'zh-hans:优酷视频; zh-hant:優酷視頻;'),
-- 以下均为防止“博客”过度转换
Item('Netease Blog', 'zh-hans:网易博客; zh-hant:網易博客;'),
Item('Sina Blog', 'zh-hans:新浪博客; zh-hant:新浪博客;'),
Item('Sohu Blog', 'zh-hans:搜狐博客; zh-hant:搜狐博客;'),
Item('Tencent Blog', 'zh-hans:腾讯博客; zh-hant:騰訊博客;'),
Item('Williamlong', 'zh-hans:月光博客; zh-hant:月光博客;'),
Item('bookstw', 'zh-hans:博客来; zh-hant:博客來;'), -- 台灣的博客來網路書店
-- 以下均为防止“相册”过度转换
Item('Netease Album', 'zh-hans:网易相册; zh-hant:網易相冊;'),
Item('Baidu Album', 'zh-hans:百度相册; zh-hant:百度相冊;'),
-- 以下均为防止“搜索”过度转换
Item('360 Search', 'zh-hans:360搜索; zh-hant:360搜索;'),
Item('Baidu Search', 'zh-hans:百度搜索; zh-hant:百度搜索;'),
Item('Sogou Search', 'zh-hans:搜狗搜索; zh-hant:搜狗搜索;'),
Item(nil, 'zh-hans:360综合搜索; zh-hant:360綜合搜索;'),
-- 防止公司名稱過度轉換
Item('Alibaba.com Ltd.', 'zh-hans:阿里巴巴网络; zh-hant:阿里巴巴網絡;'),
Item('Alibaba.com Ltd.', 'zh-hans:谷翔信息技术; zh-hant:谷翔信息技術;'),
Item('Sumavision', 'zh-hans:数码视讯; zh-hant:數碼視訊;'), -- 中国大陆的一家CA供应商
Item('Smartone', 'zh-hans:数码通; zh-hant:數碼通;'), -- 香港通信公司
-- 避免 社区->社群 的過度轉換
Item(nil, 'zh-hans:草榴社区; zh-hant:草榴社區;'),
-- 避免 移动版->行動版/流動版 的過度轉換
Item(nil, 'zh-hans:移动版面; zh-hant:移動版面;'),
Item(nil, 'zh-hans:移动版块; zh-hant:移動版塊;'),
-- 避免 智能->智慧/智慧型 的過度轉換
Item(nil, 'zh-hans:智能ABC; zh-hant:智能ABC;'),
Item(nil, 'zh-hans:智慧城市; zh-hant:智慧城市;'),
-- 避免 命令列->命令行 的過度轉換
Item(nil, 'zh-hans:命令列表; zh-hant:命令列表;'),
-- 避免 支持->支援 的過度轉換
Item('support vector', 'zh-hans:支持向量; zh-hant:支持向量;'),
Item('supporter', 'zh-hans:支持者; zh-hant:支持者;'),
Item('I support', 'zh-hans:我支持; zh-hant:我支持;'),
Item('support me', 'zh-hans:支持我; zh-hant:支持我;'),
Item('support he', 'zh-hans:他支持; zh-hant:他支持;'),
Item('support he', 'zh-hans:支持他; zh-hant:支持他;'),
Item('support she', 'zh-hans:她支持; zh-hant:她支持;'),
Item('support she', 'zh-hans:支持她; zh-hant:支持她;'),
-- 避免 最优->最佳 的過度轉換
Item(nil, 'zh-hans:最优秀; zh-hant:最優秀;'),
Item(nil, 'zh-hans:最优美; zh-hant:最優美;'),
Item(nil, 'zh-hans:最优质; zh-hant:最優質;'),
Item(nil, 'zh-hans:最优先; zh-hant:最優先;'),
-- 避免 导出->匯出 的過度轉換
Item(nil, 'zh-hans:推导; zh-hant:推導;'),
-- 避免 子类->子類別 的過度轉換
Item(nil, '子类别=>zh-tw:子類別; 子类别=>zh-hk:子類別; 子类别=>zh-mo:子類別;'),
Item(nil, 'zh-hans:子类型; zh-hant:子類型;'),
-- 避免 C++类->C++類別 的過度轉換
Item(nil, 'zh-hans:C++类似; zh-hant:C++類似;'),
Item(nil, 'zh-hans:C++类型; zh-hant:C++類型;'),
-- 避免 C++的类->C++的類別 的過度轉換
Item(nil, 'zh-hans:C++的类型; zh-hant:C++的類型;'),
-- 避免 Java类->Java類別 的過度轉換
Item(nil, 'zh-hans:Java类似; zh-hant:Java類似;'),
Item(nil, 'zh-hans:Java类型; zh-hant:Java類型;'),
-- 避免 Java的类->Java的類別 的過度轉換
Item(nil, 'zh-hans:Java的类型; zh-hant:Java的類型;'),
-- 避免 复杂度类->複雜度類別 的過度轉換
Item(nil, 'zh-hans:复杂度类似; zh-hant:複雜度類似;'),
-- 避免 基于类->類別基礎 的過度轉換
Item(nil, 'zh-hans:基于类似; zh-hant:基於類似;'),
Item(nil, 'zh-hans:基于类型; zh-hant:基於類型;'),
-- 避免 布尔->布林 的過度轉換
Item(nil, 'zh-hans:·布尔; zh-hant:·布爾;'),
-- 避免 圖學->图形学 的過度轉換
Item(nil, 'zh-hans:地图学; zh-hant:地圖學;'),
Item(nil, 'zh-hans:试图学; zh-hant:試圖學;'),
Item(nil, 'zh-hans:企图学; zh-hant:企圖學;'),
Item(nil, 'zh-hans:电图学; zh-hant:電圖學;'),
-- 避免 執行->运行 的過度轉換
Item('executable', 'zh-hans:可执行; zh-hant:可執行;'),
Item('executor', 'zh-hans:执行者; zh-hant:執行者;'),
-- 避免 高亮->突顯 的過度轉換
Item(nil, 'zh-hans:高亮度; zh-hant:高亮度;'),
-- 避免 访问->存取 的過度轉換
Item(nil, 'zh-hans:访问学者; zh-hant:訪問學者;'),
-- 避免 存取->访问 的過度轉換
Item('random-access', 'zh-hans:随机存取; zh-hant:隨機存取;'),
-- 避免 代码/代碼->程式碼 的過度轉換
Item(nil, '程序代码=>zh-tw:程式碼; 程序代码=>zh-hk:程式碼; 程序代码=>zh-mo:程式碼;'),
Item(nil, '程序代碼=>zh-tw:程式碼; 程序代碼=>zh-hk:程式碼; 程序代碼=>zh-mo:程式碼;'),
Item(nil, '程式代码=>zh-tw:程式碼; 程式代码=>zh-hk:程式碼; 程式代码=>zh-mo:程式碼;'),
Item(nil, '程式代碼=>zh-tw:程式碼; 程式代碼=>zh-hk:程式碼; 程式代碼=>zh-mo:程式碼;'),
Item(nil, 'zh-hans:类型代码; zh-hant:類型代碼;'),
-- 避免 码率/碼率->位元速率 的過度轉換
Item(nil, 'zh-hans:误码率; zh-hant:誤碼率;'),
Item('rate of coincident code', 'zh-hans:重码率;zh-hant:重碼率;'),
-- 避免 交互->互動 的過度轉換
Item(nil, '交互資訊=>zh-tw:交互資訊; 交互資訊=>zh-hk:交互資訊; 交互資訊=>zh-mo:交互資訊;'),
-- 避免 程序->程式 的過度轉換
Item(nil, '預存程序=>zh-tw:預存程序; 預存程序=>zh-hk:預存程序; 預存程序=>zh-mo:預存程序;'),
-- 避免 復原->撤销 的過度轉換
Item(nil, 'zh-hans:回复原; zh-hant:回復原;'),
Item(nil, 'zh-hans:恢复原; zh-hant:恢復原;'),
-- 避免 模拟/模擬->類比 的過度轉換
Item('analogizer', 'zh-hans:模拟器; zh-hant:模擬器;'),
-- 避免 檔案->文件 的過度轉換
Item('archives', 'zh-hans:档案馆; zh-hant:檔案館;'),
Item('archives', 'zh-hans:档案室; zh-hant:檔案室;'),
-- 避免 字符->字元 的過度轉換
Item('Hong Kong Supplementary Character Set', 'zh-hans:香港增补字符集; zh-hant:香港增補字符集;'),
Item('Macao Supplementary Character Set', 'zh-hans:澳门增补字符集; zh-hant:澳門增補字符集;'),
-- 避免 資訊->信息 的過度轉換
Item('Macao Information System Character Set', 'zh-hans:澳门资讯系统字集; zh-hant:澳門資訊系統字集;'),
-- 避免 数据包->封包 的過度轉換
Item(nil, 'zh-cn:数据包括; zh-tw:資料包括; zh-hk:數據包括;'),
Item(nil, 'zh-cn:数据包含; zh-tw:資料包含; zh-hk:數據包含;'),
-- 避免 比特->位元 的過度轉換
Item('bitcent', 'zh-hans:比特分; zh-hant:比特分;'),
Item('bitcoin', 'zh-hans:比特币; zh-hant:比特幣;'),
Item('BitComet', 'zh-hans:比特彗星; zh-hant:比特彗星;'),
Item('BitSpirit', 'zh-hans:比特精灵; zh-hant:比特精靈;'),
Item('micro-bitcoin', 'zh-hans:微比特; zh-hant:微比特;'),
Item('milli-bitcoin', 'zh-hans:毫比特; zh-hant:毫比特;'),
-- 避免 函数/函數->函式 的過度轉換
Item('functional', 'zh-hans:函数式; zh-hant:函數式;'),
-- 避免 套件->包 的過度轉換
Item('Office Suite', 'zh-hans:办公室套件; zh-hant:辦公室套件;'),
-- 避免 实模式->真實模式 的過度轉換
Item('real mode', '真实模式=>zh-tw:真實模式; 真实模式=>zh-hk:真實模式; 真实模式=>zh-mo:真實模式;'),
-- 避免 滚动->捲動 的過度轉換
Item('rolling update', 'zh-hans:滚动更新; zh-hant:滾動更新;'),
-- 避免 脚本->指令碼 的過度轉換
Item('script kiddie', 'zh-hans:脚本小子; zh-hant:腳本小子;'),
-- 避免 电脑/電腦->计算机 的過度轉換
Item('tablet computer', 'zh-hans:平板电脑; zh-hant:平板電腦;'),
-- 避免 佈景->布景 的過度轉換
Item('theme', '布景主题=>zh-tw:佈景主題; 佈景主題=>zh-tw:佈景主題;'),
-- 避免 字型->字体 的過度轉換
Item('wubi', 'zh-hans:五笔字型; zh-hant:五筆字型;'),
-- 避免 运算符->運算子 的過度轉換
Item('operator', 'zh-hans:运算符号; zh-hant:運算符號;'),
-- 避免 代码/代碼->程式碼 的過度轉換
Item('code list', 'zh-hans:代码表; zh-hant:代碼表;'),
-- 避免 国家安全局->國家安全域 的過度轉換
Item('NSB', '国家安全局=>zh-tw:國家安全局; 國家安全局=>zh-tw:國家安全局;'),
-- 避免 完全屏蔽->完全熒幕蔽 的過度轉換
Item('block', 'zh-hans:完全屏蔽; zh-hant:完全屏蔽;'),
{ type = 'text', text = [=[

== 外部連結 ==
* [http://ihome.ust.hk/~lbsun/terms.html 英漢計算機及網絡通訊技術詞彙]
* [http://www.iicm.org.tw/term/termb_0.htm 電腦名詞譯名]
* [https://data.gov.tw/dataset/15275 國家教育研究院-兩岸對照名詞-計算機學術名詞]（[[國家教育研究院]]）

[[Category:公共转换组模块|{{SUBPAGENAME}}]]
]=] },

},
}
