-- 用法： Item('原文', '轉換規則')
local Item = require('cgroup/core').Item;

return {

name = 'Math',
description = '数学',
content = {
{ type = 'text', text = [[

== 避免過度轉換 ==
:'''请在每个转换项目的后面注明转换的原因。'''
]] },
Item('constant', 'zh-hans:常数; zh-hant:常數;'), -- 與[[Module:CGroup/IT]]配合時，避免 常數->常量 的過度轉換
Item('directional derivative', 'zh-hans:方向导数; zh-hant:方向導數;'), -- 避免 向导->嚮導 的過度轉換
Item('equations', 'zh-hans:方程组; zh-hant:方程組;'), -- 避免 方程->方程式 的過度轉換
Item('expression', 'zh-hans:表达式; zh-hant:表達式;'), -- 與[[Module:CGroup/IT]]配合時，避免 表达式->運算式 的過度轉換
Item('function', 'zh-hans:函数; zh-hant:函數;'), -- 與[[Module:CGroup/IT]]配合時，避免 函数/函數->函式 的過度轉換
Item('identity element', 'zh-hans:单位元素; zh-hant:單位元素;'), -- 避免 单位元->單位元素 的過度轉換
Item('non-zero element', 'zh-hans:非零元素; zh-hant:非零元素;'), -- 避免 零元素->零元 的過度轉換
Item('permutation group', 'zh-hans:置换群; zh-hant:置換群;'), -- 避免 置換->排列 的過度轉換
Item('target set', 'zh-hans:目标集合; zh-hant:目標集合;'), -- 避免 目标集->目標集合 的過度轉換
Item('vector', 'zh-hans:向量; zh-hant:向量;'), -- 與[[Module:CGroup/Physics]]配合時，避免 向量->矢量 的過度轉換
Item('mean square error', 'zh-hans:均方差; zh-hant:均方差;'), -- 避免 方差->變異數 的過度轉換
Item(nil, 'zh-hans:积分形式; zh-hant:積分形式;'), -- 避免 分形->碎形 的過度轉換
Item(nil, 'zh-hans:微分形式; zh-hant:微分形式;'), -- 避免 分形->碎形 的過度轉換
Item(nil, 'zh-hans:幺元素; zh-hant:么元素;'), -- 避免 么元->單位元素/單位元 的過度轉換
Item(nil, 'zh-hans:不仅当; zh-hant:不僅當;'), -- 避免 仅当/僅當->唯若 的過度轉換
{ type = 'text', text = [[
== 数学家姓名 ==
]] },
Item('Bézout', 'zh-cn:裴蜀; zh-tw:貝祖;'),
Item('Borel', 'zh-cn:博雷尔; zh-tw:鮑萊耳;'),
Item('Chebyshev', 'zh-cn:切比雪夫; zh-tw:柴比雪夫;'),
Item('Christoffel', 'zh-cn:克里斯托费尔; zh-tw:克里斯多福;'),
Item('Clifford', 'zh-cn:克利福德; zh-tw:克里福;'),
Item('Cramer', 'zh-cn:克莱姆; zh-tw:克拉瑪'),
Item('Copeland', 'zh-cn:科普兰; zh-tw:克柏蘭;'),
Item('Descartes', 'zh-cn:笛卡尔; zh-tw:笛卡兒; zh-hk:笛卡爾;'),
Item('de Moivre', 'zh-cn:棣莫弗; zh-tw:棣美弗; zh-hk:狄默夫;'),
Item('Eratosthenes', 'zh-cn:埃拉托斯特尼; zh-tw:埃拉托斯特尼; zh-hk:愛拉托散尼;'),
Item('Erdős', 'zh-cn:埃尔德什; zh-tw:艾狄胥;'),
Item('Erdős Pál', 'zh-cn:埃尔德什·帕尔; zh-tw:艾狄胥·帕爾'), -- 注意原名为匈牙利人名（匈牙利人名同中文采用“姓-名”方式），台译时使用美式“名-姓”，中译使用匈牙利式“姓-名”
Item('Fibonacci', 'zh-cn:斐波纳契; zh-tw:費波納契; zh-hk:斐波納契;'),
Item('Fourier', 'zh-cn:傅里叶; zh-tw:傅立葉;'),
Item('[[:en:Milton Friedman|Milton Friedman]]', 'zh-cn:弗里德曼; zh-sg:弗里德曼; zh-tw:傅利曼; zh-hk:佛利民;'),
Item('Slutsky', 'zh-cn:斯卢茨基; zh-tw:史拉斯基; 斯勒茨基 =>zh-tw:史拉斯基; 斯盧茨基=>zh-tw:史拉斯基; '),
Item('Bonferroni', 'zh-cn:邦费罗尼; zh-tw:邦佛洛尼;邦費羅尼=>zh-tw:邦佛洛尼;'),
Item('Pearson', 'zh-cn:皮尔逊; zh-tw:皮爾森; 皮爾遜=>zh-tw:皮爾森;'),
Item('Kolmogorov', 'zh-cn:柯尔莫果洛夫; zh-tw: 科摩哥洛夫; 柯爾莫果洛夫 =>zh-tw: 科摩哥洛夫;'),
Item('Kolmogorov', 'zh-cn:柯尔莫哥洛夫; zh-tw: 科摩哥洛夫; 柯爾莫哥洛夫 =>zh-tw: 科摩哥洛夫;'),
Item('[[:en:Ronald Fisher| Ronald Fisher]]', 'zh-cn:费希尔; zh-tw:費雪; 費希爾 =>zh-tw:費雪;'),
Item('Frobenius', 'zh-cn:弗罗贝尼乌斯; zh-tw:弗比尼斯;'),
Item('Hausdorff', 'zh-cn:豪斯多夫; zh-tw:郝斯多夫;'),
Item('L\' Hôpital', 'zh-cn:洛必达; zh-tw:羅必達; zh-hk:洛必達;'),
Item('Legendre', 'zh-cn:勒让德; zh-tw:勒壤得;'),
Item('Levi-Civita', 'zh-cn:列维-奇维塔; zh-tw:勒維奇維塔;'),
Item('Liouville', 'zh-cn:刘维尔; zh-tw:萊歐維爾;'),
Item('Markov', 'zh-cn:马尔可夫; zh-tw:馬可夫;'),
Item('Markov', 'zh-cn:马尔可夫; zh-tw:馬可夫; 馬爾可夫=>zh-tw:馬可夫;'),
Item('Monte Carlo', 'zh-cn:蒙特卡洛; zh-tw:蒙地卡羅;'),
Item('Pareto', 'zh-cn:帕雷托; zh-tw:柏拉圖; 帕累托 =>zh-tw:柏拉圖; '),
Item('Poisson', 'zh-cn:泊松; zh-tw:卜瓦松; zh-hk:泊松;'),
Item('Schwartz', 'zh-cn:施瓦兹; zh-tw:施瓦次;'),
Item('Sturm', 'zh-cn:施图姆; zh-tw:史特姆;'),
{ type = 'text', text = [[
== 專有名稱 ==
]] },
Item('algebraic dependence', 'zh-cn:代数相关; zh-tw:代數相依;'),
Item('algebraic independence', 'zh-cn:代数无关; zh-tw:代數獨立;'),
Item('algebraically closed field', 'zh-cn:代数闭域; zh-tw:代數閉體;'),
Item('algebraically closed field', '代數閉域=>zh-tw:代數閉體; 代數閉域=>zh-hk:代數閉體; 代數閉域=>zh-mo:代數閉體;'),
Item('algebraically closed field', 'zh-cn:代数封闭域; zh-tw:代數封閉體;'),
Item('algebraically closed field', '代數封閉域=>zh-tw:代數封閉體; 代數封閉域=>zh-hk:代數封閉體; 代數封閉域=>zh-mo:代數封閉體;'),
Item('automorphic form', 'zh-cn:自守形式; zh-tw:自守式;'),
Item('base field', 'zh-cn:基域; zh-tw:基體;'),
Item('Law of large numbers', 'zh-cn:大数定律; zh-tw:大數法則; zh-hk:大數法則;'),
Item('bayes\' theorem', 'zh-cn:贝叶斯法则; zh-tw:貝氏定理; 貝葉斯法則=>zh-tw:貝氏定理;'),
Item('bayes\' theorem', 'zh-cn:贝叶斯定理; zh-tw:貝氏定理; 貝葉斯定理=>zh-tw:貝氏定理;'),
Item('bayes\' theorem', 'zh-cn:贝叶斯理论; zh-tw:貝氏定理; 貝葉斯理論=>zh-tw:貝氏定理;'),
Item('bayesian probability', 'zh-cn:贝叶斯概率; zh-tw:貝氏機率; 貝葉斯概率=>zh-tw:貝氏機率;'),
Item('bayesian statistics', 'zh-cn:贝叶斯统计; zh-tw:貝氏統計; 貝葉斯統計=>zh-tw:貝氏統計;'),
Item('bayes\' inference', 'zh-cn:贝叶斯推断; zh-tw:貝氏推論;'),
Item('bayes\' inference', ' 貝葉斯推論=>zh-tw:貝氏推論; zh-tw:貝氏推論; 貝葉斯推斷=>zh-tw:貝氏推論;'),
Item('bayesian estimator ', 'zh-cn:贝叶斯估计; zh-tw:貝氏估計; 貝葉斯估計=>zh-tw:貝氏估計;'),
Item('posterior probability', 'zh-cn:后验概率; zh-tw:事後機率; zh-hant:後驗概率; 後驗概率=>zh-tw:事後機率;'),
Item('prior probability', 'zh-cn:先验概率; zh-tw:事前機率; zh-hant:先驗概率; 先驗概率=>zh-tw:事前機率;'),
Item('posterior distribution', 'zh-cn:后验分布; zh-tw:事後分布; zh-hant:後驗分布; 後驗分布=>zh-tw:事後分布;'),
Item('prior distribution', 'zh-cn:先验分布; zh-tw:事前分布; zh-hant:先驗分布; 先驗分布=>zh-tw:事前分布;'),
Item('Bézier curve', 'zh-cn:贝塞尔曲线; zh-tw:貝茲曲線;'),
Item('bijection', 'zh-cn:双射; zh-tw:對射;'),
Item('bijection', '雙射=>zh-tw:對射; 雙射=>zh-hk:對射; 雙射=>zh-mo:對射;'),
Item('boolean', 'zh-cn:布尔; zh-tw:布林;'),
Item('boolean algebra', 'zh-cn:布尔逻辑; zh-tw:布林運算;'),
Item('central limit theorem', 'zh-cn:中心极限定理; zh-hk:中心極限定理; zh-tw:中央極限定理;'),
Item('chain', '链式=>zh-tw:連鎖; 链式=>zh-hk:連鎖; 链式=>zh-mo:連鎖;'),
Item('chain', '鏈式=>zh-tw:連鎖; 鏈式=>zh-hk:連鎖; 鏈式=>zh-mo:連鎖;'),
Item('chain', '链锁=>zh-tw:連鎖; 链锁=>zh-hk:連鎖; 链锁=>zh-mo:連鎖;'),
Item('chain', '鏈鎖=>zh-tw:連鎖; 鏈鎖=>zh-hk:連鎖; 鏈鎖=>zh-mo:連鎖;'),
Item('chain rule', 'zh-cn:链式法则; zh-tw:連鎖律;'),
Item('chain rule', '连锁法则=>zh-cn:链式法则; 连锁法则=>zh-sg:链式法则; 连锁法则=>zh-my:链式法则;'),
Item('class field', 'zh-cn:类域; zh-tw:類體;'),
Item('class field', '類域=>zh-tw:類體; 類域=>zh-hk:類體; 類域=>zh-mo:類體;'),
Item('classical group', 'zh-cn:典型群; zh-tw:古典群;'),
Item('closed graph theorem', 'zh-cn:闭图像定理; zh-tw:閉圖定理;'),
Item('coalgebra', 'zh-hans:余代数; zh-hant:餘代數;'),
Item('cochain', 'zh-cn:上链; zh-tw:餘鍵;'),
Item('codomain', 'zh-cn:到达域; zh-tw:對應域;'),
Item('codomain', '对应域=>zh-cn:到达域; 对应域=>zh-sg:到达域; 对应域=>zh-my:到达域;'),
Item('codomain', '到達域=>zh-tw:對應域; 到達域=>zh-hk:對應域; 到達域=>zh-mo:對應域;'),
Item('codomain', '陪域=>zh-tw:對應域; 陪域=>zh-hk:對應域; 陪域=>zh-mo:對應域;'),
Item('codomain', '上域=>zh-tw:對應域; 上域=>zh-hk:對應域; 上域=>zh-mo:對應域;'),
Item('cofactor', 'zh-hans:余因子; zh-hant:餘因子;'),
Item('cofactor', 'zh-hans:余因式; zh-hant:餘因式;'),
Item('cohomology', 'zh-cn:上同调; zh-tw:餘調;'),
Item('cohomotopy', 'zh-cn:上同伦; zh-tw:餘倫;'),
Item('coimage', 'zh-hans:余像; zh-hant:餘像;'),
Item('cokernel', 'zh-hans:余核; zh-hant:餘核;'),
Item('colatitude', 'zh-hans:余纬度; zh-hant:餘緯度;'),
Item('colimit', 'zh-hans:余极限; zh-hant:餘極限;'),
Item('comodule', 'zh-hans:余模; zh-hant:餘模;'),
Item('complementary', 'zh-hans:互余; zh-hant:互餘;'),
Item('complex', 'zh-hans:复形; zh-hant:複形;'),
Item('complex algebra', 'zh-hans:复代数; zh-hant:複代數;'),
Item('complex analytic', 'zh-hans:复解析; zh-hant:複解析;'),
Item('complex cobordism', 'zh-hans:复配边; zh-hant:複配邊;'),
Item('complex coefficient', 'zh-hans:复系数; zh-hant:複系數;'),
Item('complex conjugate', 'zh-hans:复共轭; zh-hant:複共軛;'),
Item('complex differentiable', 'zh-hans:复可微; zh-hant:複可微;'),
Item('complex exponential', 'zh-hans:复指数; zh-hant:複指數;'),
Item('complex geometry', 'zh-hans:复几何; zh-hant:複幾何;'),
Item('complex line bundle', 'zh-hans:复线丛; zh-hant:複線叢;'),
Item('complex matrix', 'zh-hans:复矩阵; zh-hant:複矩陣;'),
Item('complex number field', 'zh-hans:复域; zh-hant:複域;'),
Item('complex plane', 'zh-cn:复平面; zh-tw:複數平面;'),
Item('complex projective', 'zh-hans:复射影; zh-hant:複射影;'),
Item('complex root', 'zh-hans:复根; zh-hant:複根;'),
Item('complex space', 'zh-hans:复空间; zh-hant:複空間;'),
Item('complex structure', 'zh-hans:复结构; zh-hant:複結構;'),
Item('complex valued', 'zh-hans:复值; zh-hant:複值;'),
Item('variable', 'zh-cn:变量; zh-tw:變數; zh-hk:變量;'),
Item('complex variable', 'zh-cn:复变量; zh-tw:複變數; zh-hk:複變量'),
Item('complex variable', '复变数=>zh-tw:複變數; 复变数=>zh-hk:複變量; 复变数=>zh-mo:複變量;'),
Item('Multivariate statistics', 'zh-cn:多元变量统计; zh-tw:多變量統計;'),
Item('Multivariate statistics analysis', 'zh-cn:多元变量统计分析; zh-tw:多變量統計分析;'),
Item('Multivariate statistics analysis', 'zh-cn:多元变量分析; zh-tw:多變量分析;'),
Item('complex vector', 'zh-hans:复向量; zh-hant:複向量;'),
Item('confidence interval', 'zh-cn:置信区间; zh-tw:信賴區間; zh-hk:置信區間;'),
Item('confidence level', 'zh-cn:置信水平; zh-tw:信心水準; zh-hk:置信水平;'),
Item('conormal bundle', 'zh-hans:余法丛; zh-hant:餘法叢;'),
Item('consecutive exterior angles', 'zh-cn:同旁外角; zh-tw:同側外角;'),
Item('consecutive interior angles', 'zh-cn:同旁内角; zh-tw:同側內角;'),
Item('constant', '常量=>zh-tw:常數; 常量=>zh-hk:常數; 常量=>zh-mo:常數;'),
Item('convolution', 'zh-cn:卷积; zh-hk:卷積; zh-tw:摺積;'),
Item('coordinate', '座標=>zh-cn:坐标; 座標=>zh-sg:坐标; 座標=>zh-my:坐标;'),
Item('coprime', 'zh-cn:互素; zh-tw:互質;'),
Item('cosimplical', 'zh-hans:余单纯; zh-hant:餘單純;'),
Item('Cramer\'s rule', 'zh-cn:克莱姆法则; zh-tw:克拉瑪公式'),
Item('cyclotomic field', 'zh-cn:分圆域; zh-tw:分圓體;'),
Item('cyclotomic field', '分圓域=>zh-tw:分圓體; 分圓域=>zh-hk:分圓體; 分圓域=>zh-mo:分圓體;'),
Item('dependent variable', 'zh-cn:因变量; zh-tw:應變數; zh-hk:應變量;'),
Item('derived algebra', 'zh-cn:导出代数; zh-tw:導來代數;'),
Item('derived functor', 'zh-cn:导出函子; zh-tw:導來函子;'),
Item('derived set', 'zh-cn:导集; zh-tw:導來集;'),
Item('disjoint union', 'zh-cn:不交并; zh-tw:互斥聯集; zh-hk:互斥併集;'),
Item('divided... and left over', 'zh-hans:除余; zh-hant:除餘;'), -- 被……除餘……
Item('divisor', 'zh-cn:约数; zh-tw:因數;'),
Item('dynamical system', 'zh-cn:动力系统; zh-tw:動態系統;'),
Item('eigenfunction', 'zh-cn:本征函数; zh-tw:固有函數;'),
Item('elimination', '消元=>zh-tw:消去;'),
Item('elimination method', 'zh-cn:消元法; zh-hk:消元法; zh-tw:消去法;'),
Item('equation', '方程=>zh-tw:方程式;'),
Item('coefficient', 'zh-cn:系数; zh-tw:係數; zh-hk:系數;'),
Item('product-moment', 'zh-cn:积矩; zh-tw:積動差; 積矩=>zh-tw:積動差; '),
Item('exclusive or', 'zh-cn:异或; zh-tw:互斥或; zh-hk:異或;'),
Item('extension field', 'zh-cn:扩张域; zh-tw:擴張體;'),
Item('extension field', '擴張域=>zh-tw:擴張體; 擴張域=>zh-hk:擴張體; 擴張域=>zh-mo:擴張體;'),
Item('extension field', '扩域=>zh-tw:擴張體; 扩域=>zh-hk:擴張體; 扩域=>zh-mo:擴張體;'),
Item('family of sets', '集合族=>zh-tw:集族; 集合族=>zh-hk:集族; 集合族=>zh-mo:集族;'),
Item('fibonacci sequence', 'zh-cn:斐波那契数列; zh-tw:費氏數列; zh-hk:斐波那契數列;'),
Item('field extension', 'zh-cn:域扩张; zh-tw:體擴張;'),
Item('field extension', '域擴張=>zh-tw:體擴張; 域擴張=>zh-hk:體擴張; 域擴張=>zh-mo:體擴張;'),
Item('field theory', 'zh-cn:域论; zh-tw:體論;'),
Item('field theory', '域論=>zh-tw:體論; 域論=>zh-hk:體論; 域論=>zh-mo:體論;'),
Item('find remainder', 'zh-hans:求余; zh-hant:求餘;'),
Item('finite field', 'zh-cn:有限域; zh-tw:有限體;'),
Item('fractal', 'zh-cn:分形; zh-hk:分形; zh-tw:碎形;'),
Item('Galois field', 'zh-cn:伽罗瓦域; zh-tw:伽羅瓦體;'),
Item('global field', 'zh-cn:整体域; zh-tw:大域體;'),
Item('global field', '整體域=>zh-tw:大域體; 整體域=>zh-hk:大域體; 整體域=>zh-mo:大域體;'),
Item('hidden markov model', 'zh-cn:隐马尔可夫模型; zh-tw:隱藏式馬可夫模型;'),
Item('identity element', 'zh-cn:单位元; zh-tw:單位元素; zh-hk:單位元; zh-mo:單位元素;'),
Item('identity element', '幺元=>zh-tw:單位元素; 幺元=>zh-hk:單位元; 幺元=>zh-mo:單位元素;'),
Item('identity element', '么元=>zh-tw:單位元素; 么元=>zh-hk:單位元; 么元=>zh-mo:單位元素;'),
Item('if and only if', 'zh-cn:当且仅当; zh-tw:若且唯若; zh-hk:當且僅當;'),
Item('imaginary axis', 'zh-cn:虚轴; zh-tw:虛數軸; zh-hk:虛軸;'),
Item('inflection point', 'zh-cn:拐点; zh-hk:拐點; zh-tw:反曲點;'),
Item('inflection point', '反曲点=>zh-cn:拐点; 反曲点=>zh-sg:拐点; 反曲点=>zh-my:拐点;'),
Item('inverse element', 'zh-cn:逆元; zh-tw:反元素;'),
Item('inverse element', '逆元素=>zh-tw:反元素; 逆元素=>zh-hk:反元素; 逆元素=>zh-mo:反元素;'),
Item('invertible element', 'zh-cn:可逆元; zh-tw:可逆元素;'),
Item('irreducible', '既约=>zh-tw:最簡; 既约=>zh-hk:最簡; 既约=>zh-mo:最簡;'),
Item('irreducible element', '既约元=>zh-tw:不可約元素; 既约元=>zh-hk:不可約元素; 既约元=>zh-mo:不可約元素;'),
Item('irreducible element', '既约元素=>zh-tw:不可約元素; 既约元素=>zh-hk:不可約元素; 既约元素=>zh-mo:不可約元素;'),
Item('least squares', 'zh-cn:最小二乘; zh-tw:最小平方;'),
Item('linear dependence', 'zh-cn:线性相关; zh-tw:線性相依; zh-hk:線性相關;'),
Item('linear independence', 'zh-cn:线性无关; zh-tw:線性獨立; zh-hk:線性無關;'),
Item('local field', 'zh-cn:局部域; zh-tw:局部體;'),
Item('mean value theorem', 'zh-cn:中值定理; zh-tw:均值定理; zh-hk:中值定理;'),
Item('monoidal', 'zh-hans:幺半; zh-hant:么半;'),
Item('multiplication table', 'zh-cn:乘法表; zh-tw:乘法表; zh-hk:乘數表;'),
Item('distribution', 'zh-cn:分布; zh-tw:分布; zh-hk:分佈;'),
Item('normal', 'zh-cn:正态; zh-tw:常態; zh-hk:正態;'),
Item('normal', '常态=>zh-cn:正态; 常态=>zh-sg:正态; 常态=>zh-my:正态; 常态=>zh-hk:正態; 常态=>zh-mo:正態;'),
Item('test', 'zh-cn:检验; zh-tw:檢定; zh-hk:檢驗;'),
Item('significant level', 'zh-hans:显著水平; zh-cn:显著性水平; zh-tw:顯著水準; zh-hk:顯著水平; 显著性差异水平=>zh-tw:顯著水準; 显著性差异水平=>zh-hk:顯著水平;'),
Item('normed', 'zh-hans:赋范; zh-hant:賦範;'),
Item('number field', 'zh-cn:数域; zh-tw:數體;'),
Item('number field', '數域=>zh-tw:數體; 數域=>zh-hk:數體; 數域=>zh-mo:數體;'),
Item('object', 'zh-cn:对象; zh-tw:物件;'),
Item('only if', 'zh-cn:仅当; zh-tw:唯若; zh-hk:僅當;'),
Item('operation research', 'zh-cn:运筹学; zh-hk:運籌學; zh-tw:作業研究;'),
Item('optimization', 'zh-cn:最优化; zh-tw:最佳化;'),
Item('optimization', 'zh-cn:最优化; zh-tw:最佳化; zh-hk:最佳化; zh-mo:最佳化;'),
Item('optimization', 'zh-cn:优化; zh-tw:最佳化;'),
Item('optimization', 'zh-cn:优化; zh-tw:最佳化;'),
Item('ordered field', 'zh-cn:有序域; zh-tw:有序體;'),
Item('orthogonal complement', 'zh-cn:正交补; zh-tw:正交補餘;'),
Item('parameter', '母數=>zh-cn:参数; 母數=>zh-hk:參數;'),
Item('nonparametric', 'zh-cn:非参数; zh-tw:無母數; zh-hk:非參數;'),
Item('panel data', 'zh-tw:縱橫資料 ;zh-hans:面板数据 ;'),
Item('path connected', 'zh-cn:道路连通; zh-tw:路徑連通;'),
Item('periodic', 'zh-cn:周期; zh-tw:週期;'),
Item('permutation', 'zh-cn:排列; zh-hk:排列; zh-tw:置換;'),
Item('pivot element', 'zh-tw:軸元; zh-cn:主元;'),
Item('polynomial growth', 'zh-cn:多项式增长; zh-tw:多項式成長;'),
Item('population', 'zh-cn:总体; zh-hk:總體; zh-tw:母體;'),
Item('population', '母体=>zh-cn:总体; 母体=>zh-sg:总体; 母体=>zh-my:总体;'),
Item('[[:en:Macroeconomics|Macroeconomics]]', 'zh-cn:宏观经济; zh-sg:宏观经济; zh-tw:總體經濟; zh-hk:宏觀經濟; '),
Item('primality test', 'zh-cn:素性测试; zh-tw:質數測試;'),
Item('prime element', 'zh-cn:素元; zh-tw:質元素;'),
Item('prime element', '素元素=>zh-tw:質元素; 素元素=>zh-hk:質元素; 素元素=>zh-mo:質元素;'),
Item('prime factor', 'zh-cn:素因数; zh-tw:質因數;'),
Item('prime factor', '质因数=>zh-cn:素因数; 质因数=>zh-sg:素因数; 质因数=>zh-my:素因数;'),
Item('prime factor', '素因數=>zh-tw:質因數; 素因數=>zh-hk:質因數; 素因數=>zh-mo:質因數;'),
Item('prime factor', 'zh-cn:素因子; zh-tw:質因子;'),
Item('prime factor', '质因子=>zh-cn:素因子; 质因子=>zh-sg:素因子; 质因子=>zh-my:素因子;'),
Item('prime ideal', 'zh-cn:素理想; zh-tw:質理想;'),
Item('prime number', 'zh-cn:素数; zh-tw:質數;'),
Item('prime number', '质数=>zh-cn:素数; 质数=>zh-sg:素数; 质数=>zh-my:素数;'),
Item('prime number', '素數=>zh-tw:質數; 素數=>zh-hk:質數; 素數=>zh-mo:質數;'),
Item('prime ring', 'zh-cn:素环; zh-tw:質環;'),
Item('primeness', 'zh-cn:素性; zh-tw:質性;'),
Item('principal square root', 'zh-cn:算术平方根; zh-tw:主平方根;'),
Item('principal square root', '算術平方根=>zh-tw:主平方根; 算術平方根=>zh-hk:主平方根; 算術平方根=>zh-mo:主平方根;'),
Item('probability', 'zh-cn:概率; zh-tw:機率; zh-hk:概率;'),
Item('transform', 'zh-cn:变换; zh-tw:轉換;'),
Item('Pythagorean theorem', 'zh-cn:勾股定理; zh-sg:毕氏定理; zh-tw:畢氏定理; zh-hk:畢氏定理;'),
Item('Pythagorean triple', 'zh-cn:勾股数; zh-sg:毕氏数; zh-tw:畢氏三元數;'),
Item('Pythagorean triple', '勾股數=>zh-sg:毕氏数; 勾股數=>zh-my:毕氏数; 勾股數=>zh-tw:畢氏三元數; 勾股數=>zh-hk:畢氏三元數; 勾股數=>zh-mo:畢氏三元數;'),
Item('Pythagorean triple', '畢氏數=>zh-cn:勾股数; 畢氏數=>zh-tw:畢氏三元數; 畢氏數=>zh-hk:畢氏三元數; 畢氏數=>zh-mo:畢氏三元數;'),
Item('quadratic field', 'zh-cn:二次域; zh-tw:二次體;'),
Item('quasiperiodic', 'zh-hans:准周期; zh-hant:準週期;'),
Item('real axis', 'zh-cn:实轴; zh-tw:實數軸; zh-hk:實軸;'),
Item('real closed field', 'zh-cn:实闭域; zh-tw:實閉體;'),
Item('real closed field', '實閉域=>zh-tw:實閉體; 實閉域=>zh-hk:實閉體; 實閉域=>zh-mo:實閉體;'),
Item('real closed field', 'zh-cn:实封闭域; zh-tw:實封閉體;'),
Item('real closed field', '實封閉域=>zh-tw:實封閉體; 實封閉域=>zh-hk:實封閉體; 實封閉域=>zh-mo:實封閉體;'),
Item('marginal', '边缘=>zh-tw:邊際; 邊緣=>zh-tw:邊際;'),
Item('recurrence', 'zh-cn:递归; zh-tw:遞迴; zh-hk:遞歸;'),
Item('recurrence relation', 'zh-cn:递推关系; zh-tw:遞迴關係; zh-hk:遞歸關係;'),
Item('regression', 'zh-cn:回归; zh-tw:迴歸; 回歸=>zh-tw:迴歸;'),
Item('Autocorrelation', 'zh-cn:自相关; zh-tw:自我相關; zh-hk:自相關;'),
Item('Autoregressive model', 'zh-cn:自回归; zh-tw:自我迴歸; 自迴歸=>zh-tw:自我迴歸;'),
Item('hypothesis testing', 'zh-cn:假设检验; zh-hk:假設檢定; zh-tw:假說檢定;'),
Item('aternative hypothesis', 'zh-cn:备择假设; zh-hk:對立假設; zh-tw:對立假說;'),
Item('null hypothesis', 'zh-cn:零假设; zh-hk:虛無假設; zh-tw:虛無假說; 零假設=>zh-tw:虛無假說; 零假設=>zh-hk:虛無假設; 原假设=>zh-tw:虛無假說; 原假设=>zh-hk:虛無假設;'),
Item('statistical power', 'zh-cn:统计功效;zh-hk:統計功效;zh-tw:檢定力;'),
Item('terminating decimal', 'zh-hans:有限小数;zh-hant:有限小數;zh-hk:有盡小数;'),
Item('non-terminating decimal', 'zh-hans:无限小数;zh-hant:無限小數;zh-hk:無盡小数;'),
Item('non-terminating, recurring decimal', 'zh-hans:无限循环小数;zh-hant:無限循環小數;zh-hk:無盡循環小數;'),
Item('non-terminating, non-recurring decimal', 'zh-hans:无限不循环小数;zh-hant:無限不循環小數;zh-hk:無盡不循環小數;'),
Item('terminating, non-recurring decimal', 'zh-hans:有限不循环小数;zh-hant:有限不循環小數;zh-hk:有盡不循環小數;'),
Item('terminating, recurring decimal', 'zh-hans:有限循环小数;zh-hant:有限循環小數;zh-hk:有盡循環小數;'),
Item('type I error', 'zh-cn:第一类错误; zh-hk:第一型錯誤; zh-tw:型一錯誤; 第一類錯誤=>zh-tw:型一錯誤; 第一型错误=>zh-tw:型一錯誤;'),
Item('type II error', 'zh-cn:第二类错误; zh-hk:第二型錯誤; zh-tw:型二錯誤; 第二類錯誤=>zh-tw:型二錯誤; 第二型错误=>zh-tw:型二錯誤;'),
Item('goodness of fit', 'zh-cn:拟合优度; zh-tw:適合度; 適配度=>zh-tw:適合度;'),
Item('information', 'zh-cn:信息; zh-tw:訊息;'),
Item('scalar', 'zh-cn:标量; zh-tw:純量;'),
Item('scalar curvature', 'zh-cn:数量曲率; zh-tw:純量曲率;'),
Item('sigma notation', '求和号=>zh-tw:求和符號; 求和号=>zh-hk:求和符號; 求和号=>zh-mo:求和符號;'),
Item('simple group', 'zh-cn:单群; zh-tw:單純群;'),
Item('simple lie group', 'zh-cn:单李群; zh-tw:單純李氏群;'),
Item('simplex', 'zh-cn:单纯形; zh-tw:單體;'),
Item('simplicial complex', 'zh-cn:单纯复形; zh-tw:單體複形;'),
Item('singularity', 'zh-cn:奇点; zh-tw:奇異點;'),
Item('singularity', '奇點=>zh-tw:奇異點; 奇點=>zh-hk:奇異點; 奇點=>zh-mo:奇異點;'),
Item('splitting field', 'zh-cn:分裂域; zh-tw:分裂體;'),
Item('statistical noise', 'zh-cn:统计噪声; zh-tw:統計雜訊;'),
Item('subfield', 'zh-cn:子域; zh-tw:子體;'),
Item('tangent bundle', 'zh-cn:切丛; zh-tw:切線束;'),
Item('target set', 'zh-cn:目标集; zh-tw:目標集合;'),
Item('descriptive statistics', 'zh-cn:描述统计; zh-tw: 敘述統計; 描述統計=>zh-tw:敘述統計;'),
Item('statistical inference', 'zh-cn:统计推断; zh-tw:統計推論; 統計推斷=>zh-tw:統計推論;'),
Item('torsion', 'zh-cn:挠率; zh-tw:扭率;'),
Item('transitive', 'zh-cn:传递; zh-tw:遞移;'),
Item('transitive', '傳遞=>zh-tw:遞移; 傳遞=>zh-hk:遞移; 傳遞=>zh-mo:遞移;'),
Item('trichotomy', 'zh-cn:三分律; zh-tw:三一律;'),
Item('trichotomy', '三分法=>zh-tw:三一律; 三分法=>zh-hk:三一律; 三分法=>zh-mo:三一律;'),
Item('uniform boundedness principle', 'zh-cn:一致有界性原理; zh-tw:均勻有界原理;'),
Item('uniform continuity', 'zh-cn:一致连续; zh-tw:均勻連續;'),
Item('uniform convergence', 'zh-cn:一致收敛; zh-tw:均勻收斂;'),
Item('uniform neighborhood', 'zh-cn:一致邻域; zh-tw:均勻鄰域;'),
Item('uniform norm', 'zh-cn:一致范数; zh-tw:均勻範數;'),
Item('uniform space', 'zh-cn:一致空间; zh-tw:均勻空間;'),
Item('union', 'zh-cn:并集; zh-tw:聯集; zh-hk:併集;'),
Item('unitary group', 'zh-cn:酉群; zh-tw:么正群;'),
Item('unitary matrix', 'zh-cn:酉矩阵; zh-tw:么正矩陣;'),
Item('unitary space', 'zh-cn:酉空間; zh-tw:么正空間;'),
Item('bias', '偏誤=>zh-cn:偏差; 有偏=>zh-tw:偏誤'), -- 「偏差」容易過度轉換
Item('unbiased', 'zh-cn:无偏; zh-hk:無偏; zh-tw:不偏;'),
Item('likelihood', 'zh-cn:似然; zh-hk:似然; zh-tw:概似;'),
Item('variance', 'zh-cn:方差; zh-tw:變異數; zh-hk:方差;'),
Item('covariance', 'zh-cn:协方差; zh-tw:共變異數; zh-hk:協方差;'),
Item('cross-covariance', 'zh-cn:互协方差; zh-tw:交叉共變數; zh-hk:互協方差;'),
Item('heteroscedasticity', 'zh-cn:异方差; zh-tw:異質變異數; zh-hk:異方差;'),
Item('versed cosine', 'zh-hans:余矢; zh-hant:餘矢;'),
Item('zero element', 'zh-cn:零元; zh-tw:零元素;'),
{ type = 'text', text = [=[
[[Category:公共转换组模块|{{SUBPAGENAME}}]]
[[Category:数学模板|{{PAGENAME}}]]
]=] },
},
}
